cloudify-cosmo/cloudify-stage

e2e/pages/filter.js

Removed 10s wait condition from filter commands.

E2E tests stabilization - small update

---

app/components/Help.js
app/components/layout/Header.js
app/containers/Help.js
app/styles/style.scss

https://docs.cloudify.co - Documentation
https://cloudify.co/academy - Tutorials
https://cloudify.co/knowledge-base/ - Knowledge Base
https://cloudify.co/community - Contact Us
https://react.semantic-ui.com/elements/icon

CY-122 - Help menu links

---

e2e/config.json

It shall fix the problem with E2E tests we encountered here:
http://jenkins-master.gspaces.com:8080/user/limor/my-views/view/cloudify-premium/job/dir_ui/job/new-ui/job/Stage-SystemTests/254/console

E2E Tests - Updated manager version

---

backend/config.js

Fixed path resolution for user data configuration.

CY-121 - Separate user configuration from internal configuration - fix

---

widgets/common/src/Consts.js
widgets/common/src/RolesPresenter.js
widgets/tenants/src/TenantDetails.js
widgets/userGroups/src/GroupDetails.js
widgets/userGroups/src/UserGroupsTable.js
widgets/userManagement/src/UserDetails.js
widgets/userManagement/src/UsersTable.js
widgets/userManagement/src/widget.js

CY-139 - Change role display in user management widget

---

app/components/Widget.js
e2e/tests/login.js

- Fixed widget buttons clickability in Edit Mode
- Fixed error in browsers console - no `key` prop for array defined components

CY-180 - Cannot remove widget in Edit Mode

---

app/components/Help.js
app/utils/WidgetDefinition.js

* Updated ExternalLink component to have also Icon anchored instead of only text
* Updated WidgetDefinition to set default values for all optional widget's settings

CY-179 - Minor changes to Stage Help

---

app/components/Breadcrumbs.js
app/components/basic/Dropdown.js
app/components/basic/Menu.js
app/components/basic/index.js
e2e/commands/addBlueprint.js
e2e/commands/addUser.js
e2e/commands/ensureUserIsPresent.js
e2e/commands/prepareTestWidget.js
e2e/commands/removeDeployment.js
e2e/commands/selectOptionInDropdown.js
e2e/commands/selectOptionInPopupMenu.js
e2e/pages/blueprintSources.js
e2e/pages/blueprints.js
e2e/pages/deployments.js
e2e/pages/filter.js
e2e/pages/page.js
e2e/pages/userManagement.js
e2e/pages/widgetBackend.js
e2e/tests/blueprints.js
e2e/tests/deployments.js
e2e/tests/widgetBackend.js
package-lock.json
package.json

- Simplified Dropdown component
- Added option-value attributes to PopupMenu and Dropdown options elements
- Fixed Breadcrumbs after React upgrade
- Improved system tests after major changes in dependencies

Post-optimization system tests update

---

e2e/nightwatch.json
e2e/pages/page.js
e2e/tests/managerInfo.js
package-lock.json
package.json

- Update managerInfo system test in UI
- Upgraded nightwatch version and configuration
- Updated package-lock.json

CY-311 - Update managerInfo system test in UI

---

package-lock.json
package.json
widgets/executions/src/ExecutionsTable.js
widgets/executions/src/UpdateDetailsModal.js
widgets/executions/src/actions.js

1. New icon in executions widget (only for **update** executions)
2. New modal on click on magnifier icon
- no blueprint changed
- blueprint changed

CY-313 - Add inputs button to executions widget

---

widgets/deployments/src/DeploymentsList.js
widgets/deployments/src/MenuAction.js

Changed name of the option in deployments widget menu - 'Edit' to 'Update'

CY-314 - Add deployment update feature to deployments widget

---

widgets/common/src/DeployBlueprintModal.js
widgets/common/src/UpdateDeploymentModal.js
widgets/deploymentButton/src/DeployModal.js

Deployment update and Deployment creation fixed:

CY-360 - Non-string inputs not handled properly when YAML input used for deployment creation/update

---

app/actions/widgets.js

CY-343 - Duplicated widgets in deployment drill-down page

---

app/components/basic/dataSegment/DataSegment.js
app/components/basic/dataTable/DataTable.js
app/components/basic/dataTable/TableSearch.js

- Fetching data (after search input change):
- Idle state:

CY-387 - Add loading indicator to table/catalog search input

---

widgets/executions/src/ExecutionsTable.js
widgets/plugins/src/PluginsTable.js

Both - Executions and Plugins tables - updated.

CY-369 - Implemented removing ID popup on click outside popup

---

widgets/common/src/UpdateDeploymentModal.js

This is after Yariv's comment: https://cloudifysource.atlassian.net/browse/CY-396?focusedCommentId=64347&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-64347

CY-401 - Removed disabling and toggle unset of install_first and ignore_failure fields

---

widgets/common/src/UploadBlueprintModal.js

- added labels
- added mandatory indicator
- removed explicit field's width specification
- removed unnecessary field's grouping

CY-391 - Update Upload modal from Blueprint widget

---

widgets/blueprintCatalog/src/RepositoryList.js
widgets/blueprintCatalog/src/UploadModal.js

- added labels
- added automatic filling of both fields
- added help description

CY-389 - Update Upload modal from Blueprint Catalog

---

app/components/InstallWidgetModal.js

- converted to commont input for URL and file
- added label
- improved error message

CY-390 - Update Widget Install modal

---

app/styles/style.scss
widgets/common/src/UploadBlueprintModal.js
widgets/userManagement/src/CreateModal.js
widgets/userManagement/src/UsersTable.js

CY-402 - Adding the ability to create a user with a tenant in UI

---

templates/pages/blueprints-community.json
templates/pages/blueprints.json
widgets/blueprints/src/widget.js

CY-422 - Change the default settings of the local blueprint widget to "table" instead of "catalog"

---

templates/pages/catalog-community.json
templates/pages/catalog.json

CY-423 - Plugin catalog to be added to initial templates of the roles: Admin, tenant manager, user

---

app/components/Manager.js
app/containers/Manager.js

CY-424 - Service status indicator in web UI shows green even when some services are down

---

backend/consts.js
backend/package-lock.json
backend/package.json
backend/routes/Auth.js
backend/routes/Style.js
backend/server.js
conf/app.json
devServer.js
e2e/commands/removeLastPage.js
e2e/tests/blueprintInfo.js
e2e/tests/blueprintSources.js
e2e/tests/blueprints.js
e2e/tests/deployments.js
e2e/tests/editMode.js
e2e/tests/installWidget.js
e2e/tests/plugins.js
e2e/tests/widgetBackend.js
webpack.config-prod.js
webpack.config.js

Removed contextPath from app.json configuration file

CY-434 - UI fails to load after snapshot

---

app/actions/tours.js
app/components/ToursButton.js
app/components/basic/PopupMenu.js
app/utils/Tours.js
widgets/common/src/ExecuteDeploymentModal.js
widgets/common/src/ExecutionStatus.js
widgets/common/src/ExecutionUtils.js
widgets/deploymentActionButtons/src/DeploymentActionButtons.js
widgets/deployments/src/ActiveExecutionStatus.js
widgets/executions/src/ExecutionsTable.js

Added new option for cancelling execution - Kill (CY-446)

---

widgets/common/src/DeploymentUtils.js
widgets/deploymentActionButtons/src/widget.js
widgets/deployments/src/widget.js

CY-436 - Make "Update" workflow internal only (in the use of "Deployment Update" operation

---

.circleci/config.yml
README.md
app/actions/tours.js
app/utils/Tours.js
backend/package-lock.json
package-lock.json
package.json
scripts/updateReadmes.js

- divided building process into visualized steps 
- added widget documentation (README.md files) vs. official documentation (.md files in docs.cloudify.co) sync check
- added section for custom widget developers
- added section about widget documentation script (recently added)
- Added error handling in tours for case when next step is on the same page and next step target is not present
- Updated targets for error callouts - logo for case when 404 error page is shown and tours button for other cases

Improved CircleCI, internal documentation and error handling in tours

---

widgets/pluginsCatalog/src/widget.js

support https and avoiding "mixed content" errors

support https

---

widgets/common/src/UploadPluginForm.js
widgets/deploymentWizardButtons/src/steps/InputsStep.js
widgets/deploymentWizardButtons/src/steps/PluginsStep.js
widgets/deploymentWizardButtons/src/steps/SecretsStep.js

* Add placeholder to secret input field - 'Provide secret value'
* Remove red asterisk from inputs and plugins fields

CY-629 - Implement post-review changes

---

app/styles/style.scss
widgets/nodes/src/NodeInstanceModal.js

Fixed both defects:
- CY-667 - Runtime Properties outside of the window in node instance details modal
- CY-668 - Invalid pagination in Runtime Properties table in nodes widget

Node instances modal improvements (CY-667, CY-668)

---

widgets/deploymentWizardButtons/src/steps/InfrastructureStep.js

CY-681 - Improve error message in Deployment Wizard

---

.size-limit
app/utils/External.js
backend/handler/ArchiveHelper.js
backend/handler/SourceHandler.js
backend/routes/File.js
e2e/pages/blueprints.js
e2e/resources/singleYamlBlueprint.yaml
e2e/tests/blueprints.js
package-lock.json
package.json
widgets/common/src/BlueprintActions.js
widgets/common/src/UploadBlueprintForm.js

All places where blueprint upload form is used:
- Upload Blueprint widget, 
- Blueprints widget - Upload button, 
- Deployment Wizard - Blueprint step
were affected by that change.

CY-718 - Support for providing a YAML file instead of only archive in blueprint upload form

---

widgets/blueprints/src/BlueprintsCatalog.js
widgets/blueprints/src/BlueprintsList.js
widgets/blueprints/src/BlueprintsTable.js
widgets/common/src/DeployBlueprintModal.js
widgets/deploymentButton/src/DeployModal.js
widgets/deployments/src/DeploymentsList.js
widgets/deployments/src/DeploymentsSegment.js
widgets/deployments/src/DeploymentsTable.js
widgets/deployments/src/widget.js

CY-793 - Allow setting deployment visibility to `global`

---

templates/pages/blueprint.json
templates/pages/deployment.json
widgets/outputs/src/OutputsTable.js
widgets/outputs/src/widget.js

CY-794 - Update Outputs widget to show deployment's capabilities

---

widgets/managers/src/ManagersTable.js
widgets/managers/src/SlavesDetails.js

CY-1011 - Fix alignment in Cloudify Manager of Managers widget

---

widgets/common/src/InputsUtils.js
widgets/common/src/WorkflowsMenu.js
widgets/deploymentActionButtons/src/DeploymentActionButtons.js
widgets/deployments/src/MenuAction.js
widgets/managers/src/ExecuteWorkflowButton.js
widgets/managers/src/ExecuteWorkflowIcon.js

CY-1005 - Group list of workflows to execute in dropdowns

---

widgets/common/src/WorkflowsMenu.js

Added name prop to Menu.Item component in WorkflowsMenu to allow handling menu items properly in system tests.

Fix for Deployment system test

---

app/components/WidgetDynamicContent.js
widgets/userManagement/src/CreateModal.js
widgets/userManagement/src/UsersTable.js

Fixed memory leak in the application - WidgetDynamicContent and CreateModal (in user management widget) components.

CY-1025 - Memory leak in the application - WidgetDynamicContent component

---

app/components/WidgetsList.js
app/components/basic/ErrorMessage.js
backend/config.js
e2e/pages/deployments.js
package.json
webpack.config-prod.js
webpack.config.js
widgets/common/src/DeploymentActions.js
widgets/common/src/InputsUtils.js
widgets/common/src/UpdateDeploymentModal.js
widgets/common/src/UpdateDetailsModal.js

- improved Deployment Update details modal: show steps, modified node instances, allow showing only modified inputs
- fixed minor bugs in Deployment Update modal and details modal

CY-1004 - Added possibility to preview Deployment Update in UI

---

app/components/basic/ErrorMessage.js
app/components/basic/form/Form.js
widgets/common/src/DeployBlueprintModal.js
widgets/common/src/ExecuteDeploymentModal.js
widgets/common/src/UpdateDeploymentModal.js
widgets/deploymentButton/src/DeployModal.js

Updated:
- Deployment Creation modal
- Deployment Update modal
- Execute Workflow modal

CY-1066 - User not informed properly about the error after form submission

---

app/actions/app.js
app/actions/managers.js
app/actions/version.js
app/components/LicensePage.js
app/components/license/CurrentLicense.js
app/components/license/UploadLicense.js
app/reducers/licenseReducer.js
app/utils/auth.js
backend/routes/Auth.js

CY-1152 - Update description messages for non-admin users in License Management page

---

app/components/LicensePage.js
app/containers/LicensePage.js
test/components/LicensePageTest.js
test/reducers/licenseReducerTest.js
test/resources/licenses.js
test/resources/rbac.js
test/resources/versions.js
test/setup.js

- Added tests for license redux actions/reducer
- Added tests for LicensePage component

CY-1139 - Tests for License Management

---

app/components/LicensePage.js
app/components/license/CurrentLicense.js
app/components/license/UploadLicense.js
test/components/LicensePageTest.js
test/resources/licenses.js

CY-1156 - Handle licenses without expiration date & CY-1158 - Change Upload to Update in button label and description

---

app/components/basic/form/FormField.js
backend/db/Connection.js
widgets/common/src/DeployBlueprintModal.js
widgets/common/src/InputsUtils.js
widgets/common/src/UpdateDeploymentModal.js
widgets/deploymentButton/src/DeployModal.js
widgets/deploymentWizardButtons/src/steps/InputsStep.js

* Improved help description
* Limit selection to only valid values (when valid_values constraint is set)
* Allow only values according to range limitatations (greater..., less..., in_range constraints)

CY-1075 - Added support for inputs constraints in UI

---

.size-limit
app/index.tmpl.html
backend/routes/Style.js
backend/server.js
conf/userConfig.json
webpack.config-prod.js
webpack.config.js

Moved all static (non-authenticated) content to /dist/static

CY-1122 - In Console, static content should be served by nginx rather than NodeJS

---

.circleci/config.yml
backend/config.js
backend/db/Connection.js
backend/migration.js
test/backend/migrationTest.js

Fixed migration script to provide latest migration installed properly on 'current' command

CY-1254 - Restoring a 4.6 snapshot into 5.0 results in an error

---

package.json
test/nightwatch/globals.js

First nightwatch, then cypress tests.

Change e2e running order

---

test/cypress/integration/templates_spec.js

- Due to pages ordering change

sites: fix test

---

.size-limit
templates/pages/deploy.json
widgets/deployments/src/widget.js
widgets/filter/src/Filter.js
widgets/filter/src/widget.js

* Add the ability to filter deployments by site name
* Add this filter to the deployments page

CY-1343 Add site to the filter widget

---

backend/package-lock.json
package-lock.json
package.json

- updating topology widget and package lock

Version change to 5.0.0

---

widgets/common/src/DeployBlueprintModal.js
widgets/deploymentButton/src/DeployModal.js

* Add the input `Site name` to DeployBlueprintModal.
* Move up the 'Site name' input
* Add help texts to the inputs

CY-1363 Add site to deployment create in DeployBlueprintModal

---

backend/package.json
package-lock.json
package.json
test/nightwatch/config.json
widgets/blueprintCatalog/README.md
widgets/pluginsCatalog/README.md

- Also use latest topology widget version

Bump version to 5.0.5

---

.circleci/config.yml
doc/esdoc.json

* Added components documentation check to CircleCI configuration
* Fixed favicon link in ESDoc configuration

CY-1472 - Update cloudify-stage repository - documentation fix

---

.gitignore
backend/db/Connection.js
backend/package-lock.json
backend/package.json
conf/me.json.template
devServer.js
scripts/uploadPackage.sh
test/nightwatch/globals.js
webpack.config.js

- Upgraded DB-related dependencies - pg, sequelize, sequelize-cli - to the latest stable (no issues found).
Additional, minor updates:
- Fixed minor issues with webpack dev server configuration
- Removed references to unused log4js library
- Removed license upload before starting nightwatch tests (CY-1690)
- Added script for waiting on stage backend server starts
- Updated .gitignore file

CY-1734 - Composer db migration intermittently failing due to seg fault

---

templates/pages/adminDash.json
widgets/sitesMap/src/widget.js

- Added Sites Map to sys-admin initial template
- Fixed minor issue with dimension setting in Sites Map widget

CY-1592 - Create the Spire dashboard template

---

widgets/sitesMap/src/widget.js

CY-1769 - Add filtering by blueprints/deployments to Sites Map widget

---

app/actions/status.js
app/components/Manager.js
app/components/Services.js
app/components/layout/Header.js
app/containers/Manager.js
app/containers/Services.js
app/utils/consts.js
test/components/ManagersComponentTest.js

CY-1795 - Update Manager Service Status to use new /status REST API

---

widgets/snapshots/src/CreateSnapshotModal.js
widgets/snapshots/src/actions.js

* Updated Snapshot ID field
* Remove "Include metrics data" flag
* Added missing "Queue" flag
* Refactored code to be more compatible with internal code style

CY-1801 - Remove "Include metrics data" flag from the Create Snapshot modal

---

devServer.js
package-lock.json
package.json
scripts/readmesConfig.json
test/cypress/integration/templates_spec.js
widgets/blueprintCatalog/README.md
widgets/blueprintUploadButton/README.md
widgets/blueprints/README.md
widgets/deployments/README.md
widgets/events/README.md
widgets/sites/README.md
widgets/sitesMap/README.md
widgets/snapshots/README.md
widgets/topology/README.md

In addition to system test fix:
- Updated widget's documentation
- Updated webpack to fix random "WDS Disconnected" issue

Fix Template Management system test

---

app/components/Tenants.js

CY-1867 - Add scroll bar and alphabetically sort Tenant selection list/widget

---

app/components/Manager.js
test/nightwatch/pages/page.js

CY-1899 - Modify the health icon used in the UI top banner

---

app/components/InstallWidgetModal.js
package-lock.json
package.json
widgets/common/src/UploadBlueprintForm.js
widgets/common/src/UploadPluginForm.js
widgets/snapshots/src/UploadSnapshotModal.js

As cloudify-ui-components 0.0.7 included some breaking changes to UrlOrFileInput component cloudify-stage had to be updated accordingly

cloudify-ui-components updated to 0.0.7

---

test/cypress/integration/spire_manager_spec.js

It seems CircleCI build fails due to https://github.com/cloudify-cosmo/cloudify-stage/pull/893 not being merged

Fix for failing system tests

---

scripts/readmesConfig.json
scripts/updateReadmes.js
widgets/blueprintCatalog/README.md
widgets/highAvailability/README.md
widgets/managers/README.md
widgets/sitesMap/README.md

Updated widgets README.md files to be in sync with official docs

CY-1782 - Update widgets documentation

---

app/components/Help.js
app/containers/Help.js
package-lock.json
test/components/HelpComponentTest.js

CY-2168 - Links in help menu

---

app/components/Manager.js
app/components/basic/cluster/ClusterService.js
app/components/status/SystemStatusHeader.js

CY-2185 - Improve External label placement in Cluster Status widget and System Status popup

---

backend/package-lock.json

Contains no direct dependency updates - implicit sub-dependencies update only.

Fix for pm2 subdependency vulnerability

---

app/actions/clusterStatus.js
app/components/maintenance/MaintenanceModePageMessage.js
app/containers/maintenance/MaintenanceModePageMessage.js
app/reducers/clusterStatusReducer.js
app/utils/StatusPoller.js
test/cypress/fixtures/cluster_status/fail.json
test/cypress/fixtures/cluster_status/summary-degraded.json
test/cypress/integration/cluster_status_spec.js
widgets/highAvailability/src/widget.js

Continuation of https://github.com/cloudify-cosmo/cloudify-stage/pull/901
Changes:

CY-2184 - System status icon not up to date (cont.)

---

backend/package-lock.json
backend/package.json

Reverts cloudify-cosmo/cloudify-stage#853

CY-1770 - Upgrade node-postgres package to the latest version

---

test/cypress/integration/spire_manager_spec.js

Build #1019 in Jenkins is running to check whether this change fix stage system tests.

Spire Manager system test fix

---

package-lock.json
package.json
widgets/executions/src/tasksGraph/ExecutionWorkflowGraph.js

SVG now fits into the table and doesn't break layout anymore.

Enabled execution graph panning and zooming

---

.size-limit
app/app.js
package-lock.json
package.json
webpack.config.js
widgets/blueprintCatalog/src/actions.js
widgets/blueprintCatalog/src/widget.js
widgets/common/src/Consts.js
widgets/common/src/NoDataMessage.js
widgets/deploymentWizardButtons/src/steps/InfrastructureStep.js
widgets/deploymentWizardButtons/src/steps/PluginsStep.js
widgets/deploymentWizardButtons/src/urls.js
widgets/deploymentWizardButtons/src/widget.js
widgets/pluginsCatalog/src/widget.js
widgets/sitesMap/src/SitesMap.js

* Replaced semantic-ui css with offline version that doesn't import fts from googleapis
* Updated blueprint catalog, plugins catalog and deployment wizard widgets to handle lack of Internet connection gracefully

Fixes for Internet disconnected environments

---

widgets/topology/src/Topology.js

Added confirmation popup for layout save operation

---

widgets/topology/src/DataProcessor.js

Hide instance count for uninitialized nodes

---

scripts/preinstall.sh
widgets/executions/src/tasksGraph/ExecutionWorkflowGraph.js
widgets/executions/src/tasksGraph/GraphEdge.js

New icon was placed near existing "open in window" icon:

Enhanced task graph to allow automatic scrolling and focusing on tasks in progress

---

widgets/executions/src/tasksGraph/ExecutionWorkflowGraph.js
widgets/executions/widget.css

Added minimap and "fit to view" toolbar button

---

widgets/executions/src/backend.js
widgets/executions/src/tasksGraph/ExecutionWorkflowGraph.js
widgets/executions/src/tasksGraph/GraphEdge.js
widgets/executions/src/tasksGraph/GraphNode.js
widgets/executions/src/tasksGraph/States.js
widgets/executions/widget.css

Updated execution graph look-and-feel

---

widgets/common/src/InputsUtils.js

There are no tests at the moment, but I found a way to solve issue blocking *CY-1205 - Add system tests for input types and constraints*. I'd like to do the proper testing within CY-1205. Waiting for Alex's opinion.

CY-1283 - Fixed InputUtils to handle null default value properly

---

.size-limit
backend/handler/ManagerHandler.js
backend/routes/Plugins.js
backend/routes/ServerProxy.js
widgets/common/src/PluginIcon.js
widgets/plugins/src/PluginsTable.js
widgets/plugins/src/widget.js
widgets/pluginsCatalog/src/PluginsCatalogList.js

CY-2588 Added plugin icon to plugins list widget

---

backend/routes/Plugins.js
widgets/common/src/PluginActions.js
widgets/common/src/UploadPluginForm.js
widgets/common/src/UploadPluginModal.js
widgets/deploymentWizardButtons/src/steps/ConfirmationStep.js
widgets/deploymentWizardButtons/src/steps/PluginsStep.js

CY-2577 Added field in plugin upload form to provide an icon file

---

app/components/Widget.js
test/cypress/integration/deployment_inputs_spec.js
test/cypress/integration/topology_spec.js
test/cypress/support/blueprints.js
test/cypress/support/commands.js
test/cypress/support/deployments.js
widgets/topology/src/DataFetcher.js
widgets/topology/src/Topology.js
widgets/topology/src/widget.js

* Fixed WSOD problem after opening Deployment page
* Added basic system test for Topology widget
* Fixed some of the linting errors in Topology widget
* Added error boundary for widgets to catch JS errors in widgets

CY-2573 - Fix for WSOD after opening Deployments page

---

backend/routes/Plugins.js
test/nightwatch/pages/plugins.js
widgets/plugins/src/widget.js

- fixed invalid manager requests performed by stage backend
- fixed broken paging and searching
- replaced `Promise.allSettled` with `Promise.all` as `allSettled` is not supported by browser running nightwatch tests
- fixed nightwatch test

Fixes around plugins widget

---

.size-limit
widgets/common/src/DynamicDropdown.js
widgets/eventsFilter/src/EventFilter.js
widgets/executions/src/ExecutionsTable.js
widgets/executions/src/backend.js
widgets/executions/src/tasksGraph/ExecutionWorkflowGraph.js
widgets/executions/src/tasksGraph/GraphNode.js
widgets/executions/src/tasksGraph/GraphNodes.js
widgets/executions/widget.css
widgets/filter/src/Filter.js

See https://cloudifysource.atlassian.net/browse/CY-2235 for screenshots

CY-2235 Extended execution tasks graph to include retry count and logs refinement button

---

widgets/common/src/ExecuteDeploymentModal.js

Small fix without JIRA issue. It was consulted with Ofer.

Changed icons in ExecuteDeploymentModal

---

test/cypress/fixtures/license/valid_spire_license.yaml
test/cypress/integration/cluster_status_spec.js
test/cypress/integration/deployment_create_spec.js
test/cypress/integration/deployment_inputs_spec.js
test/cypress/integration/filter_spec.js
test/cypress/integration/topology_spec.js
test/cypress/integration/tours_spec.js

Changed license for tests where it is not necessary to use spire edition.

Fix spire license

---

test/nightwatch/pages/blueprintSources.js
test/nightwatch/pages/blueprints.js
test/nightwatch/tests/blueprintSources.js
test/nightwatch/tests/blueprints.js

- Removed part responsible for removing deployment in Blueprints test
- Updated tested blueprint

Partial fix for nightwatch tests

---

.circleci/config.yml
backend/package-lock.json
backend/package.json
package.json

- updated `decompress` and `pm2` to fix vulnerability issues
- added audit job to Circle CI build

CY-1720 Enabled npm audit in Circle CI build

---

widgets/common/src/InputsHeader.js

CY-2739 - Added more detailed description about handling types of deployment inputs

---

scripts/uploadPackage.sh

* Changed rsync to cp&rm in uploadPackage.sh

Improve uploadPackage script

---

.size-limit
Jenkinsfile
webpack.config.js

- Removed brotli from size-limit
- Improved dist folder deletion in production build

CY-2541 - Jenkins build fix 

---

app/components/AddWidgetModal.js
app/components/EditModeButton.css
app/components/EditModeButton.js
app/components/Page.js
app/components/PageContent.js
app/components/PagesList.js
app/containers/AddPageButton.js
app/containers/Page.js
app/styles/style.scss
test/cypress/integration/tabs_spec.js

CY-2894 Added ability to add widgets to predefined tabs

---

.size-limit
app/actions/managers.js
app/components/Users.js
app/components/shared/PasswordModal.js
app/components/shared/index.js
app/containers/Users.js
app/reducers/managerReducer.js
backend/handler/AuthHandler.js
backend/routes/Auth.js
test/components/UsersComponentTest.js
test/cypress/integration/change_password_spec.js
test/cypress/support/commands.js
test/reducers/licenseReducerTest.js
widgets/userManagement/src/MenuAction.js
widgets/userManagement/src/UsersTable.js

* Moved PasswordModal component to shared components (updated header, labels and button name)
* Added checking if manager is in LDAP mode during login procedure
* Added Change Password option to users menu
* Added integration tests for new feature (without LDAP mode check)

CY-2908 - Add Change Password option in UI top menu

---

jenkins/Jenkinsfile
jenkins/build-pod.yaml

Fix pipeline size stage exception

Fix pipeline size stage exception

---

packaging/cloudify-stage.spec
scripts/uploadPackage.sh

* Fixed upload script
* Added `nginx` to `stage_group` to provide access to static resources

Fix package upload permissions

---

backend/handler/LoggerHandler.js
backend/server.js
conf/README.md
conf/userConfig.json

- Added logLevel option to user configuration
- Changed default log level to WARN from DEBUG

CY-2200 - Change default logging level

---

conf/app.json
jenkins/Jenkinsfile

CY-2947 update map key

---

widgets/common/src/MapsActions.js
widgets/sitesMap/src/SitesMap.js

Already implemented that for 5.0.5.
Porting back two changes I spotted when working on solution for 5.0.5.

CY-2684 - Fix for caching issue

---

app/actions/drilldownPage.js
app/actions/page.js
app/reducers/pageReducer.js
app/utils/Toolbox.js
templates/pages/deployment.json
test/cypress/integration/widgets/deployment_info_spec.js
test/cypress/integration/widgets/executions_spec.js
test/reducers/pagesReducerTest.js
widgets/common/src/LastExecutionStatusIcon.js
widgets/deployments/src/DeploymentsList.js
widgets/deployments/src/DeploymentsSegment.js
widgets/deployments/src/DeploymentsTable.js
widgets/eventsFilter/src/EventFilter.js
widgets/executions/src/ExecutionsTable.js
widgets/executions/src/SingleExecution.js
widgets/executions/src/tasksGraph/ExecutionWorkflowGraph.js
widgets/executions/src/widget.js
widgets/managers/src/ManagersTable.js

CY-2953 - Deployment page new layout

---

widgets/common/src/LastExecutionStatusIcon.js
widgets/eventsFilter/src/EventFilter.js

* Updated button colors in LastExecutionStatusIcon component
* Improved handling of Reset Filter button in Event Filter widget (before the Reset Filter was not enabled in all cases)

CY-2953 - Improve Deployment page new layout

---

widgets/executions/src/tasksGraph/ExecutionWorkflowGraph.js

- Added fit to view by default
- Fixed zoom calculation in fitToView method
- Stopped showing status in modal window
- Fixed setting auto focus
- Optimized componentDidUpdate method
- Simplified render method

CY-3170 - Execution Tasks Graph by default load with fit-to-view 

---

widgets/plugins/src/PluginsTable.js

- Unset force by default in plugin delete confirmation modal
- Fixed most of the linter issues in PluginsTable component 
- Updated to use Semantic UI React components

CY-3133 - Unset force by default in plugin delete confirmation modal

---

templates/pages/adminDash.json
templates/pages/app.json
test/cypress/integration/widgets/button_link_spec.js
widgets/buttonLink/src/widget.js

CY-3245 Replaced deployment wizard with "getting started" link button

---

package-lock.json
package.json
test/cypress/integration/templates/template_management_spec.js
test/cypress/integration/tenants_spec.js
test/cypress/integration/widgets/deployment_inputs_spec.js
test/cypress/integration/widgets/executions_spec.js
tours/main-sys_admin.json

- Fixed Template Management test
- Fixed Tenants test
- Fixed From Blueprint to Execution tour
- Improved Deployment Inputs test
- Improved Executions widget test

Fixed system tests

---

widgets/maintenanceModeButton/README.md
widgets/sitesMap/README.md
widgets/snapshots/README.md

This PR is necessary after introduction of https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1370 .

Sync widget docs with docs.cloudify.co

---

app/components/shared/cluster/NodeServices.js
app/components/shared/cluster/NodeStatus.js
test/cypress/fixtures/cluster_status/fail_with_services.json
test/cypress/integration/widgets/cluster_status_spec.js

CY-3386 - Positioning improvement for node services status popup in Cluster Status widget

---

widgets/common/src/DeploymentDetails.js

CY-3424 Added overflow: auto to deployment description field

---

Jenkinsfile

CY-3526 add maps token to old jenkins

CY-3526 add maps token to old jenkins

---

app/components/AddWidgetModal.js
package-lock.json
package.json

- Updated cloudify-ui-components version (fixes FileInput state loss issue)
- Prevented unwanted events propagation - was causing unnecessary re-renders

CY-3557 Unable to update custom widget by providing package file

---

scripts/updateReadmes.js
widgets/blueprints/README.md
widgets/composerLink/README.md
widgets/deployments/README.md
widgets/executions/README.md
widgets/maintenanceModeButton/README.md
widgets/managers/README.md
widgets/sitesMap/README.md
widgets/snapshots/README.md
widgets/tenants/README.md
widgets/topology/README.md
widgets/userGroups/README.md
widgets/userManagement/README.md

* Updated README.md for 5 widgets
* Added styling for `note`, `tip` and `warning` shortcodes
* Stopped removing HTML tags from the output markdown (as current markdown library is handling it)

CY-3564 - Update widgets' documentation

---

widgets/snapshots/src/SnapshotsTable.jsx

Fix for bugs introduced as part of linter fixes

CY-2601 Snapshots widget fix

---

backend/package-lock.json
backend/package.json
package-lock.json
package.json

This reverts commit 369064d11e636936c397cde84ff1b87c63213865.

Revert "Bump version"

---

widgets/executions/src/backend.js

* Fixed and simplified Executions widget backend to get promise rejection handled properly
* Updated `task.dependencies` parameter to fix unresolvable dependencies

RD-528 - Fix executions widget backend code to display task graph properly

---

backend/package-lock.json
backend/package.json
package-lock.json
package.json

Package versions were not semver compliant (see https://semver.org/#spec-item-10)

RD-1070 Fix package versions

---

test/cypress/integration/widgets/deployments_spec.js

There were 2 problems in the deployments widget system tests. 2 individual commits solve individual issues.
After those fixes, related tests passed :slightly_smiling_face:

RD-1354 RD-1355 (master) Fix deployments widget system tests

---

test/cypress/integration/widgets/deployments_spec.js

Cherry-pick of https://github.com/cloudify-cosmo/cloudify-stage/pull/1189 to 5.2.0

RD-1354 RD-1355 (5.2.0) Fix deployments widget system tests

---

test/cypress/integration/widgets/blueprints_spec.js
widgets/common/src/DynamicDropdown.jsx

Cherry-picked #1192 for `5.2.0-build` branch.

RD-1335 RD-1356 (5.2.0) Fix data fetching issues in DynamicDropdown component and in system tests

---

widgets/topology/src/widget.jsx

5.2 backport approved by Alex.

RD-877 Fix for non-tree component graphs

---

package-lock.json
package.json

A follow-up to https://github.com/cloudify-cosmo/cloudify-blueprint-topology/pull/147

CY-3721 Topology upgrade

---

test/cypress/integration/widgets/deployments_spec.js

* Reused newly added Cypress functions for executions checking
* Increased timeout for executions to 60 seconds
I know it's not perfect, but I think for now it is fine. 
In the future we can either:
* kill-cancel execution just after it is started not to depend on the execution time
* or use different deployments per each test, which will make waiting for execution to finish not necessary.

RD-1577 - Update deployments_spec to work better with long executions

---

.size-limit
package-lock.json
package.json

* Updated `marked` library version (despite major version change I did not spot any issues in all the places where it is used - widget's readme modal, Blueprint Catalog widget)
* Update `package-lock.json` file with simple `npm audit --fix` execution
* Adjusted `.size-limit` for the incoming change from cloudify-ui-components: https://github.com/cloudify-cosmo/cloudify-ui-components/pull/64
Size increase is not big, see:
```
Main JS bundle
Size limit:   285 KB
Size:         283.77 KB
Loading time: 5.7 s     on slow 3G
Running time: 85 ms     on Snapdragon 410
Total time:   5.8 s
Vendor JS bundle
Package size limit has exceeded by 25.75 KB
Size limit:   4.13 MB
Size:         4.16 MB
Loading time: 85.1 s  on slow 3G
Running time: 607 ms  on Snapdragon 410
Total time:   85.8 s
Widgets
Size …
```

RD-1578 - Update dependencies to fix security issues

---

widgets/common/src/labels/LabelsList.jsx

RD-1661 - Increase max-height of LabelsList component

---

widgets/common/src/DeploymentActions.js
widgets/common/src/ExecuteDeploymentModal.jsx
widgets/deploymentActionButtons/src/widget.jsx

As RD-1353 was fixed on the backend side, I took a chance to create small PR and update two places in the code which were waiting for it.

RD-1353 - Optimize fetching of deployment workflows

---

app/translations/en.json
widgets/common/src/DeployBlueprintModal.jsx
widgets/common/src/labels/LabelsModal.jsx

As a continuation of https://github.com/cloudify-cosmo/cloudify-stage/pull/1237 I added i18n support to Deploy Blueprint modal.

RD-1663 - Add i18n support to Deploy Blueprint modal

---

app/translations/en.json
widgets/common/src/UploadBlueprintModal.jsx

* Fixed condition used for checking if Blueprint Icon URL is valid URL
* Added i18n support to the modified file

RD-1750 - Fix adding blueprint icon on blueprint upload

---

widgets/deployments/README.md

Waiting for https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1735 to be merged first.

RD-760 - Update Deployments widget description

---

app/translations/en.json

Change according to e-mail conversation with Ofer:

RD-1803 - Update popup message about using reserved label key

---

backend/package-lock.json
backend/package.json

As https://github.com/node-saml/passport-saml/issues/556 was fixed, I created small PR to make Stage audit happy.

RD-1738 - Update passport-saml version

---

backend/routes/Auth.js
backend/test/routes/Auth.test.js
jenkins/Jenkinsfile

The same change as in #1257 for 5.2.0.

RD-916 (5.2.0) Add security attributes to all used cookies

---

app/utils/Context.ts
app/utils/StageAPI.ts
test/cypress/fixtures/deployments/various-statuses.json
test/cypress/integration/widgets/deployments_view_spec.ts
widgets/deploymentsView/src/renderDeploymentRow.tsx
widgets/deploymentsView/src/styles.scss
widgets/deploymentsView/src/widget.tsx

This PR adds showing the real latest execution progress as it comes from the API. It bases on #1267 
The rules describing the behavior of the progress bar are in https://cloudifysource.atlassian.net/wiki/spaces/WR/pages/1674215425/Deployment+states ("Progress bar" point)
The API documentation for those fields is in https://cloudifysource.atlassian.net/wiki/spaces/WR/pages/1572864001/Environment#Data-Model
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/335/pipeline
Ran 2021-03-25 15:15 CET

RD-1741 Show real latest execution progress

---

test/cypress/integration/widgets/deployments_view_spec.ts
widgets/common/src/deploymentsView/DeploymentsView.tsx

Select the first possible deployment in the Deployments View widget if it is possible.
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/453/pipeline
Ran 2021-04-14 8:34 CEST

RD-2038 Always select the first possible deployment in the table

---

test/cypress/integration/widgets/filters_spec.ts
widgets/filters/src/widget.tsx
widgets/onlyMyResources/src/MyResourcesCheckbox.jsx

System tests build: https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/455/

RD-1123 Added support for "only my resources" context setting

---

widgets/common/src/filters/RuleRow.tsx
widgets/common/src/filters/inputs/LabelValueInput.tsx

RD-2007 - Improve styling for Label type inputs

---

test/cypress/integration/widgets/filters_spec.ts
widgets/filters/src/FilterModal.tsx
widgets/filters/src/FiltersTable.tsx

System tests build: https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/459/

WDR-13 Added filters list refetch after successful edit

---

app/translations/en.json
test/cypress/integration/widgets/filters_spec.ts
widgets/filters/src/FiltersTable.tsx

I'm not planning system tests execution - I run the updated test locally and it passes.

RD-1123 Changed Type column to boolean System column

---

scripts/readmesConfig.json
widgets/filters/README.md
widgets/filters/src/widget.tsx

I don't see any impact on system tests, so I'm not scheduling a build.

RD-1123 Added README.md for filters widget

---

test/cypress/integration/widgets/topology_spec.js

Topology widget test started in local environment passed.
System tests scheduled: https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/505/

RD-2092 - Fix expected structure of Terraform resources in topology_spec.js

---

app/translations/en.json
widgets/common/src/deploymentsView/header/index.tsx

This change is trivial but I'm submitting it as a separate PR as it's an integration point for all bulk actions related stories.
Screenshot:
Clicked:
I'm not planning system tests execution on the branch.

RD-2079 Added bulk actions button

---

package-lock.json
package.json

This PR fixes audit fails during Nightly Build.
Ticket:  https://cloudifysource.atlassian.net/browse/RD-2267
System tests passed: https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/556/

Rd 2267 UI audits fail because of severity vulnerabilities

---

app/utils/EventBus.ts
widgets/common/src/BlueprintActions.ts
widgets/common/src/DeploymentActions.ts
widgets/common/src/ExecuteDeploymentModal.jsx
widgets/common/src/InputsUtils.jsx
widgets/common/src/UpdateDeploymentModal.jsx
widgets/common/src/deploymentsView/header/DeployOnModal.tsx
widgets/deploymentWizardButtons/src/steps/ConfirmationStep.jsx
widgets/deploymentWizardButtons/src/steps/InputsStep.jsx

Addresses code review comments from #1340 and #1343
Since there are some refactorings impacting broader context I scheduled system tests build: https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/558/

RD-2078 Code review follow-ups

---

app/translations/en.json
app/utils/Manager.js
app/utils/stageUtils.ts
backend/package-lock.json
package-lock.json
test/cypress/integration/widgets/deployments_view_spec.ts
widgets/common/src/DeployBlueprintModal.tsx
widgets/common/src/DeploymentActions.ts
widgets/common/src/DeploymentGroupsActions.ts
widgets/common/src/ExecuteDeploymentModal.jsx
widgets/common/src/ExecutionGroupsActions.ts
widgets/common/src/GenericDeployModal.jsx
widgets/common/src/SearchActions.ts
widgets/common/src/deploymentsView/DeploymentsView.tsx
widgets/common/src/deploymentsView/common.ts
widgets/common/src/deploymentsView/header/DeployOnModal.tsx
widgets/common/src/deploymentsView/header/ExecutionStartedModal.tsx
widgets/common/src/deploymentsView/header/GoToExecutionsPageButton.tsx
widgets/common/src/deploymentsView/header/RunWorkflowModal.tsx
widgets/common/src/deploymentsView/header/common.ts
widgets/common/src/deploymentsView/header/index.tsx

This PR aims to switch UI development to `6.0.0-build` branch.
After merging this PR we all should switch, by that I mean:
1. In already existing PRs - change base branch in our PRs to `6.0.0-build`
2. In new PRs - set base branch to `6.0.0-build`
3. Run our system tests with BRANCH (not STAGE_BRANCH) set to `6.0.0-build` (see RD-2308)
System tests started with the following parameters:
* STAGE_BRANCH = `RD-2306`
* BRANCH = `6.0.0-build`
https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/583/

RD-2306 - Update 6.0.0-build branch with latest changes from the master branch

---

app/translations/en.json
test/cypress/integration/widgets/filters_spec.ts
widgets/common/src/deploymentsView/detailsPane/DrilldownButtons.tsx
widgets/common/src/deploymentsView/header/FilterModal.tsx
widgets/common/src/filters/RulesForm.tsx
widgets/common/src/filters/common.ts
widgets/common/src/filters/inputs/AttributeValueInput.tsx
widgets/common/src/filters/inputs/LabelValueInput.tsx
widgets/common/src/filters/types.ts
widgets/filters/src/FilterModal.tsx

RD-2142 - Add "is_not" filter operator

---

app/components/GettingStartedModal/ModalContent.tsx
app/components/GettingStartedModal/steps/SummaryStep/SummaryStep.tsx

It is cherry-pick from https://github.com/cloudify-cosmo/cloudify-stage/pull/1354 to 6.0.0-build

Rd 2252 the getting started progress bar should be always visible  for 6 0 0 build

---

test/cypress/integration/tenants_spec.js

One more fix related to https://github.com/cloudify-cosmo/cloudify-stage/pull/1377 .
Good news are that the on `6.0.0-build` branch ([Stage-UI-System-Test #636](https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/636/tests)) we have just one failure which is to be fixed by this PR.

RD-2415 Fix Tenants spec

---

app/components/PagesList.tsx
app/styles/style.scss
package-lock.json
package.json
test/jest/components/PagesList.test.tsx

Now user can open page in new tab using sidebar

RD-1825 Fix missing possibility to open page in new tab using sidebar.

---

widgets/filters/src/FiltersTable.tsx

This addresses filters table issue reported in WDR-44.
Regarding the reported dropdown issue there is RD-1575 to address it application wide, so I'm not going to fix this as part of this PR.

WDR-44 Added word breaking rule to filter id column

---

widgets/filter/README.md

Cherry-pick of #1443 to `6.1.0-build`.

RD-1829 Update Resource Filter's README (#1443)

---

jenkins/Jenkinsfile

Cherry-pick of #1448 to `6.1.0-build`

RD-2647 Switch UI development to 6.1

---

test/cypress/integration/widgets/deployments_view_spec.ts
test/cypress/support/commands.ts

A cherry-pick of https://github.com/cloudify-cosmo/cloudify-stage/pull/1451 to master
A single approval is sufficient IMO :slightly_smiling_face:

RD-2633 Allow setting up intercepts right before login

---

jenkins/Jenkinsfile
jenkins/build-pod.yaml

RD-1766 Redesign pipeline, optimize parallelization.

RD-1766 redesign ci workflow stage (#1445)

---

.size-limit
app/translations/en.json
test/cypress/integration/widgets/deployments_view_spec.ts
widgets/common/src/deploymentsView/DeploymentsView.tsx
widgets/common/src/deploymentsView/header/FilterModal.tsx
widgets/common/src/deploymentsView/header/index.tsx
widgets/common/src/deploymentsView/useFilterQuery.ts
widgets/common/src/filters/RulesForm.tsx
widgets/filters/src/FilterModal.tsx

Cherry-pick of #1444 to master

RD-1769 Added support for new or modified filter

---

test/cypress/integration/widgets/executions_spec.ts
widgets/executions/src/ExecutionsTable.tsx
widgets/executions/src/widget.tsx

https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/822/

RD-2332 Add the Deployment display name column to the Executions widget.

---

test/cypress/integration/widgets/deployments_view_spec.ts
test/cypress/support/deployments.ts
widgets/common/src/SearchActions.ts

A cherry-pick of #1438 to `master`. A single approval should be enough.

RD-2516 Use search name in Deployments View

---

.size-limit
app/translations/en.json
test/cypress/integration/widgets/deployments_view_spec.ts
widgets/common/src/DynamicDropdown.tsx
widgets/common/src/deploymentsView/header/filter/FilterModal.tsx
widgets/common/src/deploymentsView/header/filter/SaveButton.tsx
widgets/common/src/deploymentsView/header/filter/common.ts
widgets/common/src/deploymentsView/header/index.tsx

Cherry-pick of #1459 to master

RD-1771 Added support for creating new filter

---

test/cypress/integration/widgets/filters_spec.ts

Please see my comment to RD-2664.

RD-2664 Disabled flaky tests

---

app/translations/en.json
test/cypress/integration/widgets/deployment_actions_spec.ts
test/cypress/integration/widgets/deployments_spec.ts
widgets/common/src/DeploymentActions.ts
widgets/common/src/ExecuteDeploymentModal.tsx
widgets/deploymentActionButtons/src/DeploymentActionButtons.tsx
widgets/deployments/src/ActionsMenus.tsx
widgets/deployments/src/DeploymentsList.tsx
widgets/deployments/src/DeploymentsSegment.tsx
widgets/deployments/src/DeploymentsTable.tsx

Cherry-pick of #1469 into master.

RD-2331 Added deployment display name to workflow execution modal header

---

app/translations/en.json
test/cypress/integration/widgets/blueprint_actions_spec.ts
widgets/blueprintActionButtons/src/BlueprintActionButtons.tsx
widgets/blueprintActionButtons/src/widget.tsx

A cherry-pick of #1466 to master.

RD-2593 Hide "Edit a copy in Composer" button (#1466)

---

app/translations/en.json
test/cypress/integration/widgets/blueprints_spec.ts
widgets/blueprints/src/BlueprintsCatalog.tsx
widgets/blueprints/src/BlueprintsTable.tsx
widgets/blueprints/src/types.ts
widgets/blueprints/src/widget.tsx

Cherry-pick of #1477 to `master`

RD-2593 Hide "Edit in Composer" in Blueprints widget (#1477)

---

app/translations/en.json
test/cypress/integration/widgets/deployment_actions_spec.ts
test/cypress/integration/widgets/deployments_spec.ts
widgets/common/src/DeploymentActionsModals.tsx
widgets/common/src/RemoveDeploymentModal.tsx
widgets/common/src/SetSiteModal.tsx
widgets/common/src/UpdateDeploymentModal.tsx
widgets/common/src/labels/LabelsModal.tsx
widgets/deploymentActionButtons/src/DeploymentActionButtons.tsx
widgets/deployments/src/DeploymentsList.tsx

There are no visual changes - only modals header text changes.
System tests: https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/872/

RD-2330 Added deployment display name to deployment actions modal headers

---

test/cypress/integration/widgets/nodes_spec.ts
widgets/nodes/src/NodesTable.tsx
widgets/nodes/src/widget.tsx

Cherry-pick of  #1479 to master

RD-2335 Added deployment name column to nodes list widget

---

package-lock.json

Cherry-pick of  #1485 to master

RD-2665 Updated prismjs version to fix vulnerability

---

app/utils/Manager.ts
test/jest/utils/Manager.test.ts

changed `$.param` to `stringify` from `queryString` lib and adjust tests.

RD-2694 Remove jQuery usage from Manager.ts file.

---

package-lock.json
package.json

Fixes scrolling to errors in form submission.
Depends on https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1882 (the mutlibranch CI won't pass until that PR is merged)
I will cherry-pick the PR to master once this one is merged.
https://user-images.githubusercontent.com/889383/124486496-f1c17400-ddad-11eb-882a-3be78299400d.mp4
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/890/pipeline
Queued 2021-07-05 16:32 CEST

RD-2690 Upgrade cloudify-ui-components to 2.4.7

---

package-lock.json
package.json

Cherry-pick of https://github.com/cloudify-cosmo/cloudify-stage/pull/1494 to `master`

RD-2690 Upgrade cloudify-ui-components to 2.4.7 (#1494)

---

test/cypress/integration/widgets/plugins_catalog_spec.ts
widgets/common/src/PluginActions.ts
widgets/common/src/PluginIcon.tsx
widgets/pluginsCatalog/src/Actions.ts
widgets/pluginsCatalog/src/PluginsCatalogList.tsx
widgets/pluginsCatalog/src/PluginsCatalogModal.tsx
widgets/pluginsCatalog/src/types.ts
widgets/pluginsCatalog/src/widget.tsx

Cherry-pick of https://github.com/cloudify-cosmo/cloudify-stage/pull/1495 to `master`
Needs #1497 to be merged first

RD-2483 Migrate Plugins Catalog widget to TypeScript (#1495)

---

.size-limit
test/cypress/integration/widgets/plugins_catalog_spec.ts
widgets/pluginsCatalog/src/Actions.ts
widgets/pluginsCatalog/src/PluginsCatalogList.tsx
widgets/pluginsCatalog/src/types.ts
widgets/pluginsCatalog/src/widget.tsx

Cherry-pick of https://github.com/cloudify-cosmo/cloudify-stage/pull/1496 to `master`

RD-2483 Display uploaded plugin version in Plugins Catalog widget

---

app/components/Page.tsx
app/styles/style.scss
app/utils/shared/combineClassNames.ts
test/jest/utils/shared/combineClassNames.test.ts

Cherry-pick of https://github.com/cloudify-cosmo/cloudify-stage/pull/1503 to master

RD-2128 Fix margin for widgets maximized on small screens (#1503)

---

test/cypress/integration/widgets/topology_spec.ts
test/cypress/support/asserts.ts
widgets/topology/src/Topology.tsx

Cherry-pick of https://github.com/cloudify-cosmo/cloudify-stage/pull/1501 to `master`

RD-2747 Fix expanding Terraform nodes in Topology widget (#1501)

---

test/cypress/integration/widgets/deployments_view_spec.ts
widgets/common/src/deploymentsView/DeploymentsView.tsx
widgets/common/src/deploymentsView/styles.scss

Cherry-pick of #1512 to `master`

RD-2769 Fix unbounded resizing of Deployments View panes (#1512)

---

test/cypress/integration/widgets/filters_spec.ts

This PR turns on test disabled within #1468 and contains a cherry pick of #1519 on `6.1.0-build` branch.

RD-2664 Fix selecting label key from dropdown list in filters_spec

---

test/cypress/integration/widgets/topology_spec.ts

Cherry-pick of https://github.com/cloudify-cosmo/cloudify-stage/pull/1526 to `master`

RD-2898 Loosen assertions in topology spec (#1526)

---

app/components/EditWidgetModal.tsx
app/components/shared/DynamicTable.tsx
app/components/shared/index.ts
app/translations/en.json
widgets/blueprints/src/BlueprintsList.tsx
widgets/blueprints/src/types.ts
widgets/blueprints/src/widget.tsx
widgets/common/src/BlueprintUploadActionsMenu.tsx

Added Dynamic Table component to edit array of objects 
Plus button adds new row with empty strings values of all of object fields. 
to use this editor in widget configuration user needs define columns of table and components for each of field in object.
[ ] Add some system tests for this feature.

RD-2922 Add Dynamic Table component.

---

test/cypress/integration/widgets/blueprints_spec.ts

Simply test to check if marketplace modal opens correctly.  Blueprint catalog is tested by `blueprint_catalog_spec.ts` so imho testing the same is redundant.

Add test to check marketplace modal content.

---

app/translations/en.json
widgets/common/src/hooks/useRefreshEvent.ts
widgets/plugins/src/PluginsTable.tsx

- migrated to TS
- migrated to functional component
- externalized strings
- removed lodash usage
Before:
After:
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/1123/
I'll extend https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1919 with an updated widget screenshot.

RD-3014 Changed upload button styling and refactored `PluginsTable` component

---

backend/jest.config.js
backend/package-lock.json
backend/package.json

Upgraded `passport-saml` version to fix security issues reported in audit.
After that upgrade, the following errors were returned by `npm run test:backend`:
```
● /auth endpoint › /saml/callback handles › invalid token
The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/en/configuration#testenvironment-string.
Consider using the "node" test environment.
TypeError: expirationTimer.unref is not a function
15 |     }
16 | 
> 17 |     return new SamlStrategy(
|            ^
18 |         {
19 |             path: '/auth/saml/callback',
20 |             entryPoint: config.app.saml.ssoUrl,
at new CacheProvider (node_modules/passport-saml/src/node-saml/inmemory-cache-provider.ts:52:21)
at SAML.initialize …
```

RD-2977 Upgrade `passport-saml` to fix security audit issues

---

backend/jest.config.js
backend/package-lock.json
backend/package.json

Cherry-pick of #1570 on `6.2.0-build` branch.
N/A
Just a cherry-pick, so not planning any testing.
N/A

RD-2977 Upgrade `passport-saml` to fix security audit issues [6.2]

---

test/cypress/integration/widgets/blueprints_spec.ts

Add additional test cases for check item in blueprint upload menu, Continuation of https://github.com/cloudify-cosmo/cloudify-stage/pull/1569#discussion_r700098862
n/a
* [Build #1193 (03-Sep-2021 11:31:34)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1193/)
n/a

RD-3016 Add additional test cases for check item in blueprint upload menu

---

app/components/GettingStartedModal/ModalHeader.tsx

Even though I ran system tests in https://github.com/cloudify-cosmo/cloudify-stage/pull/1580 I introduced a bug with refactoring committed after starting the tests.
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/1202/ - I only ran the 'getting started' spec, which passed.
N/A

RD-3113 Fix for bug introduced during refactoring

---

backend/jest.config.js
backend/utils.ts

After merging #1575 it is required to update coverage reference commit. It should point to a commit in the `master`, so it was not possible to do it as part of #1575.
N/A
N/A
N/A

RD-1291 Updated coverage reference commit

---

app/translations/en.json
widgets/common/src/LastExecutionStatusIcon.tsx

Added default message for error detail
No change in UI look
N/A
N/A

RD-3095 Added default message for error detail

---

package.json

As discussed during UI weekly meeting, I'm adding a simple note to make it clear what is the difference between dev and optional dependencies in our packages.
N/A
N/A
N/A

RD-3154 Clarify the difference between dev and optional dependencies in `package.json`

---

backend/package-lock.json
backend/package.json

Bumped cloudify-ui-common version to use fixed `getLogger` implementation.
N/A
N/A
N/A

RD-2917 Bumped cloudify-ui-common version

---

app/translations/en.json
test/cypress/integration/widgets/deployments_view_spec.ts
widgets/common/src/DeployBlueprintModal.tsx
widgets/common/src/GenericDeployModal.tsx
widgets/common/src/deploymentsView/header/DeployOnModal.tsx
widgets/deploymentsView/README.md

Cherry-pick of #1600 .
See #1600 .
[Stage-UI-System-Test/1262](https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1262/pipeline) (14.09.2021, 12:54:15 CEST) - PASSED
See #1600

RD-3110 Enhance Deploy On modal to allow providing a suffix for new deployments [6.2]

---

.size-limit
app/translations/en.json
widgets/blueprintCatalog/src/RepositoryTable.tsx
widgets/common/src/blueprintMarketplace/BlueprintMarketplaceModal.tsx

Cherry-pick of #1598 .
See #1598 .
[Stage-UI-System-Test/1261](https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1261/pipeline) (14.09.2021, 12:53:11 CEST) - PASSED
See #1598

RD-3140 Update Blueprint Marketplace modal to use Table view by default [6.2]

---

app/translations/en.json
widgets/common/src/LastExecutionStatusIcon.tsx

RD-3095 Cherry-pick to 6.2

---

app/components/GettingStartedModal/GettingStartedModal.tsx
app/utils/hooks/index.ts
app/utils/hooks/useOpenProp.ts

Cherry-pick of #1609 .
See #1609 .
See #1609 .
N/A

RD-3174 Reset state of Getting Started modal on open [6.2]

---

app/components/GettingStartedModal/GettingStartedModal.tsx
app/translations/en.json
test/cypress/integration/getting_started_spec.ts

Added 'Getting started' modal close confirmation dialog.
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/1282/ - only 'getting started' spec
N/A

RD-3175 Added modal close confirmation dialog

---

app/components/GettingStartedModal/GettingStartedModal.tsx

Clear step errors when going to previous step
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/1285/ - only 'getting started' spec
N/A

RD-3181 Clear step errors when going to previous step

---

widgets/blueprintCatalog/README.md
widgets/blueprints/README.md

Cherry pick of 2edafb93bde00891256d32333c5b7fe65cc1b789

RD-3069 Update documentation for Blueprint flow changes (#1613)

---

app/components/GettingStartedModal/GettingStartedModal.tsx
app/translations/en.json
test/cypress/integration/getting_started_spec.ts

RD-3181 and RD-3175 cherry-picks to 6.2

---

app/translations/en.json
widgets/blueprints/src/widget.tsx
widgets/common/src/blueprintMarketplace/blueprintMarketplaceTabsConfig.ts

Cherry-pick of #1616 .
See #1616 .
See #1616 . Not planning to run more tests.
N/A

RD-3179 Update tabs in Blueprint Marketplace modal [6.2]

---

backend/package-lock.json
backend/package.json

Dependency update due to `npm audit` failure.
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/1392/
N/A

RD-3370 Dependency update

---

package-lock.json
package.json

https://github.com/cloudify-cosmo/cloudify-blueprint-topology/pull/170
> Starting position of tooltip need to be set to 0 and 0 to prevent unexpected expansion of parent container.
[Build #1394 (Oct 20, 2021, 11:51:09 AM)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1394/)
N/A

RD-2029 Upgrade cloudify-blueprint-topology to 2.5.3

---

templates/page-groups/deployments.json
templates/page-groups/resources.json
templates/page-groups/systemSetup.json
templates/pages/adminDash.json
templates/pages/agents.json
templates/pages/blueprints.json
templates/pages/environments.json
templates/pages/executions.json
templates/pages/filters.json
templates/pages/groups.json
templates/pages/health.json
templates/pages/logs.json
templates/pages/plugins.json
templates/pages/secrets.json
templates/pages/services.json
templates/pages/sites.json
templates/pages/snapshots.json
templates/pages/tenants.json
templates/pages/users.json

Added icons for pages and page groups used by built-in templates.
N/A
Will be covered in separate ticket.

RD-3419 Added icons for pages and page groups used by built-in templates

---

test/cypress/integration/flows/user_spec.ts

Fixed system test that's failing after #1657 was merged.
N/A
Verified locally
N/A

RD-3419 Fixed system test

---

.size-limit
app/actions/templateManagement/pageGroups.ts
app/actions/templateManagement/pages.ts
app/components/IconSelection.tsx
app/components/sidebar/PagesList.tsx
app/components/templateManagement/TemplateManagement.tsx
app/components/templateManagement/pageGroups/PageGroupModal.tsx
app/components/templateManagement/pageGroups/PageGroups.tsx
app/components/templateManagement/pages/CreatePageModal.tsx
app/components/templateManagement/pages/PageManagement.tsx
app/components/templateManagement/pages/Pages.tsx
app/components/templateManagement/templates/CreateTemplateModal.tsx
app/reducers/templatesReducer.ts
app/translations/en.json
test/cypress/integration/templateManagement/page_groups_spec.ts
test/cypress/integration/templateManagement/pages_edit_spec.ts
test/cypress/integration/templateManagement/pages_spec.ts

Added icons support in template management.
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/1446/
Will be updated in separate ticket

RD-3242 Added icons support in template management

---

widgets/common/src/InputsUtils.tsx

A link to the ticket in Jira: https://cloudifysource.atlassian.net/browse/RD-3330
**The bug is:** Cannot add negative numbers.
**Steps to reproduce:** type "--", then remove it, then type a number, remove it, then try to type a negative number. 
**Expected result:** negative number is in the input.
**Actual result:** sometimes empty input and sometimes a number without the minus sign.
I added a code that checks that the input value is not NaN. 
In the following video I show "before fix" and "after fix". In "before fix" when I type "-" after numbers it deletes everything.  And negative numbers cannot be added. But, after the fix, "-" can be added without problems.
https://user-images.githubusercontent.com/17104212/141311538-780bf5ad-d213-4016-b467-6f7b14751a13.mov
System tests: …

RD-3330 Fix negative number in an input

---

app/components/sidebar/HelpMenu.tsx
app/components/sidebar/PagesList.tsx
app/components/sidebar/SideBar.tsx
app/components/sidebar/SystemMenu.tsx
app/components/sidebar/UserMenu.tsx
test/cypress/components/app/sidebar/Help_spec.tsx
test/cypress/components/app/sidebar/PagesList_spec.tsx
test/cypress/components/app/sidebar/SideBar_spec.tsx
test/cypress/components/app/sidebar/UserMenu_spec.tsx
test/cypress/support/editMode.ts

Added automatic sidebar groups collapsing
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/1577/
Will be covered in separate ticket

RD-3442 Added automatic sidebar groups collapsing

---

templates/pages/adminDash.json

Changes bringed with this PR will modify the layout of the dashboard, so that the `execution` and `executionsStatus`  widgets would fill all the available horizontal space   
Additionally, some amount of the comments (related to the creator of the files) has been removed, due to the [ongoing refactors](https://cloudifysource.atlassian.net/wiki/spaces/RD/pages/2148073473/Ongoing+Refactors+in+Cloudify+UI#Migrating-files-to-TypeScript)
Locally I've run all tests related to the modified widget (the only test related to them was stored in `executions_spec.ts` file) and additionally I've run `npm run test:frontend` command, which has passed succesfully
Moreover, I've run the [System Tests](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1589)

RD-3584 Modified the layout of the dashboard

---

test/cypress/integration/widgets/user_defined_widgets_spec.ts

Fix for system test that started to fail on nightly
N/A
https://jenkins.cloudify.co/job/Stage-UI-System-Test/1611/ - `user_defined_widgets_spec` only
N/A

RD-3691 System test fix

---

backend/templates/terraform/blueprint.ejs
backend/test/routes/fixtures/terraform/1_blueprint.yaml
backend/test/routes/fixtures/terraform/2_blueprint.yaml

Updated blueprint template according to Michael's comments.
N/A
N/A
N/A

RD-3207 Updated blueprint template

---

conf/README.md

Spotted missing documentation update for RD-3482. Added a line about recently created white-labelling parameter.
N/A
N/A
See Description section.

RD-3482 Update README.md for configuration files

---

app/components/sidebar/SideBarItem.tsx
app/components/sidebar/SystemMenu.tsx

Fixed page menu items display when dragging in edit mode
N/A
N/A
N/A

RD-3700 Fixed page menu items display when dragging in edit mode

---

app/translations/en.json
backend/routes/Terraform.ts
backend/test/routes/Terraform.test.ts
test/cypress/integration/widgets/blueprints_spec.ts
test/cypress/support/commands.ts
widgets/blueprints/src/TerraformModal.tsx

Added more validations to Terraform modal
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/1679/
Should be updated once feature implementation is complete.

RD-3660 Added more validations to Terraform modal

---

scripts/updateReadmes.js
widgets/filters/README.md

This PR brings changes related to styling the tables inside widgets documentations.
Changes consists of adding proper class names to the `table` element inside mentioned documentations.
N/A
N/A

RD-2457: Styled tables inside the widgets documentations

---

test/cypress/integration/widgets/blueprints_spec.ts

Looks like introducing `Form.Group` broke the spec
N/A
Minor change - verified locally
N/A

RD-3916 Fixed cy test

---

widgets/blueprints/README.md

Documentation has been synchronized with the [recent update](https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2066/files)
N/A
N/A
N/A

RD-3953 Synchronized documentation

---

test/cypress/integration/user_menu_spec.ts

Changes consists of delaying the response for one of the requests, so that we could be certain that cypress will have a necessary time for detecting the `<Loader />` component on the screen.
N/A
I've run the cypress test file, related to the jira issue, multiple times to see if the issue is gone for good 🚀 
And it seems like 250ms delay for the response is creating a safe space for the cypress to confirm that the `<Loader />` is visible on the screen!
[System tests](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1792) has been executed 
(All tests are passing, except 2 which are failing due to the problems detected on the master branch)
N/A

RD-3974: Added delay to the response of the request

---

package-lock.json
package.json

Changes consists of upgrading the @cypress-code-coverate package which was found vulnerable
[Link to the details](https://app.snyk.io/org/cloudify-manager/project/42f77e91-9e07-43d5-8ef9-8367ae5f163c#issue-SNYK-JS-SHELLQUOTE-1766506) provided by snyk
N/A
[System tests](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1795/) has been executed.
(All tests are passing, except 2 which are failing due to the problems detected on the master branch)
N/A

RD-3825: Updated @cypress/code-coverage package to version 3.9.12

---

test/cypress/integration/widgets/blueprints_spec.ts
widgets/blueprints/src/TerraformModal.tsx

Fixed terraform form validation
N/A
Verified blueprints spec locally
N/A

RD-3945 Fixed terraform form validation

---

app/translations/en.json
templates/pages/adminDash.json
templates/pages/blueprints.json
test/cypress/integration/widgets/blueprints_spec.ts

Changes consists of modifying a few labels, simple as that 😁 
I'm attaching the screenshots after the changes, to confirm, that all of the places (pointed out in the ticket) has been addressed
As the changes was applied only to the labels (and I've updated the tests, related to those labels, accordingly) I did not execute System Tests
Documentation will be updated while progressing on [this task](https://cloudifysource.atlassian.net/browse/RD-3969)

RD-3980: Updated translation labels

---

package-lock.json
test/cypress/components/app/sidebar/TenantSelection_spec.tsx

Added intercepting of the tenants into the tests logic, as it wasn't implemented before
N/A
As the changes are only related to the `TenantSelection_spec.tsx`, I've locally executed `npm run cy:open-ct` command and successfully run (multiple times) the `TenantSelection_spec.txt` test scenarios
N/A

RD-2866: Fixed tests related to the TenantSelection component

---

widgets/common/src/deployModal/DeployModalActions.tsx

I fixed [RD-4047 ticket]( https://cloudifysource.atlassian.net/jira/software/projects/RD/boards/56?assignee=616d361525f3130070320527&selectedIssue=RD-4047) by adding `value` attribute to the drop-down.
https://user-images.githubusercontent.com/17104212/150750964-b73646ab-dd24-4df9-a433-83df5a8af083.mov
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1877/pipeline
N/A

RD-4047 Fix deploy drop-down selection

---

test/cypress/components/app/sidebar/TenantSelection_spec.tsx
test/cypress/integration/widgets/blueprints_spec.ts
test/cypress/support/executions.ts
test/cypress/support/resource_commons.ts
widgets/blueprints/src/TerraformModal.tsx

Changes consists of modifying resourceLocation regexp, so that it may cover the initial slash of the resource path.
N/A
I've executed [System tests](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1887)
N/A

RD-3979: Modified resourceLocation regexp

---

app/translations/en.json
templates/pages/adminDash.json
templates/pages/blueprints.json
test/cypress/integration/widgets/blueprint_catalog_spec.ts
test/cypress/integration/widgets/blueprints_spec.ts

Similar change as in #1772 , but only blueprint examples change, no need to update widget help description on `master` branch.
N/A
Tested within #1772 .
N/A

RD-392 Switch blueprint examples to 6.3

---

backend/templates/terraform/blueprint.ejs
backend/test/routes/fixtures/terraform/1_blueprint.yaml
backend/test/routes/fixtures/terraform/2_blueprint.yaml

Changes consisting of updating links inside the generated blueprints, to point out to the version `6.3`
N/A
I've executed [System Tests](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1919), but from the yesterday the seems to no be able to be executed 😢 
N/A

RD-4029: Updated blueprint imports

---

backend/app.ts
backend/routes/Auth.ts
backend/routes/BlueprintAdditions.ts

Cherry-pick of #1773 .
See #1773 
See #1773 
See #1773

RD-4086 Fix displaying Blueprints and Plugins logos [6.3]

---

widgets/blueprints/README.md

Changes are consisting of synchronizing the documentation with the [docs.cloudify.org](https://github.com/cloudify-cosmo/docs.getcloudify.org) repo
N/A
N/A
N/A

RD-3969: Synchronised documentation

---

backend/templates/terraform/blueprint.ejs
backend/test/routes/fixtures/terraform/1_blueprint.yaml
backend/test/routes/fixtures/terraform/2_blueprint.yaml

Cherry-pick of #1774 .
See #1774
See #1774
See #1774

RD-4029 - cherry pick

---

widgets/blueprints/README.md

RD-3969: Synchronised documentation with the 6.3 build

---

app/translations/en.json
test/cypress/fixtures/widgets/splitViewWidget.tsx
test/cypress/integration/getting_started_spec.ts
test/cypress/integration/widgets/plugins_catalog_spec.ts
test/cypress/support/commands.ts

Cherry pick of #1781
See #1781
See #1781
See #1781

RD-4090 Update plugins catalog link to the latest version [6.3]

---

widgets/topology/src/Topology.tsx

Fixed terraform topology rendering when dependency node is missing
N/A
This fix is transparent for any case that might by used as part of any test, so no need to run tests.
N/A

RD-4095 Fixed terraform topology rendering when dependency node is missing

---

.size-limit
widgets/blueprintActionButtons/README.md
widgets/blueprintNum/README.md
widgets/blueprints/README.md
widgets/buttonLink/README.md
widgets/deploymentNum/README.md
widgets/deploymentsView/README.md
widgets/executionNum/README.md
widgets/executions/README.md
widgets/nodes/README.md
widgets/pluginsNum/README.md
widgets/sitesMap/README.md

This PR is to synchronize widgets help description with recent changes in user documentation - https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2079.
N/A
N/A
N/A

RD-2504 Update widgets help description

---

.size-limit
widgets/blueprintActionButtons/README.md
widgets/blueprintNum/README.md
widgets/blueprints/README.md
widgets/buttonLink/README.md
widgets/deploymentNum/README.md
widgets/deploymentsView/README.md
widgets/executionNum/README.md
widgets/executions/README.md
widgets/nodes/README.md
widgets/pluginsNum/README.md
widgets/sitesMap/README.md

Cherry pick of #1790 
N/A
N/A
N/A

RD-2504 Update widgets help description [6.3]

---

app/utils/shared/ExecutionUtils.ts

Cherry pick of #1787 .
N/A
See #1787 
See #1787

RD-4097 Use update workflow ID for deployment updates [6.3]

---

widgets/topology/src/Topology.tsx

Fixed terraform topology rendering when dependency node is missing.
N/A
N/A
N/A

RD-4095 Fixed terraform topology rendering when dependency node is missing - #1788 merge to 6.3

---

test/cypress/integration/widgets/blueprints_spec.ts

Changes consists of removing the upload of the Terraform plugin, because it's being already covered.
N/A
I've executed [System tests](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1948) only related to the test file, which was related to the issue mentioned in the [jira ticket](https://cloudifysource.atlassian.net/browse/RD-4098).
N/A

RD-4098: Removed unnecessary plugin upload

---

test/cypress/integration/widgets/blueprints_spec.ts
test/cypress/integration/widgets/topology_spec.ts
test/cypress/support/commands.ts
test/cypress/support/plugins.ts

Changes consists of removing the `uploadPluginFromCatalog` function across the test files.
N/A
[System tests](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1965) has been executed
N/A

RD-4104: Removed uploadPluginFromCatalog function from the test files

---

backend/app.ts
test/cypress/integration/widgets/sites_map_spec.ts

Made maps route unauthenticated, improved cy test
N/A
Verified system test locally
N/A

RD-4186 Made maps route unauthenticated, improved cy test

---

backend/app.ts
test/cypress/integration/widgets/sites_map_spec.ts

RD-4186 Made maps route unauthenticated, improved cy test (#1810)

---

devServer.ts
package-lock.json
package.json

Reverts cloudify-cosmo/cloudify-stage#1803

Revert "RD-2946 Add hot reloading"

---

test/jest/setup.ts
test/jest/widgets/blueprints/TerraformModal.test.ts
widgets/blueprints/src/TerraformModal.tsx

Added test for getResourceLocation function
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/2048/ - blueprints widget spec only
N/A

RD-4102 Added test for getResourceLocation function

---

backend/package-lock.json
package-lock.json

Cherry-picked solution from #1819 and #1816 PRs to create single solution.
N/A
[Stage-UI-System-Test/2114](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2114/) - PASSED (except Filter widget spec, which is reported as RD-4286)
N/A

RD-4297 Fix security audit issues coming from `ajv` package

---

app/components/GettingStartedModal/schema/cloudSetup.schema.json

Cherry-pick #1842 onto `6.3.1-build` branch.
See #1842 
See #1842 
See #1842

RD-4320 Fix typo in vSphere Secrets dialog in Getting Started modal [6.3.1]

---

app/translations/en.json

Updated EULA link
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/2128/ - community spec only
N/A

RD-4315 Updated EULA link

---

app/translations/en.json

Cherry-pick of #1844.
See #1844.
See #1844.
See #1844.

RD-4315 Update EULA link in Contact Details modal [6.3.1]

---

templates/pages/blueprints-community.json

Changes were made only to the configuration file, which was related to the comunity version.
There was one missing property, which I've added 🎉 
N/A
N/A
N/A

RD-4351: Added blueprints icon for the community version sidebar

---

templates/pages/blueprints-community.json

To see more details, please see [the original PR](https://github.com/cloudify-cosmo/cloudify-stage/pull/1850)
Please see [the original PR](https://github.com/cloudify-cosmo/cloudify-stage/pull/1850) for more details
Please see [the original PR](https://github.com/cloudify-cosmo/cloudify-stage/pull/1850) for more details
Please see [the original PR](https://github.com/cloudify-cosmo/cloudify-stage/pull/1850) for more details

RD-4351: Synchronizing the 6.3.1-build version with the changes introduced by the RD-4351 changes

---

app/components/ContactDetailsModal/ContactDetailsModalContent/formFields.ts
test/cypress/integration/community_spec.ts

Adding functionality introduced inside #1853 to the **6.3.1** version
For more details about the implemented functionality, please see #1853 
N/A
Please see #1853 for more details
N/A

RD-4367: Cherry picking functionality from RD-4367 to 6.3.1

---

app/components/ContactDetailsModal/ContactDetailsModalContent/CheckboxLabel.tsx
app/components/ContactDetailsModal/ContactDetailsModalContent/ContactDetailsModalContent.tsx
app/components/ContactDetailsModal/ContactDetailsModalContent/formFields.ts
app/translations/en.json
test/cypress/integration/community_spec.ts

Refactoring - reused EULA link already defined in `en.json`.
N/A
Extended community spec - added `href` check.
I verified the whole community spec locally. I'm not planning full system tests execution.
N/A

RD-4368 Reused EULA link

---

package-lock.json

Changes consists of relocking some of the packages, which were listed as prone to the [ansi-regex](https://app.snyk.io/org/cloudify-manager/project/42f77e91-9e07-43d5-8ef9-8367ae5f163c#issue-SNYK-JS-ANSIREGEX-1583908) vulnerability
N/A
[System tests](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2165) has been executed.
2 tests scenarios has failed, but those failures are known for appearing from time to time [at our nightly](https://cloudifysource.atlassian.net/wiki/spaces/RD/pages/2382528743/Tracking+2022-01-03+-+2022-03-31).
There is event [dedicated ticket](https://cloudifysource.atlassian.net/browse/RD-3672?src=confmacro) which is dedicated for resolving this exact issue.
Because of that, I think it;s fair to assume that the changes introduced by this …

RD-3825: Resolved most of packages prone to ansi-regex vulnerability

---

test/jest/widgets/common/InputUtils.test.tsx
widgets/common/src/InputsUtils.tsx

https://cloudifysource.atlassian.net/browse/RD-4253
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2198)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/2198/)
N/A

RD-4253: Display Form.TextArea on textarea type + refactoring

---

backend/package-lock.json
backend/package.json

See https://github.com/cloudify-cosmo/cloudify-ui-common/pull/111
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2228)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2228/) (only Edit Mode spec failing, seems like known issue)
N/A

RD-4450 Update version of `cloudify-ui-common` package in backend

---

package-lock.json

Fixed audit failure by updating `lodash-es` version
N/A
N/A
N/A

RD-4454 Fix audit failure

---

.size-limit
package-lock.json
package.json

Updated cloudify-ui-common to use proper getAdminToken cy command implementation.
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/2249/
N/A

RD-4492 Update cloudify-ui-common to use proper getAdminToken cy command implementation

---

app/components/ContactDetailsModal/ContactDetailsModalContent/ContactDetailsModalContent.tsx
app/components/EditWidgetModal.tsx
app/components/shared/DynamicTable.tsx
app/utils/StageAPI.ts
package-lock.json
package.json
widgets/blueprints/src/TerraformModal.tsx
widgets/blueprints/src/TerraformVariableValueInput.tsx
widgets/common/src/deployModal/GenericDeployModal.tsx
widgets/common/src/filters/FilterIdDropdown.tsx

https://cloudifysource.atlassian.net/browse/RD-2792 (point 2)
The PR contains adjustment for typing related to GenericField component typescript migration. It also provides a refactoring in a few places.
https://jenkins.cloudify.co/job/Stage-UI-System-Test/2173/ [passed]
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2253)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/2253/)
Tests fail due to two known issues present in the master as well.
AFAIK there is nothing to update except of the components library version: https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2129

RD-2792: StageAPI - making type field ENUM type

---

widgets/common/src/InputsUtils.tsx

https://cloudifysource.atlassian.net/browse/RD-4114
It's a simple fix for lacking requirement reported by Ilan. Instead of displaying id we display display_name when the fields are different.
N/A
N/A

RD-4114 Show display_name instead of id only (deployment_id input and workflow parameter improvement)

---

test/cypress/integration/widgets/deployment_button_spec.ts

RD-4114
Fix for the test failing during our system tests you ask about: @qooban . I assume here that there are no other blueprints or deployments with given prefix.
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2307)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/2307/)

RD-4114: Tests deployment_id, blueprint_id input fields and worflow parameters

---

jenkins/Jenkinsfile

The PR is to provide the pipeline with the bug fix for wrong "empty" file name of the created package. 
https://cloudifysource.atlassian.net/browse/RD-273
N/A
N/A
N/A

Providing the bug fix for the RD-273

---

test/README.md
widgets/common/src/inputs/utils/getInputField.tsx

Small fix for deployment_id field. In some cases, when the display_name was undefined the options had content like undefined (deplyment_id)
Also a few typo correction included.
Screenshot after fix.
N/A - tested locally
N/A

RD-4114: fixed displaying 'undefined' (deployment_id)

---

test/cypress/integration/widgets/blueprints_spec.ts
widgets/common/src/terraformModal/TerraformModal.tsx

RD-3981
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2549)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/2549/) -> Single test
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2550)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/2550/)
N/A

RD-3981: Terraform Module - authentication, auto focus when required

---

.nycrc

RD-4288
Based on Nightly build result. https://jenkins.cloudify.co/job/Stage-UI-System-Test/2563/Cypress_20coverage/
N/A
N/A

RD-4288: Coverage threshold up

---

app/translations/en.json
widgets/common/src/inputs/InputField.tsx
widgets/common/src/inputs/fields/NodeInstanceInputField.tsx
widgets/common/src/inputs/fields/NodeTypeInputField.tsx
widgets/common/src/inputs/fields/ScaleGroupInputField.tsx
widgets/common/src/inputs/fields/ScalingGroupInputField.tsx

RD-4172, RD-4180, RD-4165
Tests would be provided in the separated PR.
N/A
Tested manually.
N/A

RD-4172, RD-4180, RD-4165: Workflow parameters - node_type, node_instance, scaling_group

---

app/actions/auth.ts
app/actions/managers.ts
app/actions/userApp.ts
app/components/AboutModal.tsx
app/components/AuthRoutes.tsx
app/components/ErrorPage.tsx
app/components/GettingStartedModal/GettingStartedModal.tsx
app/components/Home.tsx
app/components/LicenseLabel.tsx
app/components/LinkToLogin.tsx
app/components/LogoPage.tsx
app/components/NotFound.tsx
app/components/Routes.tsx
app/components/banner/Banner.tsx
app/components/layout/Layout.tsx
app/components/sidebar/SideBarHeader.tsx
app/components/sidebar/UserMenu.tsx
app/containers/LicensePage.ts
app/containers/maintenance/MaintenanceModePageMessage.ts
app/utils/Interceptor.ts
app/utils/consts.ts
app/utils/shared/UrlUtils.ts
test/cypress/integration/getting_started_spec.ts
test/jest/components/Banner.test.tsx

Changes consists of modyfying the methods executed on canceling or completing the `GettingStartedModal` process.
Additionally, regarding the discussion on `UI Weekly`, I've created a property (inside `app/utils/consts.ts`) which would be responsible for storing paths to a different application urls, to which we might need to navigate the users 🎉 
I didn't migrated all of the paths used in our application.
I've just put those on which I was working with, so that we might fill up this object while working with another path redirections functionality.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2588)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2588/)
N/A

RD-4527: Modify GettingStartedModal redirections

---

widgets/tokens/src/TokensTableHeader/CreatedToken.tsx

Changes consists of passing to the `<CopyToClipboardButton />` component always a token value, not the displayed token value (which may have asterisks)
N/A
I've checked locally if the modification is working as expected.
As no tests cenario was related to the modified functionality, I didn't execute the System Tests.
N/A

RD-4423: Added ability to always copy the token value

---

test/cypress/integration/widgets/deployments_spec.ts
widgets/deployments/src/widget.tsx

Simplified condition used for displaying the `ShowFirstUserJourneyButtons` component.
Now the component should be displayed if any deployment is being returned from the backend.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2593)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2593/)
[PR](https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2182) for the documentation update has been created.
The sychronization should take place as a part of this PR.

RD-4651: Simplified condition for displaying the ShowFirstUserJourneyButtons component

---

widgets/deployments/README.md

Changes consists of synchronizing documentation, which was updated within [this PR](https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2182)
N/A
N/A
N/A

RD-4651: Synchronized deployments widget documentation

---

widgets/common/src/inputs/InputField.tsx
widgets/common/src/inputs/fields/NodeIdInputField.tsx
widgets/common/src/inputs/fields/ValueListInputField.tsx
widgets/common/src/inputs/fields/types.ts
widgets/common/src/inputs/types.ts

RD-4223, RD-4240, RD-4230, RD-4216
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2618)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/2618/)
The tests would be provided as a separated PR. (or PR to this PR if we wouldn't manage to merge it before)

RD-4223, RD-4240, RD-4230, RD-4216: Input parameters, workflow parameters, list type

---

widgets/common/src/terraformModal/TerraformModal.tsx

Changes consists of providing a `type="password"` attribute to the one of the input fields.
N/A
N/A

RD-4824: Provided password type attribute to the url authentication field

---

widgets/common/src/inputs/InputField.tsx

RD-4907
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2641)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/2641/)

RD-4907: Fixing the logic behind choosing the input type

---

widgets/executions/src/backend.ts
widgets/executions/src/tasksGraph/ExecutionWorkflowGraph.tsx

Show tasks graph even when its name does not match workflow name.
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/2863/ - none of the failures seem to be related to the changes in the PR, so I consider it a pass
N/A

RD-4327 Show tasks graph even when its name does not match workflow name

---

test/cypress/integration/widgets/deployment_button_spec.ts

Changes consists of reordering assertion checks, so that the URL would be checked after making sure that we've been redirected to the proper page (by default url check is being made synchronously, without any sort of timeout)
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2885)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2885/)
N/A

RD-5090: Delayed check for the url after having certainty about page redirection

---

test/cypress/integration/widgets/deployments_spec.ts
widgets/common/src/executions/LatestExecutionStatusIcon.tsx
widgets/common/src/executions/index.ts
widgets/deployments/src/DeploymentsSegment.tsx
widgets/deployments/src/DeploymentsTable.tsx
widgets/executions/src/tasksGraph/ExecutionWorkflowGraph.tsx
widgets/executions/src/widget.tsx
widgets/managers/src/ManagersTable.tsx

Renamed `lastExecution` code occurrences
N/A
Refactoring - checking CI build status only
N/A

RD-1836 Rename `lastExecution` code occurrences

---

app/components/shared/IdPopup.tsx

Jira ticket: https://cloudifysource.atlassian.net/browse/RD-1255
Before fix:
After fix:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/2923/pipeline
N/A

RD-1255 Solve uneven whitespace in ID popup

---

widgets/common/src/terraformModal/TerraformModal.tsx

Small fix regarding Michael comment at the ticket: RD-4405
N/A
N/A

RD-4405: filling inputs and outputs based on data from terraform file

---

test/cypress/integration/widgets/blueprints_spec.ts

Single `blueprint_spec` test:
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2960)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/2960/)
All tests:
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2961)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/2961/)

RD-5226: Fixed test - selecting source module optional

---

test/cypress/integration/flows/user_spec.ts

Kill running executions before deleting deployments
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/3000/
N/A

RD-5281 Kill running executions before deleting deployments

---

test/cypress/integration/widgets/blueprint_catalog_spec.ts

RD-3666: Typo fix in test file

---

jenkins/Jenkinsfile

The changes made for bypass the Google public certificate validation.
The issue could be bypass in two ways, first is to wait on the google to let them update the certifcates... second is to add
the google repo as trusted. The second option is implemented in this PR.
N/A
- [ x] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [x ] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [ x] I added proper labels to this PR.
N/A
N/A

RD-5295 - Stage multibranch build won't start tests due to `apt update` failure

---

templates/pages/blueprintMarketplace.json

Jira ticket: https://cloudifysource.atlassian.net/browse/RD-5178
https://user-images.githubusercontent.com/17104212/177109643-0d5cf3c1-f773-47c1-8a16-4159fd3ce2a6.mov
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3035/pipeline
TODO: check if an update needed

RD-5178 Avoid two scrollbars in blueprints catalog

---

widgets/userGroups/src/UserGroupsTable.tsx

RD-5104
- fix fetching issue by removing `name="role"` in UserGroupManagement (similiar to UserManagment widget)
n/a
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3059)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3059/)
n/a

RD-5104 fix fetching error in UserGroupsTable

---

widgets/tokens/README.md

Tokens widget documentation sync after merging https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2245.
Forgot to do that in #2059 .
N/A
N/A
This PR is about documentation 🙂

RD-4469 Update Tokens widget documentation

---

app/translations/en.json
test/cypress/integration/widgets/events_spec.ts
widgets/events/src/EventsTable.tsx
widgets/events/src/widget.tsx

Part 1 of RD-5205
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3116/pipeline
https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2246

RD-5205 part 1: make headers consistent in events widget

---

widgets/common/src/inputs/fields/ValueListInputField.tsx

Changes consists of adjusting [ValueListInputField option values](https://github.com/cloudify-cosmo/cloudify-stage/blob/0ae42173b5ecedb69e74539066c8a6275efc3532/widgets/common/src/inputs/fields/ValueListInputField.tsx#L14-L18), so that number passed as a `string` would be treated as a `string` (later it was parsed as a numeric value)
Additionally, there was also an issue related to not displaying default value of the `ValueListInputField` dropdown.
It also have been corrected 🎸 
https://user-images.githubusercontent.com/89005877/178958742-d72736c1-5a05-48c4-99bd-284d0f34ce16.mp4
https://user-images.githubusercontent.com/89005877/178959292-52166809-f30f-4950-bd36-f30c188635ba.mp4
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3124)](https://jenk …

RD-4954: Fixed parsing stringified numeric values

---

widgets/deployments/src/DeploymentsSegment.tsx

Issue seems to be related to some kind of change from the deployments endpoint.
It looks like now `lastExecution` field may be `null` when removing a selected deployment.
Issue comes from the fact that a few functions are trying to reference properties of `lastExecution` - which results in getting an error
N/A
As [the issue](https://cloudifysource.atlassian.net/browse/RD-5338) is happening on our System Tests from time to time, I've executed System Tests multiple times to have a bigger certainty that the issue has been indeed fixed 🎸 
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3136)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3136/)
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI- …

RD-5338: Rendering ExecutionProgress only when a required data is accessible

---

app/translations/en.json
test/cypress/integration/widgets/agents_spec.ts
widgets/agents/src/AgentsTable.tsx
widgets/agents/src/types.tsx
widgets/agents/src/widget.tsx

part 2 of RD-5205. the order of the PRs doesn't matter.
Latest:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3128/pipeline
I started `agents_spec` in this branch in Jenkins: https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3123/pipeline
initial, failed because of Jenkins issues:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3117/pipeline
https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2247

RD-5205 part 2: make headers consistent in  agents widget

---

app/components/shared/cluster/ClusterServicesList.tsx
app/translations/en.json
test/cypress/integration/widgets/deployments_view_spec.ts
widgets/blueprints/src/BlueprintsTable.tsx
widgets/common/src/deploymentsView/detailsPane/pageLayout.json

part 4 of RD-5205, order doesn't matter
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3134/pipeline
- There is no need to update Blueprints Page because the screenshot is with catalog view.
TODO: update services page: https://docs.cloudify.co/latest/working_with/console/pages/services-page/

RD-5205 part 4: make headers consistent in other tables

---

widgets/agents/README.md
widgets/events/README.md

To align with the PR in docs repo: https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2250
N/A
N/A
N/A

RD-5382 Part 5: update docs

---

widgets/deploymentsView/README.md

This PR is only about Deployments View widget documentation sync.
Ref. https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2256
N/A
N/A
N/A

RD-5191 Update Deployments View widget documentation

---

templates/pages/services.json

Jira ticket: https://cloudifysource.atlassian.net/browse/RD-5250
Latest:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3207/pipeline
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3203/pipeline
N/A

RD-5250 Add subservices to the list in services page

---

backend/package-lock.json
backend/package.json
package-lock.json
package.json

Bumping `cloudify-ui-common` package to v7.3.1 to fix security vulnerability (SQL Injection) described in RD-5435.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3209)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3209/)
N/A

RD-5435 Bump `cloudify-ui-common` package to v7.3.1

---

widgets/events/src/widget.tsx

Issue is coming from #2078, where some refactor related to variable naming has been made without adjusting all references to those variables.
This PR is adjusting mentioned references, so that they'll point out to the existing variables 🎉 
After merging this PR, I'll create an additional one with cherrypick for the `6.4.0-build` branch 💪 
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3230)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3230/)
(Complete System Tests execution - without specifying test scenario 🎸  )
N/A

RD-5452: Referenced existing variable

---

widgets/common/src/deploymentsView/header/filter/FilterModal.tsx
widgets/common/src/deploymentsView/header/index.tsx

Cherry-pick of #2091 .
See #2091 
See #2091
See #2091

RD-5206 The unsaved filter in Service page cannot be reused if removed (#2091)

---

app/components/GettingStartedModal/schema/gettingStarted.schema.json
app/translations/en.json
scripts/checkDocs.sh
scripts/readmesConfig.json

This change goes to `6.4.0-build` branch only. 
For the `master` branch there will be a PR with only blueprint examples links changes.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3240)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3240/) - one test failed due to known issue - RD-5020 - so I'm considering it as PASSED
N/A

RD-4999 Update blueprint examples links and documentation links for v6.4

---

app/components/GettingStartedModal/schema/gettingStarted.schema.json
app/translations/en.json

Extracted blueprint links update from #2095 .
N/A
Already done within #2095.
N/A

RD-4999 Update blueprint links

---

test/cypress/integration/widgets/deployments_spec.ts
widgets/common/src/deployments/DeploymentActions.ts
widgets/common/src/deployments/UpdateDeploymentModal.tsx

Cherry-pick #2097
See #2097
See #2097
See #2097

[6.4] RD-5352 Add new action switches to the Deployment Update modal

---

app/components/LoginPage.tsx
app/configureStore.ts
app/reducers/configReducer.ts
app/translations/en.json
app/tsconfig.json
app/utils/ConfigLoader.ts
backend/app.ts
backend/config.ts
backend/db/Connection.ts
backend/handler/ManagerHandler.ts
backend/package-lock.json
backend/package.json
backend/routes/Auth.ts
backend/routes/Config.ts
backend/routes/Config.types.ts
conf/README.md
conf/userConfig.json
test/cypress/fixtures/configuration/userConfig.json
test/cypress/integration/login_spec.ts
test/cypress/integration/user_configuration_spec.ts
test/cypress/support/commands.ts

Cherry-pick #2093
See #2093
See #2093
See #2093

[6.4] RD-4936 Add first login credentials hint to the Login page

---

.size-limit
package-lock.json
package.json
test/cypress/integration/widgets/topology_spec.ts
webpack.config.js

RD-5390 Upgrade topology to v4 (#2103)

---

backend/routes/Terraform.ts
widgets/common/src/terraformModal/TerraformModal.tsx

Cherrypick of #2092 
Please see #2092 
Please see #2092 
Please see #2092

RD-5399: Fixed variables & outputs detection on zip files (#2092)

---

app/components/GettingStartedModal/schema/cloudSetup.schema.json
app/components/GettingStartedModal/schema/gettingStarted.schema.json

fixing blueprints and links for cloudSetup and gettingStarted

---

app/components/GettingStartedModal/schema/cloudSetup.schema.json
test/cypress/integration/getting_started_spec.ts

Corrections after #2113
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/3323/ - `getting_started_spec` only
N/A

RD-5510 Corrections after #2113

---

app/components/GettingStartedModal/schema/cloudSetup.schema.json
test/cypress/integration/getting_started_spec.ts

RD-5510 #2116 merge to 6.4

---

test/cypress/integration/widgets/blueprints_terraform_spec.ts
widgets/common/src/terraformModal/TerraformModal.tsx

Changes consists of reusing validating functions while importing variables and outputs from terraform module.
Futher refactor was not made as there is a [dedicated ticket](https://cloudifysource.atlassian.net/browse/RD-5332) for that
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3305)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3305/)
N/A
Yes, corresponding PR with cherrypick will be created 🚀

RD-5368: Revalidating variables and outputs after their import

---

widgets/common/src/terraformModal/TerraformModal.tsx

Please see #2106 
Please see #2106 
Please see #2106 
Please see #2106

RD-5368 #2106 merge to 6.4

---

app/components/GettingStartedModal/schema/cloudSetup.schema.json

https://github.com/cloudify-cosmo/cloudify-stage/pull/2090
https://github.com/cloudify-cosmo/cloudify-stage/pull/2090
https://github.com/cloudify-cosmo/cloudify-stage/pull/2090
https://github.com/cloudify-cosmo/cloudify-stage/pull/2090

RD-2430 Add secrets to OpenStackV3 in GettingStartedModal (#2090)

---

jenkins/Jenkinsfile

Changes consists of removing `dependabot` string from regexp that is triggering the execution of System Tests on Jenkins.
N/A
N/A
N/A

RD-5597: Removed triggering System Tests on dependabot branches

---

jenkins/Jenkinsfile

During removal of dependabot branches from pattern responsible for initializing execution of System Tests `/` character was not been removed (#2131 )
Because of that, we are encountering issues related to the execution of the System Tests on a master branch, as it now is also required to have a `/` sufix
This PR is resolving that issue, making the [RD-5597](https://cloudifysource.atlassian.net/browse/RD-5597) correctly implemented
N/A
N/A
N/A

RD-5597: Removed dependabot naming residue

---

jenkins/Jenkinsfile

Regexp responsible for detecting branch is expecting to have extra characters after the `master` phrase
Because of that, I'm removed that requirement (which could be also problematic from the `+.-build` phrase perspective)
To check if the solution would work, I've executed [composer System Tests](https://jenkins.cloudify.co/job/Composer-UI-Multibranch/job/master/745/) with that modification (using the `replay` option) and it seems to be working properly 🎉  
N/A
N/A
N/A

RD-5617: Adjusted branch regexp

---

backend/tsconfig.json

Changed backend TS config base. See https://github.com/cloudify-cosmo/cloudify-blueprint-composer/pull/1086.
N/A
CI verification only
N/A

RD-5461 Change backend TS config base

---

test/cypress/integration/widgets/sites_spec.ts

Changes consists of adjusting location values, so that [sites_spec](https://github.com/cloudify-cosmo/cloudify-stage/blob/master/test/cypress/integration/widgets/sites_spec.ts) tests scenarios would be passing successfully
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3461)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3461/)
N/A

RD-5624: Adjust location values

---

widgets/labels/src/LabelsTable.tsx

N/A
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3466/pipeline
N/A

RD-5631 Fix labels_spec

---

backend/tsconfig.json
test/cypress/integration/widgets/deployment_actions_workflow_parameters_spec.ts
test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts
test/cypress/integration/widgets/deployment_button_spec.ts
test/cypress/integration/widgets/deployment_info_spec.ts
test/cypress/integration/widgets/executions_spec.ts
test/cypress/integration/widgets/topology_spec.ts
test/cypress/support/blueprints.ts
test/cypress/support/commands.ts
widgets/common/src/secrets/SecretActions.ts
widgets/common/src/secrets/SecretsModal.tsx
widgets/common/src/types.ts
widgets/deployments/src/DeploymentsList.tsx

Increased topology spec blueprint upload timeout.
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/3471/ - `topology_spec` only
N/A

RD-5625 Topology spec fix

---

app/components/sidebar/TenantSelection.tsx
app/components/sidebar/UserMenu.tsx
templates/pages/adminDash.json
templates/pages/blueprints.json
templates/pages/environments.json
templates/pages/logs.json
templates/pages/tenants.json

Changes consisting of modifying icons across the sidebar (according to [RD-3481](https://cloudifysource.atlassian.net/browse/RD-3481) guideline)
N/A
N/A

RD-3481: Updated sidebar icons

---

templates/pages/blueprintMarketplace.json

Cherry-pick #2147.
See #2147.
See #2147.
See #2147.

[6.4.1] RD-5613 Adjust height of Blueprint Marketplace tabs

---

app/components/basic/index.ts

RD-1563
it seems like after ApproveButton migration to TS this problem is solved, for example, there is a similar situation with `CancelButton` which still needs this assertion in Stage because the typescript version of this component wasn't released yet. 
I left the [comment ](https://github.com/cloudify-cosmo/cloudify-stage/blob/55b1cce087e378dd23d9b39325a5410d5f7ed3db/app/components/basic/index.ts#L99)about RD-1563 because there are still 3 other assertions that needs to be removed after migrating components to TS. I'll update TS migration components epic to remove this assertion in Stage during migration.
n/a
currently Jenkins test doesn't work :( 
n/a

RD-1563 remove overriding assertion for ApproveButton

---

backend/handler/RequestHandler.ts
backend/package-lock.json
backend/package.json
backend/routes/ServerProxy.ts
conf/README.md
conf/userConfig.json
jenkins/build-pod.yaml

RD-5665 #2173 merge to 6.4.1

---

backend/package-lock.json
backend/package.json

It's similar change to #2177 , but with only `follow-redirects` version bump.
N/A
Tested manually in real production environment.
N/A

RD-5965 Bump `follow-redirects` package in cloudify-stage backend

---

test/cypress/integration/flows/user_spec.ts

RD-5448
- update user_spec to resolve issue
n/a
the test is failing https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3600/ because there's another issue that was noticed earlier: https://cloudifysource.atlassian.net/browse/RD-5918
the isssue mentioned by Norbert in comments:  [User flow -- uploads blueprint using first journey buttons (failed).png](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3599/artifact/cloudify-stage/test/cypress/screenshots/flows/user_spec.ts/User%20flow%20--%20uploads%20blueprint%20using%20first%20journey%20buttons%20(failed).png) no longer appears
n/a

RD-5448 fix user_spec

---

widgets/agents/README.md
widgets/blueprintUploadButton/README.md
widgets/deployments/README.md

Documentation sync PR as https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2328 was merged.
N/A
N/A
Related change: https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2328

CD-7 Update widget documentation

---

jenkins/Jenkinsfile

The error was due to update of jnlp image which is missing. After changes provided by Yuval functions working fine again: https://github.com/cloudify-cosmo/pipeline-shared-library/commit/9d2fa9e1faf70fdcd036effe37f862f27d7067c6
N/A
N/A
N/A

RD-5947 Back to `getVersion` & `getPreRealease` functions 

---

jenkins/Jenkinsfile

The error was due to update of jnlp image which is missing. After changes provided by Yuval functions working fine again: https://github.com/cloudify-cosmo/pipeline-shared-library/commit/9d2fa9e1faf70fdcd036effe37f862f27d7067c6
N/A
N/A
N/A

RD-5947 Update Jenkinsfile

---

jenkins/Jenkinsfile
widgets/agents/README.md
widgets/blueprintUploadButton/README.md
widgets/deployments/README.md

Documentation sync PR as https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2330 was merged.
Not to spoil `6.4.1-build` branch with workarounds, let's wait for RD-5947 - it should make CI pipeline working again.
N/A
N/A
Related change: https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2330

CD-7 Update widget documentation [6.4]

---

app/utils/External.ts
backend/package-lock.json
test/cypress/support/blueprints.ts
widgets/common/src/blueprints/BlueprintActions.ts

This PR is a continuation of #2171.
Within this PR [comments from the #2171](https://github.com/cloudify-cosmo/cloudify-stage/pull/2171#pullrequestreview-1127205697) should be addressed 💪  
N/A
According to the recommendation, they're being executed 😁 
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3632)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3632/)
N/A

RD-6005: Adjustments for using multipart form data

---

.size-limit
jest.config.js
package-lock.json
package.json

RD-6069
There's a new audit issue about recharts, so we needed an update to 2.1.14. 
However, Recharts version above `2.1.12` was breaking Jest test with `SyntaxError: Unexpected token 'export'`  https://github.com/recharts/recharts/issues/2915 https://github.com/recharts/recharts/issues/2991. This issue doesn't appear in 2.1.12 but this version was breaking npm audit... https://github.com/recharts/recharts/issues/2658#issuecomment-1263176213
I did some digging around the topic and in general, this issue should be resolved by Recharts, however, this repo is not updated on regular basis, so I did some workaround with `moduleNameMapper` which seems to resolve both issues with audit and dependencies and it will resolve the issue from Snyk as well.
n/a …

RD-6069 Audit fails on recharts

---

app/translations/en.json
widgets/blueprintCatalog/src/RepositoryCatalog.tsx
widgets/blueprintCatalog/src/RepositoryTable.tsx
widgets/blueprintCatalog/src/widget.css

RD-5450
zeplin mockups: https://app.zeplin.io/project/612e8cb57788ff10babc7900/screen/62d54f617ecb5513598e4c2e
- changed the design to match mockups
Important notes: 
- I didn't change the buttons and texts colors because I wasn't sure if this should be part of this ticket 🤔 or it should be part of theming
- Also, I'm wondering what color should be on the button on the hover (because as I understand correctly the blue button should appear on the hover on the whole segment, not only on the button). The mockups don't cover this state. 
- Another issue with the icons: currently, we could have a disabled state of "Upload" button which is slightly lighter than active. So if I match the colors of icons to the current design it looks like all the icons and buttons are disabled:
Before:
After: …

RD-5450 new design of Blueprint marketplace

---

widgets/highAvailability/src/widget.tsx

Jira ticket: RD-5772
N/A
N/A
N/A

RD-5772 Migrate highAvailability (Cluster Status) widget to TypeScript

---

package-lock.json

`package-lock.json` get broken after merging https://github.com/cloudify-cosmo/cloudify-stage/pull/2208 .
See errors in RD-6092 description. This PR fixes it by just running `npm install` locally and updating `package-lock.json` file.
N/A
Executed [Stage-UI-Multibranch/RD-6092 #2](https://jenkins.cloudify.co/blue/organizations/jenkins/cloudify-stage/detail/RD-6092/2/pipeline) with modified Jenkinsfile to check if `Build RPM` step is passing => All good.
N/A

RD-6092 Fix package-lock.json

---

app/components/GettingStartedModal/GettingStartedModal.tsx
app/components/GettingStartedModal/ModalContent.tsx
app/components/GettingStartedModal/createEnvironmentsGroups.tsx
app/components/GettingStartedModal/installation/tasks.ts
app/components/GettingStartedModal/model.ts
app/components/GettingStartedModal/schema/cloudSetup.schema.json
app/components/GettingStartedModal/schema/gettingStarted.schema.json
app/components/GettingStartedModal/steps/EnvironmentsStep/EnvironmentsStep.tsx
app/components/GettingStartedModal/steps/SummaryStep/SummaryStep.tsx
app/components/GettingStartedModal/steps/WelcomeStep.tsx
app/translations/en.json

Jira ticket: RD-5607
I implemented according to the following comment:
https://cloudifysource.atlassian.net/browse/RD-5607?focusedCommentId=77330  Here is the copy of the comment:
> Jakub Niezgoda 
> August 22, 2022, 4:27 AM
> @ Leon Gilyadov You will probably need to change the format of schema files (cloudSetup.schema.json and  gettingStarted.schema.json). Currently they are list of objects and if we add custom message for each file, then more suitable would be to have something like:
> ```
> {
>     welcomeText: "...",
>     content: <current file content>
> }
>```
> The current text is in en.json file at the following path: /gettingStartedModal/welcomeText
Changing `welcomeText` to `"aaa"`:
```
{
"welcomeText": "aaa",
"content": [
{
"name": "aws",
...
```
resulting in:
16-Oct-2022 …

RD-5607 Add an option to customize the first screen messaging

---

app/components/GettingStartedModal/ModalContent.tsx
app/components/GettingStartedModal/steps/WelcomeStep.tsx

Follow up PR to #2218
There was added an additional comment to #2218 after it was approved and merged.
This follow up PR addresses this comment.
N/A
17-OCT-2022 `getting_started_spec`:  ✅  passed
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3707/pipeline
There is no any documentation for Getting Started Modal in docs.cloudify.co

RD-5607 Part 2

---

app/components/WidgetDynamicContent/WidgetDynamicContent.tsx
app/components/basic/index.ts
app/components/license/UploadLicense.tsx
package-lock.json
package.json
widgets/blueprintActionButtons/src/BlueprintActionButtons.tsx
widgets/blueprintCatalog/src/UploadingMessage/UploadingMessage.tsx
widgets/blueprints/src/BlueprintsList.tsx
widgets/common/src/deployModal/GenericDeployModal.tsx
widgets/common/src/deploymentsView/detailsPane/drilldownButtons/index.tsx
widgets/common/src/executeWorkflow/ExecuteWorkflowInputs.tsx
widgets/common/src/executeWorkflow/ExecuteWorkflowModal.tsx
widgets/common/src/executeWorkflow/types.ts
widgets/common/src/types.ts

Changes consist of:
- updating `cloudify-ui-components` package to the newest version - `2.21.0`
- pulling changes from #2215 
- resolving `Field` type incompability
- resolving issue mentioned in [this comment](https://github.com/cloudify-cosmo/cloudify-ui-components/pull/172#discussion_r999018798) 🎉
After merging this PR, I'll be closing #2215 as its content will be provided within this PR 💪 
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Composer-UI-System-Test&build=3722)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Composer-UI-System-Test/3722/) - failed due to the CI/CD issues (same issues appeared on todays [nightly](https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3723/pipeline))
[![Build …

RD-6130: Updated cloudify-ui-components library

---

app/components/shared/cluster/ClusterServicesOverview.tsx
app/components/shared/cluster/ClusterStatusIcon.tsx
app/components/shared/cluster/consts.ts
app/components/shared/cluster/types.ts
app/components/sidebar/HealthIndicator.tsx
app/components/status/SystemServicesStatus.tsx
test/cypress/integration/widgets/cluster_status_spec.ts
test/cypress/integration/widgets/spire_manager_spec.ts

I decided to split the migration of RD-5755 to multiple PRs to make tracking changes and reviewing the code easier. 
In this PR I made some of the TS migrations that prerequisite to the RD-5755.
Locally tested `test/cypress/integration/widgets/cluster_status_spec.ts` 2022-Oct-24 at 16:06 ✅ passed:
24-Oct-2022 16:21 `test/cypress/integration/widgets/spire_manager_spec.ts` ✅ passed:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3734/pipeline
N/A

RD-5755 Part 1: convert clusterServiceStatusEnum to ClusterServiceStatus

---

.eslintrc.json
backend/package-lock.json
backend/package.json
backend/tsconfig.json
package-lock.json
package.json

Reused common backend tsc and eslint configs
N/A
CI verification
N/A

RD-3132 RD-3133 Reuse common backend tsc and eslint configs

---

widgets/blueprintCatalog/src/RepositoryCatalog.tsx

RD-6095 
- simplify layout in [RepositoryCatalog.tsx](https://github.com/cloudify-cosmo/cloudify-stage/pull/2232/files#diff-b6347669f6370f72e26d1693322755e5593d51cf8eb13dac5cb2bd7287e41bc6) so now the marketplace has more responsive look
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3740)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3740/)  - blueprint_catalog_spec.ts
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3745)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3745/) - all tests, failing test is not connected to current changes
n/a

RD-6095 adjustment number of columns in marketplace

---

test/cypress/integration/widgets/blueprint_catalog_spec.ts
widgets/blueprintCatalog/src/widget.tsx

RD-6100
- change default values of fieldsToShow in blueprints catalog marketplace to show only Name and Description
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3750)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3750/) - blueprint_catalog_spec.ts
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3751)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3751/) - all tests, the fail test is known issue
n/a 
there is separate ticket for that

RD-6100 Remove Creation and Update dates from marketplace widget

---

semantic-ui/site/collections/form.overrides.less
semantic-ui/site/collections/form.variables.less
semantic-ui/site/elements/input.overrides.less

- Modifying [Semantic UI Less variables](https://github.com/Semantic-Org/Semantic-UI-LESS) to adjust error input presentation
- Adjusting labeled input border color while the input is being hovered
N/A
N/A

RD-3489: Styled input errors

---

semantic-ui/site/collections/form.overrides.less
semantic-ui/site/collections/form.variables.less
semantic-ui/site/elements/input.overrides.less
semantic-ui/site/elements/input.variables.less
semantic-ui/site/globals/site.variables.less
widgets/blueprints/src/BlueprintsList.tsx

- Styling Textarea component
- Unifying & reusing some styling properties shared across `Form` components
Changes may not look spectacular, as apparently most of the necessary changes were introduced while implementing #2227 (styling input component), but still some styling modifications has been provided 🎸 
N/A
N/A

RD-6023 Styled Textarea component

---

app/components/sidebar/HealthIndicator.tsx

This PR is fixes `test/cypress/integration/cluster_status_spec.ts` that was broke after I merged #2229.
N/A
All specs 30 Oct 2022 10:56 IL time  ✅ passed:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3766/pipeline
All specs 28-oct-2022 18:41 IL time:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/3763/pipeline
N/A

 RD-5755 Fix `test/cypress/integration/cluster_status_spec.ts` test

---

app/components/GettingStartedModal/common/managerHooks.ts
app/utils/Manager.ts
widgets/pluginsCatalog/src/PluginsCatalogList.tsx

Jira ticket: RD-5280:
> There are 2 places in Stage code where we construct distribution full name (distro name + distro release) to select wagon files when uploading plugins: 
> - Plugins Catalog widget 
> - Getting Started Modal (part of the app framework)
>
> It could be extracted and re-used across the app framework and widgets.
There is  also a comment in the Jira ticket:
> @ Leon Gilyadov Please check with @ Jakub Madej if there’s any case in Composer app where we use similar constructs to select wagon files when uploading plugins. If there’s something in Composer as well, then it would make sense to extract the code even higher (to cloudify-ui-common-*).
N/A
`wagonUrl` is used to fetch data.
Here is a related screenshot of Plugins Catalog widget, after the changes in this PR:
all …

RD-5280 Deduplicate plugin wagon name creation logic

---

backend/package-lock.json

Changes consists of updating `package-lock.json` file via `npm run audit` command
N/A
I didn't execute System Testes as I think that the PR pipeline tests are sufficient in that case 💪 
N/A

RD-6276 Fixed xmldom vulnerability

---

package-lock.json

Changes consts of:
- Relocking `jsdom` and `jest-environment-jsdom` package to bump up `nwsapi` package
- Executing `npm audit fix` command to make sure that some minor vulnerabilities would be resolved along the way ;)
I've seen that tomorrow we could start experiencing the same issue as [cloudify-ui-common](https://cloudifysource.atlassian.net/browse/RD-6280).
After merging this PR, we should be able to avoid that opportunity beforehand 💪 
N/A
N/A
N/A

RD-6294 Resolved nwsapi vulnerability

---

app/README.md
doc/README.md
widgets/README.md

Moved widget and app framework related documentation to more accurate places.
N/A
N/A
This PR is all about documentation.

RD-6114 Update internal documentation

---

widgets/filters/src/FiltersTable.tsx
widgets/secrets/src/SecretsTable.tsx
widgets/userGroups/src/UserGroupsTable.tsx
widgets/userManagement/src/UsersTable.tsx

RD-6182 
- align the checkbox to the left side
should i run any test? 🤔

RD-6182 PP - System Setup user table adjustment

---

test/cypress/integration/flows/user_spec.ts

Removal of unnecessary test scenarios skipping
N/A
N/A
N/A

RD-5918 Unskipped tests

---

semantic-ui/site/collections/form.variables.less
semantic-ui/site/elements/label.variables.less
semantic-ui/site/globals/site.variables.less
semantic-ui/site/modules/dropdown.overrides.less
semantic-ui/site/modules/dropdown.variables.less
widgets/blueprints/src/BlueprintsList.tsx

Changes consists of updating theming variables and applying necessary overrides in order to adjust dropdown component to the [new designs](https://app.zeplin.io/project/63021ced403e55165cc8566f/screen/6348a68b38eb8d54c3611d41) 
N/A
N/A

RD-6020 RD-6021 Theming of the dropdown component

---

test/cypress/integration/widgets/blueprints_terraform_spec.ts
test/cypress/integration/widgets/topology_spec.ts

RD-6393 verification if system tests still needs to be skipped 
n/a
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3863)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3863/)  - both tests - blueprints_terraform_spec.ts & topology_spec.ts
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3864)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3864/) - blueprints_terraform_spec.ts
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3865)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3865/) - topology_spec.ts
[![Build …

RD-6393 Unskip system tests

---

package-lock.json

RD-6404 fix audit for loader-utils 
n/a
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3872)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3872/) failed tests - known issues -> RD-5266 & RD-6388
I run stage locally as well - didn't notice any issues.
n/a

RD-6404 Audit fix for loader-utils

---

test/cypress/integration/widgets/blueprint_catalog_spec.ts

RD-6119 adding system test to cover new functionality 
n/a
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3871)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3871/)
n/a

RD-6119 cypress test

---

.size-limit
app/app.tsx

Changes are consisting of importing `font-cloudify.css` stylesheet, which is containing styling for some custom icons (used within `events` widget)
I've also took a look across the application, to check if importing new font is having an impact on other icons, but it seems that other icons were unmodified 🎉 
N/A
N/A

RD-6399 Fixed presentation of event logs icons

---

.size-limit
app/components/EditModeButton.css
app/components/sidebar/PagesList.tsx
app/components/sidebar/SideBarItem.tsx

RD-6189
- add css style to change color on hover on buttons in sidebar in editMode
- add styles to change position of removeIcon so it will be aligned 
- also found a bug with removeIcon in subitem - this icon was slighty outside the menu (see screenshot) so I fixed that as well
Before: 
After (I disabled `hidden` properties just for screenshots so we could see more removeIcons)
n/a

RD-6189 PP sidebar adjustment in editMode

---

semantic-ui/site/collections/message.overrides.less
semantic-ui/site/collections/message.variables.less
semantic-ui/site/globals/site.variables.less
widgets/blueprints/src/BlueprintsList.tsx

- Updating theming LESS variables
- Providing overrides for some of `<Message />` styling
N/A
N/A

RD-6022 Message component theming

---

app/components/templateManagement/TemplateManagement.tsx
app/components/templateManagement/pageGroups/PageGroups.tsx
app/components/templateManagement/pages/CreatePageModal.tsx
app/components/templateManagement/pages/Pages.tsx
app/components/templateManagement/templates/CreateTemplateModal.tsx
app/components/templateManagement/templates/RoleList.tsx
app/components/templateManagement/templates/Templates.tsx
app/components/templateManagement/templates/TenantList.tsx
app/components/templateManagement/templates/types.ts
backend/handler/templates/PagesHandler.ts
backend/handler/templates/types.ts
backend/routes/Templates.types.ts

Migrated all remaining files in `app/components/templateManagement` directory to TypeScript.
Minor type-safety improvements included.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3877)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3877/) (18.11.2022) - failed due to interrupted exception (RD-4319), but all template management related tests passed, so I think we're quite safe;
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3878)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3878/) (18.11.2022) - PASSED (failing only on known issue - RD-6388)
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&buil …

RD-5759 Migrate app framework - `templateManagement` components to TypeScript

---

app/components/shared/cluster/ClusterService.tsx
app/components/shared/cluster/ClusterServicesOverview.tsx

RD-6194 
- adjust font size to 16px
- small refactoring - change inline styles to `style-components`
After: 
n/a
n/a

RD-6194 PP change of font-size

---

app/components/EditTabModal.tsx
app/components/EditWidgetModal.tsx

Changes consists of reordering `<ApproveButton />` and `<CancelButton />` in modals as described in RD-6403
N/A
[Configuring widget](https://docs.cloudify.co/latest/working_with/console/customization/edit-mode/) may need an update regarding one screenshot but as theming changes will soon be merged to the `master` branch, I didn't made any screenshots update as they'd need to be updated once more, after delivering theming changes 😄

RD-6403: Standardize Approve and Cancel buttons order of presentation

---

test/cypress/integration/widgets/deployment_actions_workflow_parameters_spec.ts
test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts

I got an info from Lukasz that the fix needed for RD-6455 won't be provided this week probably, so I'm skipping 2 tests for now.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3915)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3915/) - only 2 specs modified in this PR - both PASSED
N/A

RD-6455 Skip failing tests

---

backend/package-lock.json
backend/package.json

[RD-5881](https://cloudifysource.atlassian.net/browse/RD-5881) there is no corresponding version of types/node 16.16.0 the only available version is 16.11.* or 16.18.*, so we decided to go for 16.11.68
n/a
n/a 
n/a

RD-5881 upgrade node/types to v16.11.68

---

widgets/executions/src/widget.css

Changes consists of adjusting CSS to meet the RD-6177 requirements
In addition, some unnecessary CSS rules were removed 🎉 
N/A
N/A

RD-6177 Adjusted placement of the ExecutionWorkflowGraph toolbar icons

---

test/cypress/integration/widgets/deployment_actions_workflow_parameters_spec.ts
test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts

Reverts cloudify-cosmo/cloudify-stage#2282 (as fix on the core side - https://github.com/cloudify-cosmo/cloudify-manager/pull/3940 was merged).
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3943)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3943/) - only `deployment_actions_workflow_parameters_spec` and `deployment_button_deployment_inputs_spec` - both PASSED
N/A

RD-6455 Unskip tests

---

semantic-ui/site/elements/button.overrides.less

Changes consists of updating `button.overrides.less` file to apply the same `margin-top` property button icons 🎉 
Difference is almost not visible 😄, but pixel-wise everything is now perfectly aligned 🎉 
N/A
N/A

RD-6176 Align drilldown buttons

---

widgets/blueprintCatalog/README.md

RD-6078
n/a 
n/a
https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2438

RD-6078 update Blueprints Catalog documentation

---

app/utils/External.ts
app/utils/Manager.ts
widgets/common/src/actions/SearchActions.ts
widgets/common/src/deploymentsView/header/DeployOnModal.tsx
widgets/common/src/deploymentsView/header/RunWorkflowModal.tsx

Changes consists of migrating the following files:
- `app/utils/External.ts` 
- `app/utils/Manager.ts`
In the upcoming PR the rest of not migrated `app/utils/` files will be migrated 🎉 
N/A
N/A
N/A

RD-5753 Migrating app/utils files to TS - Part 1

---

test/cypress/integration/templateManagement/pages_spec.ts

Changes consists of updating selector of an icon, which has been changed while introducing theming changes
N/A
System tests executed only for failing test scenario (`pages_spec`)
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3973)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3973/)
N/A

RD-6501: Fixed pages_spec system test

---

test/cypress/integration/widgets/deployments_view_spec.ts

Test fix
N/A
https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3989/
N/A

RD-6500 Test fix

---

widgets/common/src/actions/SearchActions.ts

Changes consists of applying fix for the [correctly spotted issue](https://github.com/cloudify-cosmo/cloudify-stage/pull/2289/files#r1038250739)
Thanks @kubama for spotting this and for spending your time on further investigation 🎉  
N/A
Executed system tests just for failing tests scenario 
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3998)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3998/)
N/A

RD-6465: Fixed incorrect parameters passing

---

test/cypress/integration/edit_mode_spec.ts

Fix for RD-6508
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4012/ - `should allow to switch tabs and maximize widgets` test case passes, other failures are covered by https://cloudifysource.atlassian.net/browse/RD-6526
N/A

RD-6508 Test fix

---

test/cypress/integration/page_spec.ts

Fix for RD-6523
N/A
https://jenkins.cloudify.co/job/Stage-UI-System-Test/4014/ - `page_spec` passes
N/A

RD-6523 Test fix

---

app/components/shared/cluster/types.ts
app/components/status/SystemServicesStatus.tsx
app/components/status/SystemStatusHeader.tsx

Last part of RD-5755
N/A
✅ passed - `test/cypress/integration/cluster_status_spec.ts` and `test/cypress/integration/widgets/cluster_status_spec.ts`:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/4023/pipeline
all specs 06-DEC-2022: The tests stopped running after the test 50 of 68 tests.
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/4016/pipeline
all specs 05-DEC-2022: tests setup error
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/4010/pipeline
N/A

RD-5755 PR-3 Migrate  components

---

app/utils/Internal.ts
app/utils/LoaderUtils.ts
app/utils/WidgetBackend.ts
widgets/common/src/actions/SearchActions.ts

- Modifying the way that the parameters were used be doListAll function (6c669ad6ae0539e2aca70be321abeefedde91035)
- Modifying the way of creating resource url (36b5bfe30e676638b50f79a7e30eb0aff55a81cc)
- Migrating away from anonymous functions usage within classes (9a30dba88896697b61f68cfb1d97314099972a36)
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4028)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4028/)
N/A

RD-6522, RD-6526 Fixed issues appearing in executions and edit_mode specs

---

test/cypress/integration/widgets/filter_spec.ts

Fix for RD-6540
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4032/
N/A

RD-6540 Test fix

---

test/cypress/support/templates.ts

Fix for RD-6527
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4033/ - specs affected by this PR (`page_groups_spec.ts`, `pages_edit_spec.ts`, `pages_preview_spec.ts`, `pages_spec.ts`, `template_management_spec.ts`, `templates_spec.ts`) are all passing
N/A

RD-6527 Tests fix

---

test/cypress/integration/flows/user_spec.ts
test/cypress/integration/widgets/blueprint_catalog_spec.ts
test/cypress/integration/widgets/blueprints_terraform_spec.ts

Reverts cloudify-cosmo/cloudify-stage#2299
https://jenkins.cloudify.co/job/Stage-UI-System-Test/4034/ - pass, the only failing test is covered by https://cloudifysource.atlassian.net/browse/RD-6465

RD-6497 Re-enable tests due to fixed manager issue

---

widgets/agents/README.md

due to  https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2451/files nighhtly stopped working
, this fixes
its result of running `npm run docWidgets` on latest master`

upgraded docs

---

test/cypress/integration/widgets/deployments_spec.ts
widgets/common/src/deployments/UpdateDeploymentModal.tsx

Fixed input default values handling when updating deployment to another blueprint
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4103/ - `deployments_spec.ts` only due to number of failing tests on `master`
N/A

RD-6222 Fix input default values handling when updating deployment to another blueprint

---

app/widgets/common/deployModal/GenericDeployModal.tsx
app/widgets/common/deploymentsView/configuration.ts
app/widgets/common/deploymentsView/index.ts
app/widgets/common/deploymentsView/table/DeploymentsTable.tsx
app/widgets/common/deploymentsView/table/columns.tsx
app/widgets/common/deploymentsView/table/renderDeploymentRow.tsx
widgets/deploymentsView/src/widget.tsx
widgets/deploymentsViewDrilledDown/src/widget.tsx

Fix for empty labels in deployments view widget configuration modal
N/A
Verified locally
N/A

RD-6162 Fix for empty labels in deployments view widget configuration modal

---

app/widgets/common/blueprints/UploadBlueprintBasicForm.tsx
app/widgets/common/filters/RuleRemoveButton.tsx
app/widgets/common/filters/RuleRowTypeDropdown.tsx

Further fixes for missing labels
N/A
Verified locally
N/A

RD-6162 Further fixes for missing labels

---

test/cypress/integration/widgets/deployments_spec.ts

Seems like #2348 has reverted a need for the previous fix, which was implemented within #2347 
Because of that, within this PR I'm reverting changes introduced by #2347
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4193)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4193/)
N/A

RD-6660: Modify input selector

---

backend/app.ts
backend/routes/Snapshots.ts
backend/test/routes/Snapshots.test.ts

Added endpoint for getting/restoring ua snapshots
N/A
Added unit tests
N/A

RD-4791 Add endpoint for getting/restoring ua snapshots

---

app/components/templateManagement/TemplateManagement.tsx
backend/handler/templates/PagesHandler.ts
backend/handler/templates/TemplatesHandler.ts
backend/handler/templates/types.ts
backend/routes/Snapshots.ts
backend/routes/Templates.ts
backend/routes/Templates.types.ts
backend/test/routes/Snapshots.test.ts
backend/test/routes/Templates.test.ts

Added snapshot support for templates and pages
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4213/
N/A

RD-4793 RD-4794 Add snapshot support for templates and pages

---

app/translations/en.json
app/widgets/common/secrets/SecretActions.ts
widgets/secrets/src/SecretsTable.tsx

RD-6372
- add a new column for Secret Provider
- change name from `hidden value` to `hidden`
- adjust columns widths
n/a
I'll update the documentation after all changes about secret widget will be finished
[RD-1234]: https://cloudifysource.atlassian.net/browse/RD-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RD-6372]: https://cloudifysource.atlassian.net/browse/RD-6372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RD-6372 create Secret Provider column in Secret widget

---

app/widgets/common/deployments/DeploymentActions.ts
test/cypress/integration/widgets/deployments_spec.ts

- it resolves this issue: RD-6798
before:
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4284)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/4284/)
n/a

RD-6798 align deploymentsAction method from put to post

---

app/widgets/common/deployModal/GenericDeployModal.tsx
test/cypress/integration/widgets/deployment_actions_spec.ts

Changes consists of hiding `Deploy On` dropdown on blueprint deployment modal, when it's being open on a specific environment 🎉 
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4299)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4299/)
N/A

RD-6804 Hiding DeployOn dropdown while deploying a blueprint on environments page

---

test/cypress/integration/widgets/blueprints_terraform_spec.ts

Looks like UI state after running 'allow to use new or existing secret as variable source' test case was not entirely consistent in terms of active page. To work around this I changed current page refresh to explicit test page visit in before each hook.
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4336/
N/A

RD-6833 Visit test page explicitly instead of refreshing current page

---

app/components/page/content/EmptyContainerMessage.tsx
app/components/page/editMode/AddWidgetModal.tsx
app/components/page/editMode/EditModeBubble.tsx
app/components/page/editMode/EditModeButton.tsx
app/components/page/editMode/EditTabModal.tsx
app/components/page/editMode/InstallWidgetModal.tsx
app/components/routes/ExternalRedirect.tsx
app/components/routes/LogoPage.tsx
app/components/routes/NotFoundPage.tsx

Migrated all remaining components in `app/components` folder to TypeScript.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4341)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/4341/) - `edit_mode_spec` failed, fixed and passing locally, the rest of failures are known issues.
N/A

RD-5761 Migrate application framework components to TypeScript

---

backend/package-lock.json

Updated `cookiejar` to vulnerability-free patch version.
N/A
CI verification only
N/A

RD-6872 Update `cookiejar` to vulnerability-free patch version

---

test/cypress/integration/user_configuration_spec.ts

The test execution hangs on `cy.visit`, even though test recording reveals that the page loads.
Having no better idea, I tried to make the `before` hook be as similar as possible to what's on L59 (which does not have the same issue). Hopefully it will fix the issue :crossed_fingers:.
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4357/
N/A

RD-6631 System test fix?

---

app/translations/en.json
widgets/snapshots/src/CreateSnapshotModal.tsx
widgets/snapshots/src/RestoreSnapshotModal.tsx
widgets/snapshots/src/SnapshotsTable.tsx
widgets/snapshots/src/UploadSnapshotModal.tsx
widgets/snapshots/src/actions.ts
widgets/snapshots/src/props/SnapshotPropType.ts
widgets/snapshots/src/widget.common.ts
widgets/snapshots/src/widget.tsx
widgets/snapshots/src/widget.types.ts
widgets/tsconfig.json

Snapshots widget TS migration.
Includes additional fix for an issue introduced by executions widget TS migration.
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4349/

RD-5783 Snapshots widget TS migration

---

app/translations/en.json
app/utils/hooks/useOpenProp.ts
widgets/tenants/src/GroupsModal.tsx
widgets/tenants/src/MenuAction.tsx
widgets/tenants/src/TenantDetails.tsx
widgets/tenants/src/TenantsTable.tsx
widgets/tenants/src/UserRoles.tsx
widgets/tenants/src/UsersModal.tsx
widgets/tenants/src/actions.ts
widgets/tenants/src/props/TenantPropType.ts
widgets/tenants/src/widget.tsx
widgets/tenants/src/widget.types.ts

Tenants widget TS migration
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4354/
N/A

RD-5784 Tenants widget TS migration

---

widgets/blueprintActionButtons/src/widget.tsx

Jira ticket: RD-6409
`blueprint_actions_spec` - ✅ passed:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/4350/pipeline
Nothing to update:
https://github.com/cloudify-cosmo/docs.getcloudify.org/blob/master/static/images/ui/widgets/blueprint-action-buttons.png

RD-6409 part 2: BlueprintActionButtons showEditCopyInComposerButton

---

app/components/routes/LoginPage.tsx

RD-4449
I tried to add a new styled component via styled-component however this doesn't seem to work 🤔even when I extract this component to `compoents\common` so instead I went for the inline styling. If you have any ideas why styled didn't work in that case or how to make it work pls share the knowledge 😅 It looks like it's working on HTML tags (like divs etc), but not on semantic components.
before:
after:
n/a
n/a

RD-4449 [PP] Fix error message styling in Login page

---

widgets/blueprintActionButtons/README.md
widgets/blueprints/README.md

This PR is about updating the documentation for RD-6409
N/A
N/A
PR in docs repo: https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2497

RD-6409 part 3: update documentation

---

test/cypress/integration/login_spec.ts
test/cypress/integration/user_configuration_spec.ts
test/cypress/integration/widgets/blueprints_terraform_spec.ts
test/cypress/integration/widgets/deployments_spec.ts
test/cypress/support/commands.ts
test/cypress/support/resource_urls.ts
widgets/agents/README.md
widgets/common/src/deployments/DeploymentActions.ts

RD-5266 RD-6798 RD-6431 backports from master
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4392/ - fixes for RD-5266 and RD-6431 working
After https://github.com/cloudify-cosmo/cloudify-stage/pull/2406/commits/cb25453e0b401191f50d7549632bb425968b13c1:
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4394/ (`deployments_spec` only) - fix for RD-6798 working
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/4397/pipeline/ - `deployments_view_spec` is passing now as well
N/A

RD-5266 RD-6798 RD-6431 backports

---

test/cypress/support/executions.ts

Cherry picked from commit 581b423ac2c7aeae9006c1238034d0fa63e2e3fd
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4407/
N/A

RD-6430 Improve killRunningExecutions cypress custom command (#2271)

---

widgets/README.md

Reviewed all links to "docs.cloudify.co" and updated accordingly.
More details about reasoning in RD-6282.
N/A
N/A
It's about documentation.

RD-6282 Update links to user documentation

---

test/cypress/integration/widgets/blueprint_sources_spec.ts

[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4420)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4420/)
In a recent CI run, the test failed since the "rightPane" was detached and totally rerendered from scrach
this makes it so we dont memorize the right pane in within scope, but we search it each time.
its a slight readability decrease in favour of hardening the tests.

RD-6899 Hardened blueprint test

---

app/widgets/common/actions/SearchActions.ts
app/widgets/common/blueprints/BlueprintActions.ts
widgets/blueprints/src/types.ts
widgets/blueprints/src/widget.tsx

Blueprint types improvements.
N/A
TODO
N/A

RD-5764 Improve blueprint widget types

---

package-lock.json
package.json
test/cypress/support/commands.ts

Changes consists of imitating functionality implemented in [cypress-get-table package](https://github.com/roggerfe/cypress-get-table/blob/master/src/index.js) in our repository 
N/A
I've executed only test files which are using `cy.getTable` command
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4456)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4456/)
N/A

RD-6931 Migrated away from cypress-get-table package

---

app/translations/en.json
widgets/plugins/src/MarketplaceModal.tsx
widgets/plugins/src/PluginsTable.tsx
widgets/plugins/src/widget.tsx
widgets/plugins/src/widget.types.ts

- Finalizing plugins widget migration to TS
- Migrated labels to translation file
- Migrated away from implicit `lodash` imports
- Migrated away from using `t` acronym, regarding translations
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4526)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4526/)
N/A

RD-5779 Migrated plugins widget 

---

app/translations/en.json
widgets/pluginsNum/src/widget.tsx

- fully migrating `pluginsNum` widget to TS
- migrating away from implicit `lodash` imports
- migrating `pluginsNum` widget labels to the translation file
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4523)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4523/)
N/A

RD-5780 Migrated pluginsNum widget

---

widgets/blueprints/README.md
widgets/deploymentButton/README.md
widgets/deployments/README.md

Changes consists of executing `npm run docWidgets` command to synchronize widgets documentation
N/A
N/A
N/A

RD-6444 Synchronized widgets documentation

---

app/actions/manager/auth.ts
app/actions/types.ts
app/components/routes/LoginPage.tsx

This PR was created to share an idea/direction on how to simplify login error handling.

Simplify login error handling

---

test/cypress/integration/widgets/filter_spec.ts

I noticed that `fetchFilteredDeployments` might also match `fetchDeployments`. I have no proof that this is the reason behind the failures, but I have no better ideas ATM.
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4572/
N/A

RD-6838 System test fix attempt

---

test/cypress/integration/widgets/deployment_actions_spec.ts

RD-6319 -  hotfix - adjusted tests for new validation

---

templates/pages/environments.json

Updated template
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4671/
Separate ticket

RD-6920 Updated template

---

test/cypress/integration/widgets/filter_spec.ts

Goal of this PR is to increase the stability of the system tests.
Because of that, I've increased expected timeout for a redirection to deployment page (which happens automatically after blueprint deployment), as we've started to have cases when current (default) 15s may be not sufficient.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4728)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4728/)
N/A

RD-7122: Increased timeout for redirection after blueprint deployment

---

.size-limit
app/translations/en.json
app/utils/hooks/useErrors.ts
app/widgets/common/helmModal/ClusterCredentialInput.tsx
app/widgets/common/helmModal/HelmModal.tsx
backend/handler/HelmHandler.types.ts
test/cypress/integration/widgets/blueprints_helm_spec.ts
widgets/environmentButton/src/CreateEnvironmentModal.tsx

Added validations and error handling
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4731/
Separate ticket

RND-96 Add validations and error handling

---

backend/app.ts

Removed snapshot endpoints from cookie-authenticated endpoints list
N/A
CI verification + manual test
N/A

RD-6709 Remove snapshot endpoints from cookie-authenticated endpoints list

---

app/components/page/content/PageContent.tsx

the previous PR ( #2479 ) caused an issue with edit_mode_spec (I noticed [failed test on jenkins](https://jenkins.cloudify.co/job/Stage-UI-System-Test/4761/testReport/junit/(root)/Edit%20mode%20should%20allow%20to%20manage%20tabs/should_allow_to_manage_tabs/)), so I'm reverting it to the original solution
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4762)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/4762/) edit_mode_spec
N/A

RND-209 fix edit mode spec

---

test/cypress/integration/widgets/blueprints_spec.ts
widgets/blueprints/src/BlueprintsCatalog.tsx
widgets/blueprints/src/BlueprintsCatalogActionButtons.tsx

- Aligning blueprint catalog buttons (8ceb07fa54059cfb295615897cc9b9fcd6e551de)
- Extracting blueprint catalog buttons as external component (7f00631082ad91da456b07928dbd27194ec3b1f0)
- Adjusting system tests (4974caaa6aa5105bbaeddc767b42fd55726305ff)
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4777)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4777/)
N/A

RD-6967: Align blueprint catalog action buttons

---

app/components/page/content/PageContent.tsx
templates/pages/blueprints.json

Cherry picked from commit https://github.com/cloudify-cosmo/cloudify-stage/commit/a5793304526a30b88344c639cf473f7651d42e25 (https://github.com/cloudify-cosmo/cloudify-stage/pull/2479)

RD-6711, RND-209 Seperate environments from services in Blueprints page

---

app/widgets/common/deploymentsView/DeploymentsView.tsx
app/widgets/common/deploymentsView/detailsPane/header.scss
app/widgets/common/deploymentsView/detailsPane/header.tsx
app/widgets/common/deploymentsView/layout.ts

Cherry picked from commit https://github.com/cloudify-cosmo/cloudify-stage/commit/0ed0e1271d474343a6a406a5d334c64ed5ffc2cf (https://github.com/cloudify-cosmo/cloudify-stage/pull/2483)

RND-166, RND-167 - move "Map" , "Filter", "Bulk actions" above the list of the deployments in services & environments page page

---

widgets/blueprints/src/BlueprintsCatalogActionButtons.tsx

It appears that in #2488 I could made some changes in browser, while developing feature, which enabled me to achieve the expected result without having a full implementation from the code perspective
This PR is fixing shortcomings which are visible on the screenshots below
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4786)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4786/)
N/A

RD-6967: Fixed buttons allignment

---

widgets/deploymentsView/README.md

Synced Deployments View widget documentation.
N/A
CI only.
PR about documentation sync.

RD-6316 Update Deployments View widget documentation

---

test/cypress/integration/templateManagement/pages_edit_spec.ts
test/cypress/support/commands.ts

System test fix backport (cherry picked from commit 77e23d24ff4efc56f6ddde567ae338e058820c8a)
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4903/
N/A

RND-359 System test fix backport (#2523)

---

test/cypress/integration/widgets/deployments_view_spec.ts

Recently added test was relying on workflows connected to application's deployments.
As it's hard to determine what deployments would be available during test execution, it's hard to test availability of specific workflows.
Because of that, I've mocked the data returned from `/searches/workflows` endpoint, so that recently added test scenario would be independent of other system tests and current state of the system.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4907)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4907/)
N/A

RND-145: Mocked data for testing purposes 

---

test/cypress/integration/widgets/filter_spec.ts

Cherry picked from commit ab1c171af7f10755d105bb7db0c2ca8b283d6829
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4910/
N/A

RD-7122 #2473 backport to 7.0.0

---

backend/package-lock.json

Updated `vm2` to fix audit failure
N/A
CI verification only
N/A

RND-422 Update `vm2` to fix audit failure

---

app/components/templateManagement/templates/Templates.tsx
test/cypress/integration/templateManagement/templates_spec.ts

Fixed click event propagation prevention. Enhanced related test.
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4921/ :heavy_check_mark: 
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4945 :heavy_check_mark: 
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4946 :heavy_check_mark: 
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4947 :heavy_check_mark: 
N/A

RD-4589 Fix click event propagation prevention

---

app/translations/en.json
app/utils/StageAPI.ts
widgets/filter/src/Filter.tsx
widgets/filter/src/FilterDropdown.tsx
widgets/filter/src/types.ts
widgets/filter/src/widget.tsx

Full TS migration of Resource Filter widget with translation support and using explicit lodash imports.
N/A
1. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4938)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/4938/) - failed on known issues only (RD-4589 and RD-6901), so I'm considering it as PASSED
2. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4949)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/4949/) - full rerun after code review adjustments, failed on known issues only (RD-6631), so I'm considering it as PASSED
N/A

RD-5771 Migrate Resource Filter widget to TypeScript

---

app/components/templateManagement/templates/Templates.tsx
test/cypress/integration/templateManagement/templates_spec.ts

(cherry picked from commit 7cdb1f6c406a85fc0b75b566dbaa421bf8efa181)
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4954/
N/A

RD-4589 Fix click event propagation prevention (#2530)

---

test/cypress/integration/widgets/deployment_button_configuration_spec.ts

Used more precise method to select option from dropdown in recently failing spec.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4960)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/4960/) - only `widgets/deployment_button_configuration_spec.ts`
N/A

RD-6901 Improve dropdown option click

---

test/cypress/integration/widgets/deployment_button_configuration_spec.ts

Cherry pick of https://github.com/cloudify-cosmo/cloudify-stage/pull/2536
See https://github.com/cloudify-cosmo/cloudify-stage/pull/2536
See https://github.com/cloudify-cosmo/cloudify-stage/pull/2536
See https://github.com/cloudify-cosmo/cloudify-stage/pull/2536

RD-6901 Improve dropdown option click [7.0]

---

test/cypress/integration/templateManagement/pages_edit_spec.ts
test/cypress/integration/widgets/blueprint_num_spec.ts
test/cypress/integration/widgets/plugins_num_spec.ts
test/cypress/integration/widgets/sites_map_spec.ts
test/cypress/support/editMode.ts

Extended fix for widgets adding
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4962/
https://jenkins.cloudify.co/job/Stage-UI-System-Test/4963/
N/A

RND-359 Extend fix for widgets adding

---

widgets/environmentButton/src/widget.tsx

Changes consisting of modifying parameters responsible for filtering blueprints on the backend side
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4988)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4988/)
N/A

RND-57: Adjusted way of filtering blueprints

---

widgets/deploymentsView/README.md

Changes consists of synchronizing documentation after merging [docs.getcloudify.org#2541](https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2541)
N/A
N/A
N/A

RND-146: Synchronized documentation

---

test/cypress/integration/templateManagement/templates_spec.ts

As the `templates_spec` is failing more often due to a flakiness of one of the test scenario, I've decided to bring back retries which some time ago were used on this exact test scenario 
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=5019)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/5019/)
N/A

RD-4589: Added test retries

---

test/cypress/integration/auth_spec.ts

I was able to reproduce the problem in local environment after many (5-10) re-runs. Unfortunately from Cypress logs it all looks fine and it is unclear for me what is wrong here. I suspected cache issue and I used `interceptWithoutCaching` custom command, but without success. Ended up adding retries and confirmed that it helps (reproduced the problem and second attempt of "fails when license has expired" passed).
N/A
Only `auth_spec`:
1. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=5070)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/5070/)
1. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=5071)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System …

RD-7025 Add retries in run mode for `auth_spec`

---

Dockerfile
Dockerfile.backend

RND-643 Manager containers: declare basic containerSecurityContext
Create non-root users for Stage containers 
N/A
N/A
N/A

RND-643 - Non-root users for stage containers

---

Dockerfile
Dockerfile.backend
packaging/entrypoint.sh

RND-649 - Update non-root user for Stage containers

---

backend/package-lock.json
backend/package.json

Jira ticket: https://cloudifysource.atlassian.net/browse/RND-708
N/A
N/A

RND-708 vm2 audit fix

---

test/cypress/integration/templateManagement/templates_spec.ts

As discussed on one of our team meetings, I've increased number of retries for one of the `templates_spec` test scenario
N/A
N/A
N/A

RND-533 Increased number of retries

---

app/actions/manager/auth.ts
backend/handler/RequestHandler.ts
backend/routes/External.ts
backend/test/handlers/RequestHandler.test.ts
backend/test/routes/External.test.ts

Cherry-pick of #2564
N/A
See #2564
See #2564

RND-583 Improve redirects handling [7.0]

---

backend/package-lock.json
backend/package.json

update vm2 to 3.9.19
n/a
n/a
n/a

RND-886 cherry pick vm2 audit fix (#2560)

---

app/widgets/common/inputs/fields/DeploymentIdInputField.tsx
test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts

Cherry pick of #2573.
N/A
See #2573
N/A

CYBL-2046 Fix data source in Deployment ID input field [7.0.1]

---

test/cypress/integration/widgets/executions_spec.ts
widgets/executions/src/ExecutionsTable.tsx

Cherry-pick of #2581.
N/A
See #2581.
See #2581.

CYBL-2072 - Deployment Execution widget doesn't open execution's modal [7.0.2]

---

backend/test/routes/Plugins.test.ts

Cherry-pick https://github.com/fusion-e/fusion-stage/pull/57.
N/A
CI
N/A

NE-2894 Fix failing step "test backend"

---

backend/package-lock.json
package-lock.json

Used `npm audit fix` command in frontend and backend package to fix auto-fixable security issues.
N/A
CI
N/A

NE-9891 Fix security issues reported by NPM audit on production dependencies

---

app/utils/shared/PluginUtils.ts
backend/routes/Plugins.types.ts
test/cypress/integration/widgets/snapshots_spec.ts
test/jest/utils/shared/PluginUtils.test.ts

Cherrypick of https://github.com/fusion-e/fusion-stage/pull/140
* Add `manylinux` to fallback distribution list in `getWagon` function
* Modernize `getYamlUrl` and `getWagon` functions
* Add tests for `PluginUtils` functions
* Fix `file_size` type in `PluginWagonUrl` type
* 
https://jenkins.cloudify.co/job/Stage-UI-System-Test/5467/

NE-6680 Use `manylinux` as fallback distribution in plugins catalog (#140)

---

packaging/cloudify-stage.spec

As RHEL8 comes with gcc-toolset-9 (and not devtoolset-7), let us try to use that when installing/building isolated-vm NPM package.
---
This is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-stage/pull/2607

NE-12156 Enable building RPM on RHEL8

---

packaging/cloudify-stage.spec

In CentOS 7 devtoolset-7 will be used (as installed by Jenkins pipeline in cloudify-build-system).  In case of CentOS 8 we are going to rely on standard packages.
A PR in cloudify-build-system comming up soon.
---
This is a cherry-pick of https://github.com/cloudify-cosmo/cloudify-stage/pull/2611

NE-12156 Don't rely on devtoolset

---

packaging/cloudify-stage.spec

In CentOS 7 devtoolset-7 will be used (as installed by Jenkins pipeline in cloudify-build-system).  In case of CentOS 8 we are going to rely on standard packages.
A PR in cloudify-build-system comming up soon.

NE-12156 Don't rely on devtoolset to build RPM

---

backend/package-lock.json
backend/package.json

Version of `sharp` package was bumped.
N/A
CI related backend tests are passing.
N/A

NE-22809 Bumped version of sharp

---

backend/package-lock.json
package-lock.json

This PR upgrades follow-redirects package used by our dependencies to latest, not vulnerable version
N/A
N/A
N/A

NE-31914 Upgrade follow-redirects package

---

backend/handler/ArchiveHelper.ts
backend/handler/GitHubHandler.ts
backend/handler/ManagerHandler.ts
backend/package-lock.json
backend/package.json
backend/routes/ServerProxy.ts
backend/test/handlers/RequestHandler.test.ts
backend/test/handlers/widgets/validateUniqueness.test.ts
backend/utils.ts
package-lock.json
package.json

Attempt at upgrading axios to latest version `1.7.2`. There were couple of changes in types of headers, but most of the code seems compatible. I will run system tests to ensure we did not introduce some bugs.
N/A
N/A
N/A

NE-31906 Upgrade axios to latest version 1.7.2 and fix breaking changes

---

backend/package-lock.json
backend/package.json
package-lock.json
package.json

Fixing audit issues related to axios
N/A
N/A
N/A

Fixing audit issues

---

backend/package-lock.json
backend/package.json
package-lock.json
package.json

Cherry pick of #2648 
N/A
N/A
N/A

Fixing audit issues (cherry-pick)

---

backend/package-lock.json

Audit fix (cherry pick) of #2651 
N/A
N/A

Audit fix (cherry pick)

---

devServer.ts

Correct local backend address when starting frontend dev server (cherry-pick)

---

test/cypress/integration/widgets/blueprints_spec.ts
test/cypress/integration/widgets/deployments_view_spec.ts

Improving blueprints and deployments view specs
N/A
https://jenkins.cloudify.co/job/Stage-UI-System-Test/5810/

System tests blueprints_spec, deployments_view_spec fix

---

package-lock.json
package.json

Downgrade css loader to fix problem with loading images and fonts
N/A
N/A

Downgrade css loader 

---

widgets/deployments/src/widget.tsx

Porting https://github.com/fusion-e/fusion-stage/pull/838 to cloudify
N/A
https://jenkins.cloudify.co/job/Stage-UI-System-Test/5829/
N/A

NE-36163 Adjust deployments widget to breaking changes in manager

---

app/components/overlays/gettingStarted/installation/process.ts
app/components/overlays/gettingStarted/installation/tasks.ts
app/utils/shared/PluginUtils.ts
backend/routes/Plugins.ts
backend/routes/Plugins.types.ts
test/cypress/integration/getting_started_spec.ts
test/cypress/integration/widgets/blueprint_catalog_spec.ts
test/jest/utils/shared/PluginUtils.test.ts
widgets/pluginsCatalog/src/Actions.ts
widgets/pluginsCatalog/src/PluginsCatalogList.tsx
widgets/pluginsCatalog/src/types.ts

Added:
- loading all yaml files instead of one
- increasing plugin upload service timeout as we started loading more items to the manager
- providing tests improvements after changes
- replacing AWS with GCP in blueprint catalog spec because one of the tests is not passing due to types issues in blueprint yaml file, GCP works correctly 
N/A
[all_tests](https://jenkins.cloudify.co/job/Stage-UI-System-Test/5839/)

Getting started system test fix
