widgets/blueprints/src/UploadBlueprintModal.js

I think we need to add an indication in the UI that the icon image file is optional. Also, I recommend that we change the icon for the Open buttons (currently a paperclip) to a more common browse icon (usually a folder).

Rewrite the help messages for the blueprint upload modal

---

backend/routes/Auth.js

Screenshot example:
Possibly all of the errors generated by manager with unauthorized error:
1. API token authentication failed
2. OKTA authentication failed
3. No authentication info provided
4. Authentication failed for <User username={0}>
5. Authentication failed for {0}
6. Authentication token is invalid:\n{0}
7. Token is expired
8. No authentication info provided
9. Authentication failed for {0}

CY-161 - Update message in login page for unauthorized error

---

widgets/events/src/EventsTable.js
widgets/eventsFilter/src/widget.js

- Allow sorting fields in the logs and events table
- Updated height of events and logs filter widget

CY-204 - Allow sorting fields in the logs and events table

---

Jenkinsfile

Make sure that the access key belongs to a user with privileges on docs.cloudify.co

Deploy to doc.cloudify.co

---

widgets/common/src/DeployBlueprintModal.js
widgets/common/src/JsonUtils.js
widgets/common/src/UpdateDeploymentModal.js
widgets/deploymentButton/src/DeployModal.js
widgets/inputs/src/InputsTable.js
widgets/outputs/src/OutputsTable.js

- Fixed *CLI and GUI don't parse blueprint input files consistently regarding empty strings* (CY-367)
- Fixed *Deployment inputs: only strings supported (dict & list should also be available)* (CY-370)
- Updated Inputs, Outputs widgets and Deployment Creation modals.

CY-370 & CY-367 - Deployment Inputs handling

---

widgets/common/src/UpdateDeploymentModal.js

When blueprint changes in Deployment Update modal then inputs which exists in both (original and selected blueprint) are filled with original value:

CY-350 - When DDL's index changes Values delete- UI

---

widgets/executions/src/UpdateDetailsModal.js

Marked updated inputs in the deployment update screen (CY-379)
Added message in deployment update screen when no inputs were updated (CY-380)

CY-379 & CY-380

---

templates/pages/app.json

As https://github.com/cloudify-cosmo/cloudify-stage/pull/578 was not merged and probably will not be soon, I have created separate PR for the CY-352 fix.

Fixed non-admin template to redirect to System Resources page on click on Number of Plugins widget

---

widgets/common/src/UploadPluginModal.js
widgets/pluginUploadButton/src/UploadButton.js

- converted to common field for URL/File inputs
- added labels and mandatory indicator

CY-388 - Update Plugin Upload modal

---

widgets/events/src/EventsTable.js

Removed Blueprint ID from Events/Logs widget

CY-416 - Incorrect blueprint name on “Deployment Events/Logs” widget

---

widgets/executions/src/ExecutionsTable.js
widgets/executions/src/widget.js

CY-425 - Expose "ended_at" field in executions list

---

.circleci/config.yml
widgets/executions/src/ExecutionsTable.js

CY-476 - Copy to clipboard buttons in modal windows shall be in modal footer instead of modal content

---

widgets/common/src/ExecutionStatus.js
widgets/executions/src/ExecutionsTable.js
widgets/executions/src/widget.js

* Converted Params column on the right side in Executions table into Actions menu (similarly to what we already have for another widgets - Deployments, Tenant Management, ...)
* Menu content depends on the workflow type (update / not update), execution status (active / not active) and error presence

CYBL-493 - Add possibility to Kill not active executions

---

widgets/snapshots/src/CreateSnapshotModal.js
widgets/snapshots/src/RestoreSnapshotModal.js
widgets/snapshots/src/actions.js

CY-644 - Added 'Ignore plugin failure' option in snapshot restoration modal

---

app/utils/WidgetParamsHandler.js
widgets/highAvailability/src/ClusterNodesList.js
widgets/nodes/src/NodesTable.js
widgets/outputs/src/widget.js
widgets/snapshots/src/SnapshotsTable.js
widgets/tenants/src/TenantsTable.js
widgets/userGroups/src/UserGroupsTable.js
widgets/userManagement/src/UsersTable.js

Added search filter to the following widgets:
1. Nodes
2. User Management
3. Tenant Management
4. User Groups Management
5. Snapshots
6. Cluster Nodes

CY-669 - Add search filter to widgets presenting tabular data

---

app/components/templates/CreateTemplateModal.js

- Fixed CY-677 - Misleading 'All tenants' option checked in Create template modal
- Implemented CY-678 - Align the presentation of roles picks and tenants picks in new template creation

Template Management bugfixes (CY-677, CY-678)

---

templates/pages/logs.json
widgets/events/src/EventsTable.js

1. Extend Logs widget to show 15 logs per page instead of 10
2. Highlight text in Message column in Events/Logs widget when text searching is on in Events filter widget

CY-701 - Improve Logs page

---

app/components/basic/PopupHelp.js
app/components/basic/VisibilityIcon.js
widgets/common/src/DeployBlueprintModal.js
widgets/common/src/DeploymentInputsHeader.js
widgets/common/src/UpdateDeploymentModal.js
widgets/deploymentButton/src/DeployModal.js

Changes log:
- added possibility to send input value as string explicitly
- improved PopupHelp to allow adding Popup specific properties
- improved description for deployment inputs in modals

CY-708 - Deployment inputs from YAML file not properly recognized

---

widgets/deployments/src/DeploymentsSegment.js

Changes:
- removed additional column for resource visibility
- moved resource visibility to be floated right in deployment name column
- moved a bit up the name of the deployment
- extended blueprint column width

CY-699 - Not optimal distribution of space in Deployments widget

---

app/components/basic/form/FormDivider.js
widgets/common/src/DeploymentActions.js
widgets/common/src/ExecuteDeploymentModal.js
widgets/common/src/InputsHeader.js
widgets/executions/src/DryRunIcon.js
widgets/executions/src/ExecutionsTable.js
widgets/executions/src/SystemWorkflowIcon.js
widgets/executions/src/widget.js

CY-661 - Add dry-run indication in Executions widget

---

app/components/basic/RevertToDefaultIcon.js
app/components/basic/form/Form.js
app/components/basic/form/FormField.js
widgets/common/src/DeployBlueprintModal.js
widgets/common/src/ExecuteDeploymentModal.js
widgets/common/src/InputsHeader.js
widgets/common/src/InputsUtils.js
widgets/common/src/UpdateDeploymentModal.js
widgets/deploymentButton/src/DeployModal.js
widgets/deploymentWizardButtons/src/steps/InputsStep.js

- reduced duplicated code by creating InputsUtils with helper functions for all deployment inputs and execution parameters
- grouped (required, optional) and sorted parameters in execute worklow modal
- added support for multiline strings (as for now only if input has multiline default value)
- added revert to default value icon for execution parameters defined as booleans with default values
- fixed calulating Revert to Default Value icon presence (not proper in some very specific cases)

CY-713 - Align inputs/parameters in deployment creation/update, execute workflow modals and Inputs Step in Deployment Wizard

---

widgets/events/src/ErrorCausesIcon.js
widgets/events/src/ErrorCausesModal.js
widgets/events/src/EventsTable.js

CY-736 - Add extended error message modal for events/logs with error_causes

---

widgets/blueprintActionButtons/src/BlueprintActionButtons.js
widgets/blueprints/src/BlueprintsList.js
widgets/common/src/BlueprintActions.js
widgets/common/src/DeleteConfirm.js
widgets/common/src/PluginActions.js
widgets/plugins/src/PluginsTable.js

Force flag by default is false for blueprint removal (as it was before).
Force flag by default is true for plugin removal (as it was before).

CY-759 - Add force flag in blueprint and plugins deletion confirmation modal

---

app/components/basic/form/InputFile.js
widgets/common/src/DeployBlueprintModal.js
widgets/common/src/ExecuteDeploymentModal.js
widgets/common/src/InputsUtils.js
widgets/common/src/UpdateDeploymentModal.js
widgets/common/src/YamlFileButton.js
widgets/deploymentButton/src/DeployModal.js

- Unified YAML file provider look-and-feel and internal behaviour across all places of existence - ExecuteDeploymentModal, UpdateDeploymentModal, DeployModal and DeployBlueprintModal.
- Removed YAML file input field, created simple button on the right side of Inputs/Parameters header in all 4 modals
- Allowed providing YAML file with not all mandatory fields (before you must have provided YAML with all mandatory fields present, now you can load partial YAMLs one-by-one)
- Updating only fields with values provided in YAML (before all fields were updated, so values not provided in YAML were resetted)

CY-722 - Allow providing a YAML file for execution parameters in Execute workflow modal

---

app/components/Widget.js
app/components/WidgetDynamicContent.js
app/components/layout/Header.js
app/styles/style.scss
backend/handler/ArchiveHelper.js
widgets/deploymentWizardButtons/src/steps/ConfirmationStep.js
widgets/deploymentWizardButtons/src/steps/InputsStep.js
widgets/deploymentWizardButtons/src/steps/InstallStep.js
widgets/deploymentWizardButtons/src/steps/helpers/ResourceStatus.js
widgets/deployments/src/widget.js

- the deployment name is chosen automatically basing on the blueprint name and availability of name in CM, you can now change it:
- if you choose already existing name, you will see appropriate error message:

CY-645 - Implement minor improvements to Deployment Wizard

---

widgets/common/src/ExecutionActions.js
widgets/common/src/ExecutionStatus.js
widgets/common/src/ExecutionUtils.js
widgets/common/src/LastExecutionStatusIcon.js
widgets/deployments/src/DeploymentsList.js
widgets/deployments/src/DeploymentsSegment.js
widgets/deployments/src/DeploymentsTable.js
widgets/executions/src/ExecutionsTable.js
widgets/managers/src/ManagersTable.js

CY-792 - Add Resume action for cancelled and failed executions in Cloudify UI

---

app/components/basic/ResourceVisibility.js
app/components/basic/VisibilityField.js
app/components/basic/VisibilityIcon.js
app/utils/consts.js

Blueprints, Deployments, Secrets, Plugins, Snapshots widgets shall be now secured for the case when `visibility` field is not set properly in JSON data received from Manager.
In case UI gets invalid `visibility` value, grey `?` icon will be shown as in the example below:

CY-895 - WSOD in UI when resource visibility is not set properly in Cloudify Manager

---

app/components/basic/NodesTree.js
widgets/blueprintSources/src/BlueprintSources.js

- Fixed type hierarchy popup in nodes widget
- Added round brackets to number of imported blueprints in Blueprint Sources widget tree.

CY-965 - Type hierarchy popup in nodes widget doesn't show type hierarchy

---

templates/pages/adminDash.json
templates/pages/app.json
widgets/executions/src/widget.js
widgets/filter/src/Filter.js
widgets/filter/src/widget.js

Adding execution status to the Filter widget, it will be shown by default in the dashboard and it will be a dynamic list.

CY-928 Add execution status to the Filter widget

---

app/actions/app.js
app/components/basic/form/InputFile.js
backend/handler/AuthHandler.js
backend/routes/Auth.js
backend/routes/ServerProxy.js

Improved RBAC fetching logic to allow refetching RBAC on the fly when it is not in cache.
Cache check is done during maintenance status fetching from client-side. When RBAC is not in cache, then it is fetched from manager.

CY-1010 - RBAC fetching is not stateless

---

app/components/basic/pagination/Pagination.js
app/components/basic/pagination/PaginationInfo.js

Fixed setting page size to negative number causes WSOD and breaks all widgets from its type (CY-1039)
When user enters invalid value (not a number or integer not from range 1-500), then the following popup will be shown for 3 seconds:
and page size is reset to 5.
Fixed that after context change data table becomes empty when pagination is set to page higher than one (CY-1040)
When user displays tabular data on page no. X and changes context and after context change refetched data doesn't contain page no. X, then page number is changed to 1.

CY-1039 - Invalid page size & CY-1040 - Invalid page number

---

widgets/events/src/widget.js

1. Changed Events widget to use reported_timestamp instead of timestamp field 
2. Extended time string format from `DD-MM-YYYY HH:mm` to `DD-MM-YYYY HH:mm:ss.SSS` to show seconds and milliseconds

CY-1115 - Use reported_timestamp instead of timestamp in Events widget

---

app/actions/auth.js
app/actions/managers.js
app/components/AboutModal.js
app/components/LicensePage.js
app/containers/AboutModal.js
app/containers/LicensePage.js
app/containers/Users.js
app/utils/ErrorCodes.js
app/utils/External.js
app/utils/Interceptor.js
app/utils/Internal.js
app/utils/consts.js
backend/routes/Auth.js

For users without `upload_license` permission there's no *License Management* button present.
For users without `upload_license` permission there's no *Edit License* button present.
For users without `upload_license` permission there's no *License Management* option present.
Interceptor improved to block action just after we start getting 'expired_cloudify_license' or 'missing_cloudify_license' error codes from Cloudify Manager REST API.

(work-in-progress) CY-1137 - Allow non-admin users to see license and block license upload & CY-1147 - Update error handling after API changes

---

backend/migration.js

After swithing from log4js to winston, this log call has been updated
from `console.log` to `logger.log`, however the arguments are slightly
different with winston.

migration.js: use `logger.info`

---

backend/migrations/20190401111659-5_0-MovePageResourcesToFiles.js
backend/migrations/20190401130022-5_0-MoveTemplatesResourcesToFiles.js

If bulkInsert is called with an empty records array, it will
emit invalid SQL, eg. `INSERT INTO Resources () VALUES ;`, which leads
to a sql syntax error. Instead, let's not emit the insert at all, if
there's nothing to insert

Migrations: don't attempt to bulkInsert nothing

---

widgets/executions/src/widget.js

Updated Executions widget not to calculate blueprint ID for update workflows as it is now done on backend side.

CY-1539 - On deployment update UI shows blueprints in a wrong way

---

.eslintrc
app/components/status/SystemServicesStatus.js
backend/handler/services/ManagerService.js
test/cypress/fixtures/cluster_status/degraded.json
test/cypress/fixtures/cluster_status/fail.json
test/cypress/fixtures/cluster_status/ok.json
test/cypress/fixtures/license/valid_spire_license.yaml
test/cypress/fixtures/spire_deployments/3_deployments.json
test/cypress/integration/cluster_status_spec.js
test/cypress/integration/sites_spec.js
test/cypress/integration/spire_manager_spec.js
test/cypress/plugins/index.js
test/cypress/support/cluster_status_commons.js
test/cypress/support/index.js
test/nightwatch/tests/systemStatus.js
widgets/managers/src/backend.js
widgets/managers/src/widget.js

- Improved WidgetBackend Manager Service to allow getting all data (doGetFull method)
- Fixed SystemServicesStatus to be clickable
- Moved spire deployments fetching to widget backend
- Added system tests for:
- CY-1527 - Create Spire Manager widget (formerly Cloudify MoM widget)
- CY-1599 - Cluster status widget
- CY-1514 - UI - Manager service status replaced with Cluster service status

CY-1527 & CY-1599 & CY-1514 - Cluster Status in UI - tests and improvements

---

app/components/basic/cluster/NodeStatus.js
package-lock.json
package.json
test/cypress/integration/cluster_status_spec.js
test/cypress/support/cluster_status_commons.js

The same PR as #915 , but for `next` branch.
* Fixed failed node status in Cluster Status widget
* Added system test for Cluster Status widget - node status details check
* Updated cloudify-blueprint-topology link

CY-2277 - In Cluster Status widget node status details are not shown when node status is Fail (for next branch)

---

backend/package-lock.json
backend/package.json
package.json
scripts/createPackage.sh

* Sorted package.json files (used: https://www.npmjs.com/package/sort-package-json )
* Improved createPackage.sh script
I tried to simplify packaging by moving from `createPackage.sh` script into simple `npm pack` command, but found out that it is not working with symlinks. So `backend/node_modules/.bin` folder necessary to run npm scripts was not included in the package, although it was specified explicilty in the `files` field in package.json.

CY-2522 - Update cloudify-stage deploy procedure to contain package.json reflecting actual dependencies

---

package-lock.json
package.json

Recent upgrade of `mocha-junit-reporter` caused a problem in Jenkins which stopped showing test results properly. This PR is to fix that.

Fixed JUnit reporter configuration for Cypress tests in Jenkins

---

widgets/common/src/NodeInstancesConsts.js
widgets/deployments/src/DeploymentsSegment.js
widgets/deployments/src/ExecutionProgress.js

Colors:
- green - finished execution
- yellow - execution in progress
- red - failed execution
Limitations:
- works only with `install` and `uninstall` workflows

CY-2464 - Added execution progress bar to the Deployments widget

---

app/actions/page.js
app/actions/types.js
app/components/Page.js
app/components/PageContent.css
app/components/PageContent.js
app/components/PagesList.js
app/components/WidgetsList.js
app/components/templates/PageManagement.js
app/containers/Page.js
app/reducers/pageReducer.js
package-lock.json
package.json

NOTE 1: No system tests. Some time ago I spent quite a lot of time trying to cover stencils drag'n'drop with cypress tests (in composer) and I failed. Since tabs reordering is not a crucial functionality I'd leave it without tests for now.
NOTE 2: I'm aware that `PageList.js` and `CreateTemplateModal.js` already implement reordering, but they are using a jquery based solution that I didn't want to copy, thus I decided to use a pure react solution. I assume `PageList.js` and `CreateTemplateModal.js` should be refactored at some point in the future to move away from jquery and consistently use the same solution as `PageContent.js` does.

CY-2958 Added support for changing tabs order

---

templates/pages/catalog-community.json
templates/pages/catalog.json
tours/main-sys_admin.json
widgets/blueprintCatalog/src/RepositoryCatalog.js
widgets/blueprintCatalog/src/RepositoryList.js
widgets/blueprintCatalog/src/RepositoryTable.js
widgets/blueprintCatalog/src/UploadModal.js
widgets/blueprintCatalog/src/actions.js
widgets/blueprintCatalog/src/widget.js

Implemented:
* CY-2873 - Update Blueprints Catalog widget to be displayed by default as a table (#990, #992)
* CY-2870 - Add default blueprint YAML file handling in Blueprints Catalog widget (#991)
* Switched Blueprints Catalog to use stage backend to fetch examples instead of directly fetching from browser

CY-3091 - Port Blueprints Catalog improvements to 5.0.5

---

app/utils/stageUtils.js
test/cypress/integration/widgets/executions_spec.js
widgets/executions/src/backend.js
widgets/executions/src/tasksGraph/ExecutionWorkflowGraph.js
widgets/executions/src/tasksGraph/GraphNode.js
widgets/executions/widget.css

- Fixed fetching tasks graph (fetching is not stopped on tasks graph not present as it was before)
- Improved backend part of tasks graph poller (it fails quickly right now without trying to fetch not existing data)
- Improved fetching tasks graph (now we fetch tasks graph with interval depending on execution status - for active executions we poll data every 3 seconds, for inactive executions we poll data every 6 seconds)
- Updated layout for single execution view (to include status no matter if the graph is present)
- Reviewed and updated tests
- Fixed `makeCancelable` function to allow proper handling of failed promises
- Fixed GraphNode prop types
- Improved logging in backend part of tasks graph poller (using internal logger instead of console calls)

CY-3169 - Execution task graph - no-task graph error

---

widgets/common/src/WorkflowsMenu.js
widgets/deployments/src/MenuAction.js

* Added Install and Uninstall options to Deployments widget action menu
* Marked Default workflows as bold in workflows menu
* Deployments widget - action menu
* Deployment with grouped workflows
* Deployment with only default workflows
* Deployment Action Buttons widget - Execute workflow button
* Deployment with grouped workflows
* Deployment with only default workflows

CY-3130 - Execute workflows menu improvements

---

app/utils/External.js

The issue with Resource Filter widget test started occurring after implementation of **CY-3420 Make DELETEs return 204** within this PR: https://github.com/cloudify-cosmo/cloudify-premium/pull/682 .
The direct reason for failure was rejected promise (blueprint DELETE request) which caused stop of the promise chain and no trigger for refreshing Resource Filter widget.

CY-3558 - Fix handling HTTP 204 No Content responses

---

app/components/shared/cluster/ClusterServicesList.jsx
app/components/shared/cluster/NodeServices.jsx
test/cypress/fixtures/cluster_status/degraded.json
test/cypress/fixtures/cluster_status/fail.json
test/cypress/fixtures/cluster_status/fail_with_services.json
test/cypress/fixtures/cluster_status/ok.json

* Removed ID popup from Cluster Status widget (CY-3693)
* Removed `is_remote` from Cluster Status widget code (CY-3703)

CY-3693 & CY-3703 - Cluster Status widget update after cluster-status endpoint response changes

---

backend/package-lock.json
backend/package.json
package-lock.json
package.json

Package versions were not semver compliant.
Cherry pick of https://github.com/cloudify-cosmo/cloudify-stage/pull/1170 to 5.1.2

RD-1070 [5.1.2] Fix package versions

---

app/translations/en.json
widgets/common/src/DeploymentActions.js
widgets/common/src/ManageLabelsModal.jsx
widgets/common/src/labels/common.js

https://user-images.githubusercontent.com/5202105/106861440-0cd86c80-66c6-11eb-90fa-a1f2f4ba799b.mp4
Added new component available through `Stage.Common`. It is not used anywhere yet. Manage labels button was created just for testing and video recording. Deployment labels fetch is done when modal gets opened. On Apply button click, deployment labels are updated according to changes user did. I'm planning to add Cypress tests in the next tasks when it would be accessible from the widgets.

RD-752 - Add Manage Labels modal

---

widgets/topology/src/widget.jsx

This fix addresses both issues reported in the ticket.
Recursive `_.merge` was used where what we actually need is a shallow merge.

RD-877 Fix for non-tree component graphs

---

test/cypress/integration/widgets/blueprints_spec.js
widgets/common/src/DynamicDropdown.jsx

With https://github.com/cloudify-cosmo/cloudify-stage/pull/1157 I added `useEffect` for `fetchUrl` prop change. It was calling `loadMore()` method. This method is changing page (offset) and was designed to handle scrolling down in the dropdown to load more data. That resulted in problems in displaying list of options in dropdowns using DynamicDropdown component. Removing it for now as we don't need it, yet (Labels in UI feature is not going to be release in 5.2). 
It will be revisited how to handle changing `fetchUrl` within [RD-1271](https://cloudifysource.atlassian.net/browse/RD-1217).
This fix solves issues in the following specs:
1. widgets/filter_spec.js
2. widgets/blueprint_actions_spec.js
3. widgets/blueprint_info_spec.js
4. widgets/blueprint_sources_spec.js
5. …

RD-1335 RD-1356 (master) Fix data fetching issues in DynamicDropdown component and in system tests

---

scripts/uploadPackage.sh

It solves the issue with `sites_spec` and `sites_map_spec`.
See: https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/150:
```
[2021-02-09T11:21:30.070Z]        Spec                                              Tests  Passing  Failing  Pending  Skipped  
[2021-02-09T11:21:30.070Z]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
[2021-02-09T11:21:30.070Z]   │ ✔  widgets/sites_map_spec.js                00:10        3        3        -        -        - │
[2021-02-09T11:21:30.070Z]   ├────────────────────────────────────────────────────────────────────────────────────────────────┤
[2021-02-09T11:21:30.071Z]   │ ✔  widgets/sites_spec.js                    00:20       12       12        - …
```

RD-1358 - Prevent overriding app.json when uploading stage package

---

widgets/common/src/ManageLabelsModal.jsx

The most recent failures in UI system tests - Deployments widget test suite - was due to an issue in `ManageLabelsModal` component.
The following error was presented in the browser console:
```
VM6267 nonIterableSpread.js:2 Uncaught TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
at _nonIterableSpread (VM3753 nonIterableSpread.js:2)
at _toConsumableArray (VM3748 toConsumableArray.js:10)
at Object.onApply [as onClick] (ManageLabelsModal.jsx?2976:43)
at apply (_apply.js?798f:15)
at baseInvoke (_baseInvoke.js?a8a3:21)
at apply (_apply.js?798f:16)
at eval (_overRest.js?f40b:32)
at Button._this.handleClick (Button.js?5945:63)
at HTMLUnknownElement.callCallback (react-dom.development.js?e444:336)
at …
```

RD-754 - Fix setting deploymentLabels passed to DeploymentActions.doSetLabels function

---

test/cypress/integration/widgets/deployment_button_spec.js

https://github.com/cloudify-cosmo/cloudify-manager/pull/2766 changed the following:
1. Reverted constraint validation in deployment API
2. Introduced a small change in the error message for the constraint validation. 
This PR adjusts our test code for the second change.
Error message is now prefixed with `dsl_parser.exceptions.ConstraintException:`:
I think we can keep that prefix. I don't think that cutting it on the UI side is good idea.
Our Stage System Tests should all pass after this PR is merged.

RD-1648 - Update deployment's test case after changes in the REST API

---

widgets/agents/src/widget.jsx

According to the description provided in the https://cloudifysource.atlassian.net/browse/CY-3642 comment I just added a query parameter to `GET /agents` request. The solution is aligned with CLI's `cfy agents list` command right now.
Unfortunately `state` field is not present in the response, so I don't see any reasonable way of testing it. 
I'm not familiar with setting up environment which provides different agents, so I asked issue reported. He promised to set up something today, so I'm going to do manual tests there.
This video shows that `state=started` is added to the URL:
https://user-images.githubusercontent.com/5202105/111127599-4c6f5f80-8574-11eb-86d3-f0c40aad222d.mp4

CY-3642 - Filter agents list by agent state

---

backend/routes/ServerProxy.js

This PR provide fix for the most important issue reported within RD-795 - fixes stage-backend crashes by preventing sending headers from `ServerProxy` route when they already have been sent. This happens when e.g. timeout occurs after download has started. Timeout can occur when there is no response from the server (no more bytes sent) during 10 seconds period of time (that is default setting for GET request we have right now).

RD-795 - Fix for stage-backend crash upon downloading huge files

---

package-lock.json
package.json
test/cypress/fixtures/babel.config.js
test/cypress/fixtures/widgets/fibonacciSequenceWidget.tsx
test/cypress/fixtures/widgets/splitViewWidget.tsx
test/cypress/integration/widgets/user_defined_widgets_spec.ts
test/cypress/support/commands.ts
test/cypress/support/widgets.ts

This PR builds upon https://github.com/cloudify-cosmo/cloudify-stage/pull/1238 and adds the tests that verify rendering nested widgets.
The tests verify that:
1. Rendering nested widgets works
2. Nested widgets can make API requests, have their own data, etc (_Plugins Catalog_ fetches and displays the list of plugins)
3. Widgets can pass configuration to nested widgets
Additional checks I have done by hand:
1. Showing nested widget's readme works
2. Interacting with the nested widget works (I wanted to install some plugin using _Plugins Catalog_)
https://user-images.githubusercontent.com/889383/110922882-8ba57280-8320-11eb-8f44-768c22a229b2.mp4
1. Widgets can be rendered inside other widgets, thanks to components exposed in https://github.com/cloudify-cosmo/cloudify-stage/pull/1238
2. …

RD-1591 Add tests for rendering widgets recursively

---

widgets/common/src/UploadBlueprintModal.jsx

This is a fix for a change done within https://github.com/cloudify-cosmo/cloudify-stage/pull/1248
Getting `t` function the following way:
```
const {
i18n: { t }
} = Stage
```
does not work (JS errors) and make our UI unusable (e.g. Blueprints widget does not work), so I reverted it.

RD-1750 - Fix UploadBlueprintModal

---

test/cypress/integration/widgets/sites_spec.js

The selectors were too strict and required the cells to have a specific structure. Introducing an additional `div` in the cell broke the `td > span` selector. `td span` works just fine :slightly_smiling_face: 
You might notice quite a large commit when reviewing by commits. That's because I tried to refactor the verification logic to avoid repetition, but it looks like there were not enough waiting/verification I could do to make it work. I decided to revert it and do a simple, dirty, but working fix instead
https://jenkins.cloudify.co/job/Stage-UI-System-Test/293/

RD-1753 Fix Sites widget tests

---

app/typings/stage-api.d.ts
package.json
test/cypress/fixtures/deployments/various-statuses.json
test/cypress/integration/widgets/deployments_view_spec.ts
test/cypress/support/commands.ts
test/cypress/support/sites.ts
webpack.config.js
widgets/deploymentsView/src/widget.tsx

The PR adds a few basic tests for the Deployments View widget.
Don't be afraid by the number of lines added :smile: Most of them come from the test fixture for deployments
All passed locally:
1. Migrate the sites commands to TypeScript
Sites commands are used in the new test suite.
2. Basic tests:
1. The created deployment is displayed in the table
2. Hiding and showing columns (`fieldsToShow` in the widget configuration) is working correctly
3. The deployment status icon is displayed correctly and has a popup
I have tried to make the tests rely on accessible properties (`aria-label`, `role`, text), rather than classes. I think I managed to do that well, except for a few cases :slightly_smiling_face: 
The added fixture will make it easier to test functionalities such as displaying the …

RD-1751 Add basic tests for Deployments View widget

---

app/translations/en.json
test/cypress/integration/widgets/deployment_actions_spec.js

Tested locally. All green in `test/cypress/integration/widgets/deployment_actions_spec.js`.

RD-1803 - Fix Deployment Action Buttons widget test

---

backend/routes/Auth.js
backend/test/routes/Auth.test.js

This PR adds security-related attributes to all cookies we create inside Stage app:
* `SameSite=Strict`
* `Secure` if Cloudify is in SSL mode. On the frontend side we check that using `X-Scheme` header.
NOTE: `X-Scheme` header is only available in production environment (with nginx web server). 
More about SSL mode in Cloudify: https://docs.cloudify.co/latest/install_maintain/manager_architecture/security/#ssl-mode-for-external-communication.
Cookies in SSL mode with Okta authentication enabled:
TODO:

RD-916 - Add security attributes to all used cookies

---

app/translations/en.json
test/cypress/fixtures/deployments/various-statuses.json
test/cypress/integration/widgets/deployments_view_spec.ts
widgets/deploymentsView/src/columns.tsx
widgets/deploymentsView/src/widget.tsx

This PR adds support for showing data in the Environment Type column in the Deployments View.
I hope the commit log gives enough guidance about the changes :slightly_smiling_face: 
One unrelated change was fixing the way the "Status" column was presented in the widget's configuration modal (it was empty).
The functionality is covered by a Cypress test. So far, the backend does not return the `environment_type` property, so it's tested only using the mocked fixture.
https://jenkins.cloudify.co/job/Stage-UI-System-Test/301/
Ran 2021-03-19 16:50 CET

RD-1786 Show Environment Type column

---

app/components/WidgetDynamicContent.jsx
app/translations/en.json
widgets/deploymentsView/src/columns.tsx
widgets/deploymentsView/src/renderDeploymentRow.tsx
widgets/deploymentsView/src/styles.scss
widgets/deploymentsView/src/widget.tsx

This PR is a base for #1267  and includes standalone changes that I have separated out to make the code review a bit easier.
Notable changes:
1. Add `searchable`, `noDataMessage`, and `sortable` to the table
2. Refactor the way class names are combined in `WidgetDynamicContext` (non-breaking change, and will be useful in future PRs to combine 1 more class)
https://user-images.githubusercontent.com/889383/112164892-8e407b80-8bee-11eb-85be-a084f35b65e7.mp4
I will run system tests for #1267, which builds upon this one, to avoid having to run system tests for a linear path of branches

RD-1743 Use existing table features in Deployments View table

---

test/cypress/integration/widgets/deployment_actions_spec.js

This is a simple change to make `deployment_actions_spec` more robust by:
* waiting for "labels existence check" request to be send
* waiting for the label to be added to the labels list
before starting the next actions.
In my local environment test is passing. CI (only deployment_actions_spec) results will be here: https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/330
See RD-1835 for more details.

RD-1835 - Improve deployment_actions_spec to be more robust

---

app/components/Tabs.jsx
app/components/shared/widgets/PageContent.jsx
app/components/shared/widgets/Widget.tsx
app/components/shared/widgets/WidgetsList.tsx
test/cypress/integration/widgets/deployments_view_spec.ts
widgets/deploymentsView/src/detailsPane/widgets.tsx

This PR hides useless maximization buttons for nested widgets. It uses the fact that `onWidgetUpdated` would not do anything for nested widgets, so instead of passing `noop`, I changed it to pass `undefined`. This avoids having a new prop that determines whether maximization buttons should be shown or not.
The maximization button is only shown for the top-level widget.
This PR builds on #1267 
https://jenkins.cloudify.co/job/Stage-UI-System-Test/333/
Ran 2021-03-25 15:11 CET

RD-1819 Hide maximization buttons for nested widgets

---

test/cypress/integration/widgets/deployment_actions_spec.js
test/cypress/integration/widgets/deployments_view_spec.ts
widgets/common/src/ExecuteDeploymentModal.jsx

This PR fixes the selection of deployments in the Deployments View widget. It builds on #1267.
Previously, the selection was set to `null` after executing a workflow. This happened because:
1. The `deployments:refresh` event was triggered without any arguments
2. The Resource Filter widget was listening on that event and when it fired, it set the `deploymentId` to whatever was the argument of the event
https://github.com/cloudify-cosmo/cloudify-stage/blob/6514122edaad401b6b0592c770a287b95f206844/widgets/filter/src/Filter.jsx#L79-L85
Since the argument was `undefined`, `deploymentId` in that function was set to the default `null` value.
Adding the `deploymentId` preserves the selection when executing workflows.
The problem only happens when the Resource Filter widget is present on the same …

RD-1822 Keep deployment selection after executing workflows

---

app/utils/StageAPI.ts
app/utils/widgetDefinitionsLoader.ts

Added `styled` to `Stage` global.
Works fine:

RD-1859 - Expose styled-components through Stage global

---

package-lock.json
package.json

Changes:
* Update cloudify-ui-common version 
* Auto-fixed audit issues with `npm audit fix`

RD-1897 - Update cloudify-ui-common to have Cypress configuration ready for using Cloudify Manager in SSL mode

---

app/components/shared/widgets/WidgetsList.tsx
test/cypress/integration/widgets/deployments_view_spec.ts
test/cypress/support/commands.ts
test/cypress/support/filters.ts
widgets/deploymentsView/src/widget.tsx

This PR adds handling filters in Deployments View in a very basic way:
* filter rules are fetched every time before fetching the deployments
* there is no caching of filter rules. That will come in RD-1852 or RD-1854 (I'm thinking about using [react-query](https://react-query.tanstack.com/overview) instead of writing the logic for polling and aborting requests myself)
The tests need to create filters to be used for the test, so I added necessary commands that facilitate that too.
https://user-images.githubusercontent.com/889383/112830684-2927d280-9093-11eb-9f19-f1bdd3a68cc4.mp4
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/357/pipeline
Ran 2021-03-30 15:23 CEST

RD-1142 Respect filters in Deployments View

---

app/components/GettingStartedModal/localStorage.ts

This PR prevents the Getting Started modal from obstructing the view in all the tests.
I want to make it a hotfix to get the tests on master to pass, so we can merge anything. If you have better ideas how to fix it properly (I would encourage thinking about it), please do that in a separate ticket after we get this one merged :slightly_smiling_face: 
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/368/pipeline

RD-1942 Disable Getting Started modal in all Cypress tests

---

.nycrc
test/cypress/integration/widgets/deployment_button_spec.js
test/cypress/integration/widgets/deployments_spec.js
test/cypress/integration/widgets/deployments_view_spec.ts
test/cypress/support/resource_urls.ts

GitHub URL structure for accessing the artifacts of the latest release changed. It has to be reflected in the URLs used in tests.
https://jenkins.cloudify.co/job/Stage-UI-System-Test/377/

RD-1949 Fix paths to GitHub blueprint artifacts in system tests

---

app/utils/shared/ExecutionUtils.js
test/cypress/fixtures/deployments/various-statuses.json
widgets/deploymentsView/src/table/columns.tsx
widgets/deploymentsView/src/table/renderDeploymentRow.tsx
widgets/deploymentsView/src/types.ts

The recently-added environments-related deployment properties are now present in the API responses, so we can safely use them, thus, they no longer need to be optional (RD-1839)
The latest execution progress properties were prefixed with `latest_execution_`, so they had to be renamed in the fixture and the code (RD-1840)
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/406/pipeline
Ran 2021-04-07 13:22 CEST

RD-1839 RD-1840 Use renamed and stable properties

---

app/actions/drilldownPage.js
app/actions/page.ts
app/app.jsx
app/components/Breadcrumbs.jsx
app/components/Home.jsx
app/components/Page.tsx
app/translations/en.json
app/typings/stage-api.d.ts
app/utils/StageAPI.ts
backend/package.json
test/jest/reducers/pagesReducer.test.js
widgets/deploymentsView/src/widget.tsx

This PR adds filtering by parent deployment in the Deployments View widget. It covers RD-1853
Some of the changes to the core of the application result from the fact that `drilldownContext` only contained entries for each drill-down page, but not the topmost page. This would make it impossible to filter by the deployment selected on the topmost Environments/Services page because the selected deployment would be gone. Now, all pages, no matter if drilled-down, or top-level, are present in the `drilldownContext` array in the store.
As a side effect, when going back to some predecessor page by clicking the breadcrumbs, the context is now restored. If you set some configuration option on the top-level page (e.g. set a filter), drill down, and go back to that top-level page, the filter will be …

RD-1853 Filter by parent deployment in Deployments View

---

.prettierrc.js
app/translations/en.json
app/utils/StageAPI.ts
templates/pages/drilldownDeployments.json
test/cypress/integration/templates/template_management_spec.js
test/cypress/integration/widgets/deployments_view_spec.ts
test/cypress/support/commands.ts
test/cypress/support/deployments.ts
widgets/deploymentsView/src/common.ts
widgets/deploymentsView/src/detailsPane/DrilldownButtons.tsx
widgets/deploymentsView/src/detailsPane/header.tsx
widgets/deploymentsView/src/detailsPane/index.tsx
widgets/deploymentsView/src/table/columns.tsx
widgets/deploymentsView/src/widget.tsx

This PRs is adding support for the basic drill-down functionalities in the Deployments View widget.
This is a partial implementation. The drill-down functionality itself is working, but there is still work to be done to get it working correctly and according to the designs. Take a look at the subtasks for RD-1226 for a list of upcoming tasks.
https://user-images.githubusercontent.com/889383/114018951-1f118b00-986e-11eb-894c-ca56f6be45e4.mp4
The structure of the deployments in the video is the same as in the tests:
```
//                app-env
//                  - -
//                -/   \-
//               /       \-
//             -/          \-
//            /              \
//         db-env           web-app
//          ---
//        -/   \-
//      -/       \
//   db-1        db-2 …
```

RD-2001 Add core drill-down functionality to Deployments View

---

package-lock.json
package.json
test/cypress/integration/widgets/filters_spec.ts
test/cypress/support/commands.ts
test/cypress/support/filters.ts
widgets/filters/src/FilterEditModal.tsx

This PR includes `FilterEditModalProps` type fix as a follow-up to previous PR review.
This PR adds `cypress-get-table` cypress extension which makes table content validations easier. It's not perfect but it's extremely easy to use - it abstracts table structure by allowing to reference table cells by row number and column header. As such it encourages better, more thorough table content checking.
System tests run is queued (build 416).

RD-1123 Added cypress test for filters management widget

---

app/translations/en.json
backend/test/handlers/WidgetHandler.test.js
templates/pages/drilldownDeployments.json
test/cypress/integration/widgets/deployments_view_spec.ts
test/cypress/integration/widgets/filters_spec.ts
test/cypress/support/filters.ts
test/cypress/tsconfig.json
widgets/common/src/deploymentsView/DeploymentsView.tsx
widgets/common/src/deploymentsView/common.ts
widgets/common/src/deploymentsView/configuration.ts
widgets/common/src/deploymentsView/detailsPane/DrilldownButtons.tsx
widgets/common/src/deploymentsView/index.ts
widgets/common/src/deploymentsView/styles.scss
widgets/common/src/deploymentsView/types.ts
widgets/common/src/filters/index.ts
widgets/deploymentsView/src/widget.tsx
widgets/deploymentsViewDrilledDown/README.md
widgets/deploymentsViewDrilledDown/src/widget.tsx

The PR adds a new `deploymentsViewDrilledDown` widget that is rendered in the drilled-down pages of Environments. The changes should be transparent to the user - there are no functional changes. The new widget is very similar to the existing widget, but:
1. Has limited configuration
2. Always filters by parent deployment
3. Does not fetch filter rules (they will come from the context in RD-2004)
Despite having a large number of changes on paper, most of the code for `widgets/common/src/deploymentsView/DeploymentsView.tsx` comes from the preexisting widget code. You may want to use [the git's `--color-moved` config](https://github.blog/2018-04-05-git-217-released/#coloring-moved-code) to reduce the diff and show which lines were moved as-is :smile: I'd say around 200 lines were moved, and …

RD-2002 Add drilled-down Deployments View widget

---

app/translations/en.json
test/cypress/integration/widgets/deployments_view_spec.ts
widgets/common/src/deploymentsView/detailsPane/DrilldownButtons.tsx
widgets/common/src/deploymentsView/detailsPane/index.tsx

Show the correct numbers in the drill-down buttons in Deployments View.
Notice that the number of subservices in the drill-down button is 1, meaning that it correctly counts only the immediate children. The table still shows 3 subservices, as it counts all ancestors.
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/449/pipeline
Ran 2021-04-13 15:57 CEST

RD-2003 Display the number of only immediate subdeployments

---

test/cypress/integration/widgets/deployments_view_spec.ts
test/jest/tsconfig.json
test/jest/widgets/common/DeploymentActions.test.ts
widgets/common/src/DeploymentActions.ts
widgets/common/src/DeploymentActionsModals.tsx
widgets/common/src/ExecutionActions.ts
widgets/common/src/RemoveDeploymentModal.tsx
widgets/common/src/deploymentsView/detailsPane/header.tsx
widgets/common/src/props/Labels.ts
widgets/deploymentActionButtons/src/DeploymentActionButtons.tsx
widgets/deploymentActionButtons/src/widget.jsx
widgets/deploymentActionButtons/src/widget.tsx

Deleting a deployment in the Deployments View widget no longer triggers a redirect to the parent page.
The behavior is changed only when the _Deployment action buttons_ are displayed in the Deployments View widget. I have confirmed that redirecting to the parent page still happens when deleting a deployment from the drilled-down view of the old Deployments widget :slightly_smiling_face: (where it makes sense)
One caveat with deleting deployments is that the deployment is still present in the LIST request that follows the delete request. This is because the backend responds to the DELETE request and then deletes the deployment in the background, asynchronously, so the user will still see the deployment being deleted. The test still passes, since the deployment is gone with the next polling …

RD-1824 Prevent going to parent page on deployment delete

---

app/translations/en.json
test/cypress/integration/widgets/deployments_view_spec.ts
widgets/common/src/deploymentsView/DeploymentsView.tsx
widgets/common/src/deploymentsView/configuration.ts
widgets/common/src/deploymentsView/detailsPane/header.scss
widgets/common/src/deploymentsView/header.tsx
widgets/common/src/deploymentsView/layout.ts
widgets/common/src/deploymentsView/styles.scss
widgets/common/src/deploymentsView/table/DeploymentsTable.tsx

The purpose of the PR is to prepare the structure for the Deployments Map in the Deployments View widget. The actual map will be implemented in RD-2090
1. Change the scrollbar behavior in the Deployments View widget
Each "component" (details, table, map) has its own area in a grid. Details and table have their own scrollbars
2. Add a button to toggle the map
3. Add map widget configuration
4. Add tests for the added functionalities'
https://user-images.githubusercontent.com/889383/115364630-dfc73080-a1c3-11eb-92e1-f3a193c523fe.mp4
https://jenkins.cloudify.co/job/Stage-UI-System-Test/475/
Ran 2021-04-20 10:31 CEST

RD-2089 Add deployments map placeholder

---

widgets/common/src/DeploymentActions.ts

This PR fixes failing widgets/agents_spec.ts tests because of missing default value in deployment actions.
Ticket: https://cloudifysource.atlassian.net/browse/RD-2261-widgets_agents_spec_ts%20-tests-fail-because-of-some-element-covers-other-one
System tests passes: https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/552/

RD-2261 - fix for missing default parameter in doExecute method in deployment actions

---

.size-limit
backend/package-lock.json
backend/package.json
package-lock.json
package.json

* Bumped versions of `cloudify-*` packages to the latest available in frontend part
* Bumped `cloudify-ui-common` package version in backend part
Requires: https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1821

RD-2267 - Fix npm audit security issues

---

app/components/GettingStartedModal/ModalContent.tsx
app/components/GettingStartedModal/steps/SummaryStep/SummaryStep.tsx

The main goal of this PR is to make the installation/upload progress bar always visible - even the list of items is higher than modal height.
Ticket: https://cloudifysource.atlassian.net/browse/RD-2252
Build (system tests passed): https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/575/
Scrollable 'Task List' list:

RD-2252 - The getting started progress bar should be always visible

---

widgets/common/src/RemoveDeploymentModal.tsx

Added proper style to RemoveDeploymentModal to display long deployment names inside the modal content. 
This is more like general issue in the whole application, so there's RD-2255 to handle it properly in the future.

WDR-19 - Fix deployment name surpassing the Remove Deployment modal

---

test/cypress/integration/widgets/deployments_view_spec.ts

This PR builds on top of #1369 and adds a system test that verifies some of the functionalities implemented in #1369:
1. Nearby markers are clustered
2. Clicking the cluster zooms on and breaks the cluster
3. The currently selected deployment is not clustered
Functionalities not tested:
1. Cluster marker icon color (the fact that it's based on the worst deployment state)
The problem is that there are many cases to test here (2 deployments, 3 states = 6 possible states) and each requires a different fixture/dynamically changing the deployment status and then refreshing the page.
It would be better tested by unit tests/integration tests for the component IMO which would not have the overhead of refreshing the whole page for each state. …

RD-1527 Tests for Deployments Map marker clustering

---

.size-limit
app/utils/StageAPI.ts
test/cypress/integration/widgets/deployments_view_spec.ts
widgets/common/src/deploymentsView/configuration.ts
widgets/common/src/deploymentsView/detailsPane/DrilldownButtons.tsx
widgets/common/src/deploymentsView/detailsPane/header.tsx
widgets/common/src/deploymentsView/detailsPane/index.tsx

The PR adds polling (`refreshInterval`) to drill-down buttons in the Deployments View widget. Fixes https://cloudifysource.atlassian.net/browse/WDR-21
I have also taken the chance to improve the margins in the details pane's header.
https://user-images.githubusercontent.com/889383/118489841-96fc8c00-b71d-11eb-9089-b2444aa1fa7d.mp4
Notice that there's a loading overlay for the drill-down buttons now. Also, notice that there's a gap between the drill-down buttons and the deployment action buttons (they were right next to each other previously, without any vertical space).
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/605/pipeline
Queued 2021-05-17 14:37 CEST

WDR-21 Add polling to drill-down buttons

---

test/jest/widgets/common/map/site.test.ts
widgets/common/src/map/site.ts

Do not allow `NaN` or `Infinity` (which are of type `number`).
This PR aims to be a hotfix, because the root cause is still unknown to me. As I have followed the source code, we do the following operations:
1. Filter out sites that have `latitude` and `longitude`
2. Match deployments with those sites
I don't see any other operation that would make latitude or longitude be a `NaN`.
If, after merging this PR, Ofer and Gabriel will not have satisfactory results in the UI, I will have to investigate using their managers, as I could not reproduce the problem locally.
https://jenkins.cloudify.co/job/Stage-UI-System-Test/606/
Queued 2021-05-17 20:31 CEST

WDR-31 Prevent using invalid site latitudes and longitudes

---

widgets/common/src/deploymentsView/DeploymentsView.tsx

Fix the default sorting in the Deployments View widget. It was not consumed due to using `react-query` and not widget's `fetchData` and `[params]` in the URL.
This fixes https://cloudifysource.atlassian.net/browse/WDR-37
Here is the default view after opening the widget:
Changing the sort order still works:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/626/pipeline
Queued 2021-05-19 17:30 CEST

WDR-37 Sort deployments by created_at by default

---

app/translations/en.json
widgets/executions/src/widget.jsx

When the deployment was being deleted, the component crashed and did not recover when changing the selected deployment. Having an explicit error check prevents the widget from crashing.
https://user-images.githubusercontent.com/889383/118945695-fb099500-b955-11eb-8d42-f6611d9b6012.mp4
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/628/pipeline
Queued 2021-05-20 17:52 CEST

RD-2372 Prevent Execution Task Graph crashing when no deployment

---

test/cypress/integration/cluster_status_spec.js
test/cypress/integration/login_spec.js
test/cypress/integration/widgets/sites_map_spec.js
test/cypress/support/commands.ts
widgets/sitesMap/src/SiteControl.tsx
widgets/sitesMap/src/SitesMap.tsx
widgets/sitesMap/src/groupStates.ts

As we removed/changed recently some of the pages from the layout Sites Map redirection (on clicking the deployment status in the site marker tooltip) stopped working. This PR fixes that.
Within that PR I also did two small alignments to Deployments View widget:
* Changed "Good" site marker color (from green to blue)
* Changed "Failed" deployment status name (from “Failed” to “Requires attention”)
As some of the pages were removed I also updated `usePageMock` function.
Full system test run: https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/651/

RD-2440 Fix page redirection on clicking site marker tooltip

---

app/utils/External.ts

As part of #1402 I removed `headers` parameter from doX methods. Even though this parameter is not used in our code base my understanding is that it should actually stay as it may be used by customers.
I'm not planning system tests execution for this PR.

RD-1075 Brought back removed headers parameter

---

package-lock.json
package.json
test/cypress/support/blueprints.ts
test/cypress/support/commands.ts

Upgrade TypeScript to the latest version (4.3.2) and address TypeScript errors that ensued from supposedly circular references in the types.
1. Cold cache compilation improved from 30.72s to 25.56s (17%)
2. Other results look to be within measurement error margin
See https://docs.google.com/spreadsheets/d/1rMQYPDzRhN44GER2TXPcvnBBszUUodZNK-w11IS4jAE/edit#gid=0 for more data
Looks like the tsbuildinfo size actually decreased by almost 50%. Aside from that, looks like no changes in the rest of the output.
Name | tsc-dist size (MB) | tsbuildinfo size (kB)
-- | -- | --
TS 4.2.3 | 10.0 | 610
TS 4.3.2 | 9.7 | 316
When linting, you will see the following message from ESLint now:
<details>
```sh
13:26 $ npm run lint
> cloudify-stage@6.0.0 lint /home/grzegorz/projects/cloudify/cloudify-stage
> …
```

RD-1295 Upgrade TypeScript to 4.3.2

---

test/cypress/integration/widgets/agents_spec.ts

The tests are failing from time to time which makes the CI runs unreliable.
The tests and the widget should be revisited in RD-2589 and fixed, after which the tests can be enabled.
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/753/pipeline
Queued 2021-06-11 12:27 CEST

RD-2589 Disable flaky agents_spec tests

---

scripts/getTsMigrationProgress.sh
test/cypress/tsconfig.json
tsconfig.base.json

This PR disables importing JS files in TS files, which is some automation to prevent us from going back to JS :smile: 
Besides, I have added a script for calculating how many JS/TS/fully migrated TS files are there in the repo.
I have created https://docs.google.com/spreadsheets/d/1pDXaJHCUZWTYbhoHl9pc07VdRwre85Yx7OoRH9xtLzg/edit#gid=0 to track it over time.
The only changes are TS config, so if `npm run check-types` passes in Multibranch CI, the PR is good to go. There is no need for full tests.
Just to be sure, I'll run them on Monday, as the logs will probably be erased anyway over the weekend.

RD-2027 Finalize renaming files to TS

---

test/cypress/integration/widgets/topology_spec.ts

That test failed in https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/753/tests/ so according to our new rules, I am disabling it.
I have added RD-2600 to the next sprint.
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/754/pipeline
Queued 2021-06-11 13:46 CEST

RD-2600 Disable failing topology test

---

widgets/executions/src/tasksGraph/GraphNode.tsx

Fix the placement of the "Show related entities" icon of the task graph in the Executions widget.
On Safari and other webkit engines, the icon appeared to be positioned with respect to the root of the graph (the 0,0 position) instead of each graph node.
Adding `display: inline` to the icon fixes the problem and it is consistently positioned correctly across Chrome, Firefox, Epiphany (uses webkit on Ubuntu) browsers.
<details>
<summary>Chrome</summary>
</details>
<details>
<summary>Firefox</summary>
</details>
<details>
<summary>Epiphany browser (where the problem appeared before the PR)</summary>
Before:
After:
</details>
I don't see how it could break the system tests :smile: I have verified that the functionality is working by clicking on the icon manually. Thus, I do not plan to run …

RD-410 Fix "Show related entities" icon placement

---

package.json
widgets/common/src/ParameterValue.tsx
widgets/common/src/ParameterValueDescription.tsx

Fixed misalignment coming from parameter values, e.g. in this case:
https://user-images.githubusercontent.com/5202105/121895224-437f5d00-cd20-11eb-93f4-6c8e6cbfa760.mp4
See comments about additional small fixes.

RD-1072 Fix misalignment when displaying parameter values

---

app/components/GettingStartedModal/installation/process.ts
app/utils/External.ts
widgets/common/src/BlueprintActions.ts
widgets/common/src/DeploymentActions.ts
widgets/common/src/PluginActions.ts
widgets/common/src/SecretActions.ts
widgets/filters/src/FilterActions.ts
widgets/tenants/src/actions.ts
widgets/userGroups/src/actions.ts
widgets/userManagement/src/actions.ts

This is similar to #1412.
As part of #1402 I removed some options that could be used with `doPatch` method. Even though the removed options are not used in our code base they should actually stay as they may be used by customers as they are documented in API documentation.
System tests: https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/776/

RD-1075 Reverted set of options accepted by doPatch

---

test/cypress/integration/widgets/filters_spec.ts

Instead of waiting for the part which is generic, we are now waiting for the exact value in the dropdown option.
Filters spec passed locally two times in a row.
[Stage-UI-System-Test/797](https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/797/pipeline) (only Filters spec)
```
[2021-06-17T11:40:19.231Z]        Spec                                              Tests  Passing  Failing  Pending  Skipped  
[2021-06-17T11:40:19.231Z]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
[2021-06-17T11:40:19.231Z]   │ ✔  widgets/filters_spec.ts                  01:35       19       19        -        -        - │
[2021-06-17T11:40:19.231Z] …
```

RD-2626 Improve Filters spec to be more robust by more precise dropdown option selection

---

test/cypress/integration/widgets/agents_spec.ts
test/cypress/integration/widgets/deployment_button_spec.ts
test/cypress/integration/widgets/deployments_view_spec.ts
test/cypress/integration/widgets/maintenance_mode_button_spec.ts
test/cypress/support/commands.ts
test/cypress/support/executions.ts
widgets/agents/src/InstallAgentsModal.tsx
widgets/agents/src/ValidateAgentsModal.tsx
widgets/common/src/NodeFilter.tsx

1. Fixed two places related to Agents widget (see comments in the code).
2. Refactored `executions` Cypress commands
3. Refactored Install and Validate agents tests - I mocked all the necessary data as having a deployment with agent installed as AFAIR we would need to install a blueprint with access to the VM (know VM IP, upload an SSH key to the VM)
This PR does not fix issues listed in https://cloudifysource.atlassian.net/browse/RD-2589?focusedCommentId=72156 .
I discussed with @geokala yesterday my concerns about Agents widget and as for now we have kind of proposal how to change Agents widget. It seems like it would be reasonable to do a major change (remove `Install` and `Validate` buttons + Have `Validate` button available in the action column per each agent row). That needs to be …

RD-2589 Fix Agents widget tests

---

test/cypress/integration/widgets/deployments_view_spec.ts
widgets/common/src/deploymentsView/DeploymentsView.tsx
widgets/common/src/deploymentsView/detailsPane/index.tsx
widgets/common/src/deploymentsView/getSelectedDeployment.ts
widgets/common/src/deploymentsView/table/DeploymentsTable.tsx
widgets/common/src/deploymentsView/table/renderDeploymentRow.tsx

This PR implements the new way of interoperability between the Resource Filter and the Deployments View widgets.
The behavior is described in points listed in the following Jira comment: https://cloudifysource.atlassian.net/browse/RD-1829?focusedCommentId=72281. The logic is as follows:
1. If there is no deployment selected (not in Resource Filter or Deployments View), select the first deployment from the table in Deployments View
1.1. If there are no deployments (“No Results Found”), nothing is selected and there is only that information “No Results Found”. There is no warning now (the warning shown on https://user-images.githubusercontent.com/889383/122370093-1240a000-cf5f-11eb-98bb-e219ea25075d.png was unnecessary)
2. If the user selected a deployment in the Resource Filter widget (no …

RD-1829 Improve handling of incompatibilities between Resource Filter and Deployments View widgets

---

test/cypress/integration/widgets/deployments_view_spec.ts
test/cypress/support/commands.ts
widgets/common/src/deploymentsView/StatusIcon.tsx
widgets/common/src/deploymentsView/detailsPane/DrilldownButtons.tsx

This PR adds the subdeployment status icons to drill-down buttons in the Deployments View widget.
I have also added tests to verify the functionality.
When subdeplloyments require attention:
When subdeployments are good or there are no subdeployments, there is no icon:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/806/pipeline
Queued 2021-06-18 10:58 CEST

RD-2005 Add subdeployment status icons in drill-down buttons

---

widgets/filter/README.md

Add a note about incompatibility with the Deployments View widget.
The change to the docs is made in https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1880. I will wait for that PR to be merged before trying to merge this one (the CI won't let me do otherwise :smile: ).
Unfortunately, the link to the Deployments View widget is broken due to RD-2455 (already happens in the Deployments View widget).
I do not plan on running system tests, as it's an automated readme change that is validated in the multibranch pipeline :slightly_smiling_face:

RD-1829 Update Resource Filter's README

---

jenkins/Jenkinsfile

This is a copy of https://github.com/cloudify-cosmo/cloudify-stage/pull/1446 because I wanted to push more commits to it but I could not as the branch was already protected.
I will cherry-pick to 6.1.0 after this PR is merged
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/823/pipeline
Queued 2021-06-22 12:16 CEST

RD-2647 Switch UI development to 6.1

---

test/cypress/integration/change_password_spec.ts
test/cypress/integration/widgets/deployments_view_spec.ts
test/cypress/support/commands.ts

See https://cloudifysource.atlassian.net/browse/RD-2633?focusedCommentId=72312 for more information about the problem.
Long story short, when the `useDeploymentsView` function was executing for some test, the UI from the previous test is still displayed in the browser. When cypress sets up an intercept for the `/searches/deployments` before the page is refreshed (via `cy.visit`) in the new test, it may happen that due to polling, the UI from the previous test sends a request that is matched by Cypress. Because the browser unloads the UI and aborts the requests, the request never gets any response, which is what I believe caused the problems mentioned in RD-2633.
Now if there is a `/searches/deployments` request that happens before `/visit`, it will not be intercepted. I could not …

RD-2633 Allow setting up intercepts right before login

---

test/cypress/integration/widgets/deployments_view_spec.ts
test/cypress/support/deployments.ts
widgets/common/src/SearchActions.ts

This PR implements specifying the `_search_name` query param when fetching deployments in the Deployments View widget. I have also added a test to verify that it works correctly, as well as a few minor improvements to the tests for that widget.
In my test, I needed to distinguish between the deployment ID and the name. Hence, I modified the deployments view spec to handle the ID and the display name for the main deployment (that is used in most tests) separately.
I have made it so that all consumers of `SearchActions` will now benefit from searching by both ID and display name of deployments.
Some changes may look confusing when looking at the full diff. If that's the case, look at a commit-by-commit view. I hope that helps.
https://github.com/cloudify-cosmo/cloudify-manager/pull/3123 is …

RD-2516 Use search name in Deployments View

---

app/translations/en.json
test/cypress/integration/widgets/blueprint_actions_spec.ts
widgets/blueprintActionButtons/src/BlueprintActionButtons.tsx
widgets/blueprintActionButtons/src/widget.tsx

This PR hides the "Edit a copy in Composer" button by default in the Blueprint Action Buttons widget. It can be brought back by changing the configuration.
https://user-images.githubusercontent.com/889383/123640312-536b6680-d821-11eb-970f-c10363564dce.mp4
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/857/pipeline
Queued 2021-06-28 14:59 CEST

RD-2593 Hide "Edit a copy in Composer" button

---

app/translations/en.json
test/cypress/integration/widgets/blueprints_spec.ts
widgets/blueprints/src/BlueprintsCatalog.tsx
widgets/blueprints/src/BlueprintsTable.tsx
widgets/blueprints/src/types.ts
widgets/blueprints/src/widget.tsx

This PR adds a configuration flag to the Blueprints widget to hide the "Edit a copy in Composer" link.
https://user-images.githubusercontent.com/889383/123964809-20a5a780-d9b4-11eb-9dba-7e3ed2386b0f.mp4
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/870/pipeline
Queued 2021-06-30 15:01 CEST

RD-2593 Hide "Edit in Composer" in Blueprints widget

---

test/cypress/integration/widgets/nodes_spec.ts
widgets/nodes/src/NodesTable.tsx
widgets/nodes/src/widget.tsx

The pre-existing Deployment column was renamed to Deployment ID and is hidden by default. As a result nothing has changed in widget appearance except that the Deployment column now shows deployment name instead of deployment ID.
System tests: https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/871

RD-2335 Added deployment name column to nodes list widget

---

templates/pages/blueprints.json

Just as it says in the title. I have also formatted the page template with prettier.
After resetting the templates:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/879/pipeline
Queued 2021-07-01 15:53 CEST

RD-2654 Remove Composer Link widget from Blueprints page

---

templates/pages/blueprints.json

Cherry-pick of #1487 to master
In case this PR does not get merged today (Thursday), could either of you (@kubama, @stepek ) merge it yourself tomorrow and move RD-2654 to "done"? I will be absent tomorrow and this way we can conclude the required 6.1  tasks before you go on PTO :slightly_smiling_face:

RD-2654 Remove Composer Link widget from Blueprints page (#1487)

---

app/app.tsx
package-lock.json
package.json
webpack.config.js

Reverts cloudify-cosmo/cloudify-stage#1473
Adding this revert because `cloudify-blueprint-topology` is not fully support jquery ui itself.

Revert "Remove jQuery-UI"

---

test/cypress/integration/widgets/plugins_catalog_spec.ts
widgets/common/src/PluginActions.ts
widgets/common/src/PluginIcon.tsx
widgets/pluginsCatalog/src/Actions.ts
widgets/pluginsCatalog/src/PluginsCatalogList.tsx
widgets/pluginsCatalog/src/PluginsCatalogModal.tsx
widgets/pluginsCatalog/src/types.ts
widgets/pluginsCatalog/src/widget.tsx

This PR migrates the Plugins Catalog widget fully to TypeScript. My aim was only to make the code simpler to understand and keep functional changes to a minimum. I have also added system tests for the Plugins Catalog widget to make sure that the basic workflow (upload a plugin and check that it is visible in the Plugins widget) works.
There are no user-facing changes, only internal ones, so I'm not posting any screenshots.
I have verified that the error message is shown correctly after uploading a malformed plugin (some data was missing in the request body) and that the plugins are actually uploaded (which is also verified by the system test).
There will be a separate PR for RD-2483 that actually adds a new "Uploaded version" column to the Plugins Catalog widget. I am raising these …

RD-2483 Migrate Plugins Catalog widget to TypeScript

---

.size-limit
test/cypress/integration/widgets/plugins_catalog_spec.ts
widgets/pluginsCatalog/src/Actions.ts
widgets/pluginsCatalog/src/PluginsCatalogList.tsx
widgets/pluginsCatalog/src/types.ts
widgets/pluginsCatalog/src/widget.tsx

This PR adds the "Uploaded version" column to the Plugins Catalog widget. If the uploaded plugin version is the same as the latest version, the upload button is disabled with an appropriate tooltip.
I have also added a system test that verifies the code added/modified in this PR matches expectations.
This PR relies on #1495 being merged first. The changes from both PRs will have to be cherry-picked to `master` as well.
A new column:
Versions shown for installed plugins:
Tooltip when the Upload button is disabled:
Whole workflow:
https://user-images.githubusercontent.com/889383/124586698-09086c00-de57-11eb-88c0-a60e5a1b5091.mp4
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/895/pipeline
Queued 2021-07-06 13:39 CEST

RD-2483 Display uploaded plugin version in Plugins Catalog widget

---

app/components/Page.tsx
app/styles/style.scss
app/utils/shared/combineClassNames.ts
test/jest/utils/shared/combineClassNames.test.ts

This PR fixes the left margin for maximized widgets on smaller screens - it did not respect the fact that the sidebar is collapsed in such conditions and always assumed it is there. The actual fix is in 361212e54422e1b87ec96e9889bf485586b99b22.
Other commits are refactors/improvements that I made along the way as I was investigating the problem. They should not have any user-facing result or functional changes.
https://user-images.githubusercontent.com/889383/125455533-db20432b-24ba-42e6-9b9c-85616f935de2.mp4
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/913/pipeline
Queued 2021-07-13 14:59 CEST

RD-2128 Fix margin for widgets maximized on small screens

---

app/components/PagesList.tsx
app/utils/StageAPI.ts
test/cypress/integration/widgets/deployment_actions_spec.ts
widgets/common/src/DeploymentActions.ts
widgets/common/src/DeploymentActionsMenu.tsx
widgets/deploymentActionButtons/src/DeploymentActionButtons.tsx
widgets/deploymentActionButtons/src/widget.tsx

This PR removes the extra loading spinner that was shown inside of the `DeploymentActionButtons` widget. Now there will only be a single loader when the deployment data is being fetched from the Manager (the loader comes from our widget framework).
Additionally, this PR:
1. Migrates some code to TypeScript
2. Makes the data fetching states more explicit (explicit error, loading, success states)
3. Fixes some minor problems that I encountered along the way (static properties missing the `static` keyword, `Error` not being handled as widget's `data`)
I tried to add a test to verify that there is only a single loading spinner active, but Cypress was too slow (or the data fetching was too fast) and did not catch the moment that there was a spinner. It always saw 0 spinners when deployment was …

RD-1827 Remove double loader in DeploymentActionButtons widget

---

test/cypress/integration/widgets/deployments_view_spec.ts
widgets/common/src/deploymentsView/DeploymentsView.tsx
widgets/common/src/deploymentsView/styles.scss

1. Add bounds on the minimum widths of panes in the Deployments View widget
when resizing them.
2. Make sure the draggable handle is always visible.
3. Modify system tests to verify that resizing is bounded.
https://user-images.githubusercontent.com/889383/126150371-7be2fae6-0617-4730-b652-0132b4352938.mp4
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/933/pipeline
Queued 2021-07-19 13:02 CEST

RD-2769 Fix unbounded resizing of Deployments View panes

---

test/cypress/integration/widgets/maintenance_mode_button_spec.ts
test/cypress/integration/widgets/servers_num_spec.ts
test/cypress/integration/widgets/snapshots_spec.ts
test/cypress/support/executions.ts

In this PR I merged `waitUntilNoExecutionIsActive` and `killExecutions` Cypress commands into one `killRunningExecutions`. It should be executed before each test which needs no executions running in the Cloudify Manager.
I found 3 tests that are designed in such a way that no running executions is needed:
* Maintenance Mode Button widget test - `maintenance_mode_button_spec.ts`
* Number of Nodes widget test - `servers_num_spec.ts`
* Snapshots widget test - `snapshots_spec.ts`
and added a call to to `killRunningExecutions` command there.
Especially making the first one (Maintenance Mode Button widget test) more reliable can help us avoid problems stemming from turned on Maintenance Mode (failing Topology widget test, Nodes widget test, Nodes Statistics widget test, Outputs/Capabilities …

RD-2639 Make system tests independent from running executions

---

app/.eslintrc.json
app/components/EditWidgetModal.tsx
app/components/shared/PageFilter.tsx
app/utils/StageAPI.ts
app/utils/Toolbox.ts
widgets/buttonLink/src/widget.tsx
widgets/common/src/DynamicDropdown.tsx
widgets/common/src/deploymentsView/header/filter/FilterModal.tsx
widgets/common/src/filters/inputs/LabelValueInput.tsx
widgets/common/src/hooks/useEventListener.ts
widgets/common/src/labels/CommonDropdown.tsx
widgets/common/src/labels/LabelsInput.tsx
widgets/deploymentsView/src/widget.tsx

This PR:
1. Migrates `DynamicDropdown` to TypeScript and fixes resulting TS errors.
2. Adds a type for `CustomConfigurationComponentProps` (used when the widget's configuration uses a custom component).
3. Migrates `Toolbox` to TypeScript
4. Migrates `PageFilter` component to TS (there were some errors with using it as a `component` in custom configuration, so I decided to migrate it entirely rather than just fix that one small problem with `connect`)
My intention for this PR is to have no user-facing changes.
This PR is a base for the functionality for RD-1851.
I doubt we will complete RD-1851 this week to merge it into 6.1. Unless some miracle happens and I complete it early tomorrow, I will keep the PRs pointed at 6.1. If that does not happen, I will rebase them and point them to …

RD-1851 Migrate DynamicDropdown to TS and do some minor enhancements

---

test/cypress/integration/widgets/deployments_view_spec.ts
test/cypress/support/commands.ts
widgets/deploymentsView/src/FilterIdDropdown.tsx
widgets/deploymentsView/src/widget.tsx

This PR leverages the work done in #1518 to add an autocomplete component (`DynamicDropdown`) as the custom component for the default filter to use in the Deployments View widget.
There are also changes in the system tests to make sure it all works according to our expectations.
Depends on #1518 
https://user-images.githubusercontent.com/889383/126783299-7edc92e3-c6f6-4c2a-bdfe-7ff447fcab35.mp4
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/974/pipeline
Queued 2021-07-26 14:13 CEST

RD-1851 Add autocomplete for default filter in Deployments View widget

---

test/cypress/integration/widgets/filters_spec.ts

I found out that the only difference between label key selecting function (`selectRuleLabelKey`) and other functions setting values in dropdowns in `filters_spec` (`selectRuleRowType`, `selectRuleOperator`, `selectRuleAttributeValues`, `selectRuleLabelValues`) was that in `selectRuleLabelKey` there was no `click` issued on the dropdown's div element. I suspect that might be an issue.
This PR contains two changes:
1. https://github.com/cloudify-cosmo/cloudify-stage/pull/1519/commits/741bbec6435cbe1442e6e6ca57beb3bd426ade98 - small change, just `click` addition in `selectRuleLabelKey` (that should fix the problem)
2. https://github.com/cloudify-cosmo/cloudify-stage/pull/1519/commits/8ecc3ae844fc454b09ec87fe6f195d806b0f61d8 - refactoring in dropdowns usage inside `filters_spec`. The goal was …

RD-2664 Fix selecting label key from dropdown list in filters_spec

---

widgets/common/src/deploymentsView/DeploymentsView.tsx

This PR changes the default behavior of react-split-pane to improve the usability of the Deployments View widget.
The changes are quite simple:
1. Increase the minimum width of the panes so that the UI keeps looking good, even at minimum width.
2. Change the default width ratio to 40/60
The page size part of RD-2789 will come in a separate PR after https://github.com/cloudify-cosmo/cloudify-ui-components/pull/76 is merged. I have decided to split it into 2 PRs for stage so I can deliver a part of the functionalities earlier.
https://user-images.githubusercontent.com/889383/127164700-f57c89ff-bec9-413a-b57f-bf483486628c.mp4
https://jenkins.cloudify.co/job/Stage-UI-System-Test/987/
Queued 2021-07-27 15:53 CEST

RD-2789 Change default split-pane behavior in Deployments View

---

package-lock.json
package.json
widgets/common/src/DeploymentActionsMenu.tsx

Upgrade the package and remove an unnecessary `ts-expect-error` comment.
This is because `Popup.Trigger` can now accept children.
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1000/pipeline
Queued 2021-07-29 8:53 CEST

RD-2897 Upgrade ui-components to 2.6.0

---

test/cypress/integration/widgets/topology_spec.ts

Refactor the assertions in `topology_spec` to allow extra properties in the asserted objects. Changes the existing logic of using `omit` to skip some fields and now asserts that only the fields from the expected objects match.
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1002/pipeline
Queued 2021-07-29 9:56 CEST

RD-2898 Loosen assertions in topology spec

---

app/reducers/widgetsReducer.ts
app/utils/UserAppDataAutoSaver.ts
test/cypress/integration/edit_mode_spec.ts
test/cypress/integration/page_spec.ts
test/cypress/support/commands.ts
test/jest/reducers/pagesReducer.test.ts

Looks like the reason for the problem (RD-2999) was that `POST /console/ua` was called multiple times and in some cases it was hard to know how many times it will be called. In this PR I changed how we save `userApp` data in `UserAppDataAutoSaver` instance by using `lodash.debounce` and sending request only after 1 second since last trigger.
Within this PR I also improved our test page to include all standard widget parameters.
https://user-images.githubusercontent.com/5202105/129903986-706b8bae-f392-4c9a-ba88-dbcbeb9b13e6.mp4
https://user-images.githubusercontent.com/5202105/129903999-d49ae648-0144-4258-8fd8-bd7544125f4c.mp4
As this issue was not always happening, I have triggered 3 builds:
1. [Stage-UI-System-Test/1099](https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-Syst …

RD-2999 Improve UserAppDataAutoSaver and fix Edit Mode test

---

jenkins/Jenkinsfile

This PR changes build result when Audit stage fails from `SUCESS` to `UNSTABLE`. That way we can save UI Guardian's time - as he will only need to check job details in case of yellow (`UNSTABLE`) or red (`FAILURE`) build colors.
I'm planning to update all other UI repositories once we get this PR merged.
Taking advantage of stage encountering audit issue since some time, I just check build status with the changes:
* build is marked yellow (unstable)
* none of the stages are blocked after marking build as unstable
[cloudify-stage/job/RD-3024](https://jenkins.cloudify.co/job/cloudify-stage/job/RD-3024/3/)
I'll update [UI Health Monitoring - Process](https://cloudifysource.atlassian.net/wiki/spaces/RD/pages/1759346689/Process) page with information that audit failure should be indicated by …

RD-3024 Change build result to UNSTABLE when audit stage fails

---

widgets/deploymentNum/README.md
widgets/plugins/README.md
widgets/pluginsCatalog/README.md

As https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1918 and https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1919 were merged, this PR updates `README.md` files for all changed widgets' documentation pages.
N/A
Docs stage in CI pipeline passes.
N/A

RD-2826 & RD-2479 Update widget help description for "Number of Deployments", "Plugins" and "Plugins Catalog" widgets

---

app/components/GettingStartedModal/useModalOpenState.ts

In the clean Cloudify Manager installation, when the user logs in Getting Started modal is presented. After #1565 implementation it was not working properly as it was not possible to close the modal. 
The reason for that: 
* once Close button is clicked, the modal is being closed, `gettingStarted` query parameter is removed and location is updated
* `gettingStarted` query parameter change triggers useEffect hook to be fired, sets `gettingStarted` query parameter again and opens the modal
As a result of that, the user was not able to close the modal.
https://user-images.githubusercontent.com/5202105/131479023-440d52eb-deea-4544-9dc1-4608bbf09515.mp4
[Stage-UI-System-Test/1165](https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1165/pipeli …

RD-2936 Fix useModalOpenState to allow closing Getting Started modal in all cases

---

app/components/GettingStartedModal/useModalOpenState.ts

Cherry-pick of #1572 on `6.2.0-build` branch.
N/A
Just a cherry-pick, so not planning any testing.
N/A

RD-2936 Fix useModalOpenState to allow closing Getting Started modal in all cases [6.2]

---

test/cypress/integration/login_spec.ts

The reason for the problem described in RD-3123 is unknown for me. From the screenshot and video it seems like the awaited `updateUserApps` (`POST /console/ua`) was present, but only after the assertion was already executed 😕:
The problem is not reproducible in local environment and didn't happen in the last nightly ([Nightly-UI/228](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Nightly-UI/228/) - 9th Sep), so I think it is not worth to spend much time on it. 
I just refactored waiting for the response which we want to verify in that test, it should be a bit more verbose right now. Instead of `cy.wait(...).then(...)` chain, I used `cy.wait(...).its(...)` chain.
For the future we may:
1. Dig into cypress issues and try to find something similar as it seems like possible bug in …

RD-3123 Refactor waiting in login_spec.ts

---

app/translations/en.json
test/cypress/integration/widgets/blueprint_catalog_spec.ts
test/cypress/integration/widgets/blueprints_spec.ts
test/cypress/support/commands.ts
widgets/blueprintCatalog/src/RepositoryTable.tsx
widgets/blueprintCatalog/src/types.ts
widgets/blueprintCatalog/src/widget.tsx
widgets/blueprints/src/BlueprintsList.tsx
widgets/blueprints/src/types.ts
widgets/blueprints/src/widget.tsx
widgets/common/src/BlueprintUploadActionsMenu.tsx
widgets/common/src/blueprintMarketplace/BlueprintMarketplaceModal.tsx
widgets/common/src/blueprintMarketplace/index.ts
widgets/common/src/blueprintMarketplace/types.ts

Cherry pick of #1581 RD-3017 Add support for switching between Catalog and Table view in Blueprints Marketplace modal.
* RD-3017 Add support for switching between Catalog and Table view in Blueprints Marketplace modal.
* Added translations and fix pr comments.
* Update test/cypress/support/commands.ts

RD-3017 Add support for switching between Catalog and Table view in Blueprints Marketplace modal. (#1581)

---

app/translations/en.json
test/cypress/integration/widgets/deployments_view_spec.ts
widgets/common/src/DeployBlueprintModal.tsx
widgets/common/src/GenericDeployModal.tsx
widgets/common/src/deploymentsView/header/DeployOnModal.tsx
widgets/deploymentsView/README.md

Within this PR new field is added to "Deploy On" modal. This is text input field which is then used to create deployment name for newly created deployments.
[Stage-UI-System-Test/1252](https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1252/pipeline) (14.09.2021, 09:44:01 CEST) - PASSED
Deployments View widget description update PR: https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/1949 .
I'd like to merge it first and then update Deployments View widget's `README.md` within this PR.

RD-3110 Enhance Deploy On modal to allow providing a suffix for new deployments

---

.size-limit
app/translations/en.json
widgets/blueprintCatalog/src/RepositoryTable.tsx
widgets/common/src/blueprintMarketplace/BlueprintMarketplaceModal.tsx

This PR introduces final alignments in Actionable Dashboard. Blueprint Marketplace modal is displayed right now in Table view with just 'Name' and 'Description' columns visible.
Within this PR I fixed also displaying action items in Table view in Blueprint Catalog widget:
* spinner icon showed on blueprint upload was not spinning before (`loading` prop was never set on `Icon` component)
* blueprint upload icon was not disabled properly when blueprint was already uploaded (`link` prop was always set to `true` on `Icon` component)
https://user-images.githubusercontent.com/5202105/133035956-541e82a4-6185-41c4-b1d9-f8cec26c2204.mp4
[Stage-UI-System-Test/1248](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1248/) (13.09.2021 08:46:06 CEST) - PASSED
No updates …

RD-3140 Update Blueprint Marketplace modal to use Table view by default

---

backend/handler/ArchiveHelper.js

This PR fixes RD-3099 in `6.2.0-build` branch. Cherry pick from `master` was not possible as in `6.2.0-build` branch Stage backend does not have TS support, so I decided just to apply the fix in the backend JS file without adding the test created on `master` branch.
N/A
Unit test only on `master` branch.
[Stage-UI-System-Test/1269](https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1269/pipeline) (15.09.2021 09:30:21 CEST) - PASSED
N/A

RD-3099 Fix uploading blueprint that contains directories recognized as files by `decompress` library [6.2]

---

widgets/.eslintrc.json
widgets/common/src/blueprintMarketplace/index.ts
widgets/common/src/deploymentsView/index.ts
widgets/common/src/filters/index.ts
widgets/common/src/labels/index.ts

The `@typescript-eslint/no-namespace` ESLint rule is often disabled locally in files in widgets because we are using namespaces to define the Stage global API. To avoid disabling it locally, I have disabled it for all files in the `widgets` directory.
N/A
`npm run lint` passes locally.
N/A

RD-2061 Disable no-namespace ESLint rule in widgets

---

app/translations/en.json
templates/pages/adminDash.json

Despite that 6.2 is not yet released, the UI development is: 1. separated to `6.2.0-build` branch, 2. completed.
No need to change `rawContentBasePath` in `scripts/readmesConfig.json` as it already points to `master` branch in docs repo.
N/A
I've checked locally if the documentation links work properly.
N/A

RD-3106 Update documentation links after 6.2 release

---

test/cypress/integration/widgets/snapshots_spec.ts

Seems like snapshot creation time increased recently, so I improved Snapshot widgets test not only to wait for the change in the table, but also verify that the snapshot was created by polling status from the Cloudify Manager API.
In addition to that removed `@ts-check` annotation form `snaphost_spec.ts` file as it has already been fully TS migrated.
https://user-images.githubusercontent.com/5202105/136204783-370d2d05-74bd-482f-837a-9e3c5dd62d6e.mp4
[Stage-UI-System-Test/1352](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1352/) - only Snapshots widget test - PASSED
N/A

RD-3322 Make snapshot widget test less prone to timeout errors

---

app/components/sidebar/UserMenu.tsx
app/reducers/managerReducer.ts

As mentioned [here](https://cloudify.slack.com/archives/G9MN0TDG8/p1638427146002700), as the name of the parameter `isLdap`, has been changed to `isLdapEnabled`, in some places it remained unchanged, which caused some bugs to appear.
Because of those bugs, a test file `change_password_spec.ts` was execution was [resulting in failures](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1595/testReport/(root)/Change%20Password%20modal%20should%20not%20be%20available%20when%20LDAP%20is%20enabled/should_not_be_available_when_LDAP_is_enabled/).
N/A
I've run locally the failing tests, and now they appear to run successfully.
N/A

RD-3477 Renamed isLdap parameter so that it is consistent across the application

---

test/cypress/integration/widgets/deployment_button_spec.ts

This PR is the follow up to https://github.com/cloudify-cosmo/cloudify-stage/pull/1693
The previous PR was merged by mistake before I fixed the interceptSp and refactored according to review comments.
https://github.com/cloudify-cosmo/cloudify-stage/pull/1693
- I run one time the relevant system tests on my machine and they passed successfully.
- I started running system tests in Jenkins:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1670/pipeline
https://github.com/cloudify-cosmo/cloudify-stage/pull/1693

RD-1607 Follow-up PR: Refactor and fix system test for missing secrets error message

---

templates/pages/environments.json
templates/pages/services.json
widgets/common/src/deploymentsView/DeploymentsView.tsx
widgets/common/src/deploymentsView/layout.ts

See RD-3806 description for reasoning. It's another "bandage" solution. I did not change the height 10x because I think it is more than enough changing the height from 28 to 100 in our page JSON files. All widgets in the right pane in all tabs are visible and there is still much space left. There is no scrollbar on the right side. So both main requirements for RD-3806 are met.
In addition to the change I fixed minor styling issues.
Adding screenshots only for Services page, the same change was done in Environments page.
[Stage-UI-System-Test #1677](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1677/) (16.12.2021 08:46) - PASSED
N/A

RD-3806 Adjust height of Deployments View widget in Services and Environments pages

---

templates/pages/environments.json
templates/pages/services.json

It's a continuation of https://github.com/cloudify-cosmo/cloudify-stage/pull/1709 - it turned out that the increase was too small for Deployment Info tab. See video how it looks right now.
https://user-images.githubusercontent.com/5202105/146364814-e3a647b7-eb97-42f9-91d8-b4662516467d.mp4
No need to run tests IMHO. https://github.com/cloudify-cosmo/cloudify-stage/pull/1709 validates that height change does no affect test results.
N/A

RD-3806 Increase height of Deployments View widget in Services and Environments pages

---

jenkins/Jenkinsfile

Due to rare occasions of a failed pull from AWS edge endpoint of s3 items

RD-3838 change node_rpm url to original s3 url instead of edge endpoint

---

jenkins/Jenkinsfile

rm installation of rpmlint from jenkinsfile as it's now preinstalled in our internal rpmbuild image.
This should solve the occasional yum installation failure in the CI.
And if that won't fix it for good, it saves a few seconds anyway and doesn't harm the CI.

RD-3838 rm rpmlint from jenkinsfile, will be in internal image

---

app/utils/shared/ExecutionUtils.ts
test/cypress/integration/widgets/deployments_spec.ts

This is the second PR for RD-3914. This one fixes `deployments_spec` as well as updates workflow ID used to detect if specific execution is related to deployment update. In addition to that, `deployments_spec` was fully migrated to TypeScript.
N/A
1. `deployments_spec` passes locally 
2. [Stage-UI-System-Test/1832](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1832/) (18.01.2022, 12:58) - PASSED
Executions widget page description should be updated, but to speed up the process, I have added a point to RD-2504.

RD-3914 Change workflow ID used during deployment updates

---

backend/consts.ts
backend/handler/AuthHandler.ts
backend/routes/Auth.ts
backend/routes/ServerProxy.ts
backend/test/routes/Auth.test.ts

As a result of discussion in RD-3828 a change in `Auth.ts` had to be implemented to satisfy different environment needs. `getCookieOptions` function had to be updated to check both - `X-Scheme` and `X-Force-Secure` headers - to determine if token cookie should have `Secure` flag set.
In addition to that change few backend files were migrated to TypeScript.
N/A
1. Updated backend unit tests.
2. [Stage-UI-System-Test/1834](https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1834/tests) - only one test failing, it's reported already as RD-3760, not related to this PR, so I'm considering it as PASSED
N/A

RD-3828 Change rules for setting Secure flag on token cookie

---

test/cypress/components/app/sidebar/TenantSelection_spec.tsx

Changes consists of adding a delay to the `mockTenantsResponse`, so that the cypress has more time to see the `<Loading />` component.
N/A
I've executed [System Tests](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/1864) and it passed without a problem! 🎉 
N/A

RD-4040: Delayed tenants request response

---

app/translations/en.json
scripts/readmesConfig.json
templates/pages/adminDash.json
templates/pages/blueprints.json
test/cypress/integration/widgets/blueprint_catalog_spec.ts
test/cypress/integration/widgets/blueprints_spec.ts

Both - widget help description documentation and links to blueprint examples - were hardwired to 6.3 branches.
N/A
Did manual tests:
* verified that images links in widget help description points to https://docs.cloudify.co/6.3.0/...
* verified that blueprint examples are available (only in Blueprints widget) - only [Helm examples](https://repository.cloudifysource.org/cloudify/blueprints/6.3/helm_services.json) not available, @alexmolev notified
N/A

RD-3972 Switch documentation and blueprint examples to 6.3

---

app/translations/en.json
test/cypress/fixtures/widgets/splitViewWidget.tsx
test/cypress/integration/getting_started_spec.ts
test/cypress/integration/widgets/plugins_catalog_spec.ts
test/cypress/support/commands.ts

As per @alexmolev request this PR updates plugins catalog link to the latest available version.
There is more occurrences of "repository.cloudifysource.org/cloudify/wagons/plugins.json" string, but they are only in `backend/test/snapshots` (in .sql files), so I decided not to change them.
Will create cherry-pick PR for 6.3 once this one is merged.
N/A
[Stage-UI-System-Test #1926](https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1926/tests) - PASSED
N/A

RD-4090 Update plugins catalog link to the latest version

---

.size-limit
app/components/sidebar/SideBar.tsx
app/components/sidebar/SideBarItem.tsx
test/cypress/integration/widgets/blueprints_spec.ts

Changes consists of adding transition to the menu subitems, so that they won't "jump", while the sidebar is being expanded.
Same before/after effect has been achieved as shown in [jira task](https://cloudifysource.atlassian.net/browse/RD-4048)
N/A, as the changes are strictly styling related 🚀 
N/A

RD-4048: Added component which is used to animate menu subitems

---

package-lock.json
package.json

This pull-request is part of RD-3222. It was created to make it merge fast. Because PRs from other developers need `cloudify-ui-common` to be updated to v5.1.2.
PR Part 2 of RD-3222 task in Cloudify-stage is: https://github.com/cloudify-cosmo/cloudify-stage/pull/1796
N/A
System tests passed:
https://jenkins.cloudify.co/blue/organizations/jenkins/Stage-UI-System-Test/detail/Stage-UI-System-Test/1998/pipeline
I think it is `N/A` because if there documentation update needed it probably was explained in the description of the PRs in cloudify-ui-common.

RD-3222 eslint part 1: Update cloudify-ui-common to v5.1.2

---

test/cypress/integration/widgets/maintenance_mode_button_spec.ts
test/cypress/support/commands.ts
test/cypress/support/resource_commons.ts

After #1815 merge I discovered a problem in few tests:
```
An uncaught error was detected outside of a test.An uncaught error was detected outside of a test (from Root Suite)
The following error originated from your test code, not from Cypress.    > resource_commons_1.minutesToMs is not a function  When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.  Cypress could not associate this error to any specific test.  We dynamically generated a new test to display this failure.
Cypress could not associate this error to any specific test.
```
This PR aims to fix it.
N/A
[Stage-UI-System-Test #2070](https://jenkins.cloudify.co/job/Stage-UI-System-Test/2070/console) - all tests - PASSED 
N/A

RD-3760 Improve setting admin authorization in `cfyRequest` Cypress command

---

backend/package-lock.json
backend/package.json

Executed `npm audit fix` to fix `request` package related security issues.
The only leftover in security audit is vulnerability coming from `ajv` package. The following PRs should solve it:
1. #1819 
2. #1816 
N/A
Audit is not showing any issues related to `request` package.
Only patch or minor version changes, so I don't expect any problems with system tests.
N/A

RD-3609 Fix security audit issues coming from `request` package

---

backend/package-lock.json
backend/package.json

Within #1835 `vm2` package version was bumped from `3.9.5` to `3.9.8` to fix security issues.
Unfortunately it turned out that there was a breaking change in `3.9.6`, so this PR reverts the bump.
Additionally an issue in `vm2` package repository was created: https://github.com/patriksimek/vm2/issues/411
Looking at the
N/A
[Stage-UI-System-Test #2111](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2111/) - IN PROGRESS
N/A

RD-4304 Downgrade `vm2` package to v3.9.5

---

app/components/GettingStartedModal/schema/cloudSetup.schema.json

Just a typo fix. Planned for `6.3.1`, so I'll create cherry-pick PR once this is merged to `master`.
1. ![image](https://user-images.githubusercontent.com/5202105/155115911-559659cd-958b-42f9-9873-58495a090e03.png)
2. ![image](https://user-images.githubusercontent.com/5202105/155116129-7868924e-b8d0-4f59-8ffc-f486603b3df2.png)
3. ![image](https://user-images.githubusercontent.com/5202105/155116198-af82bdce-3132-4ba5-8df2-76be87dd9b11.png)
Did manual tests only, see screenshots.
We don't have `vSphere` tests, so I'm not planning system tests run.
N/A

RD-4320 Fix typo in vSphere Secrets dialog in Getting Started modal

---

test/cypress/integration/templateManagement/templates_spec.ts

There is an issue occurring from time to time in Stage-UI-System-Test job revealing Templates spec test flakiness. I didn't find a way to solve it properly, so according to our rules I'm adding test retries to the test case.
Tested retries locally (with `openMode: 2`) to check if test is independent, seems working fine.
Ref. RD-4589
N/A
Tested locally, all passed.
N/A

RD-4589 Add test retries to one test in Templates spec

---

test/cypress/integration/edit_mode_spec.ts

As we all know Edit Mode spec is quite flaky. The flakiness comes from verification of `POST /console/ua` calls response body.
I think we can live without those checks without losing much, so I removed all those assertions and removed test retries as they were not helping to solve the flakiness.
Ref. RD-3672
N/A
1. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2329)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2329/) - only Edit Mode spec - PASSED
2. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2330)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/2330/) - only Edit Mode spec - PASSED
N/A

RD-3672 Edit Mode spec adjustments

---

backend/routes/Plugins.ts
test/cypress/integration/widgets/topology_spec.ts
test/cypress/support/commands.ts

This small PR fixes two bugs:
1. Topology widget was throwing Internal Server Error (as 304 error was converted to 500 in the backend)
2. Topology widget spec was not refreshing the widget properly after deployment installation finished, so the Terraform Resources modal was not always filled with data
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2335)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2335/) - only Topology widget spec - PASSED
N/A

RD-4666 Fix error 500 in Topology widget & make Topology widget spec more robust

---

test/cypress/integration/widgets/plugins_catalog_spec.ts

There was a change in http://repository.cloudifysource.org/cloudify/wagons/v2_plugins.json which does not allow to detect if the uploaded version of the plugin is the same as the one listed in the Plugins Catalog for some of the plugins (those which has no explicit version set, but version set to "latest").
Until we have final decision about the Plugins Catalog JSON file (see discussion in RD-4906), this PR adds skipping failing tests. 
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2672)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2672/)
N/A

RD-4906 Skip two test cases in Plugins Catalog spec

---

app/components/AuthRoutes.tsx
app/utils/consts.ts
test/cypress/integration/login_spec.ts

With this change it will be possible to log in to the Cloudify UI as a user with `sys_admin` role and without tenants assigned.
I added RD-1103 to coming sprints, so we'll be able to deduplicate some consts between frontend (framework and widgets) and backend.
N/A
Updated Login spec.
Full run - [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2707)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2707/)
No necessary updates I think.

RD-1107 Allow user with `sys_admin` role and without tenant assigned to log in

---

.size-limit
app/actions/app.ts
app/actions/managers.ts
app/actions/types.ts
app/components/sidebar/UserMenu.tsx
app/reducers/managerReducer/authReducer.ts
app/reducers/managerReducer/emptyState.ts
app/reducers/managerReducer/managerReducer.ts
app/utils/consts.ts
app/utils/shared/IdpUtils.ts
app/utils/stageUtils.ts
backend/handler/AuthHandler.ts
backend/routes/External.ts
test/cypress/components/app/sidebar/SideBar_spec.tsx
test/cypress/integration/change_password_spec.ts
test/cypress/integration/widgets/user_groups_spec.ts
test/cypress/integration/widgets/user_management_spec.ts
test/jest/reducers/managerReducer/managerReducer.test.ts
test/jest/utils/Manager.test.ts
widgets/userGroups/src/CreateModal.tsx
widgets/userGroups/src/UserGroupsTable.tsx
widgets/userManagement/src/MenuAction.tsx

The main idea behind this PR is to align password changing restrictions along Cloudify UI application. For more details and requirements see RD-1051.
List of main changes:
* introduced `identityProviders` parameter inside Redux store (replaced `isLdapEnabled` parameter)
* used `identityProviders` in sidebar's user menu and User Management widget (Change Password option visibility)
* used `identityProviders` in User Groups Management widget (LDAP options visibility)
N/A
1. Updated tests (unit, component, e2e).
2. Full system tests run [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2719)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/2719/) - all passed.
3. Another full system tests run [![Build …

RD-1051 Update restrictions on password changing

---

test/cypress/integration/getting_started_spec.ts

The flakiness in Getting Started spec (`beforeEach` hook in `without mocked pages` tests) was due to the fact that after the splash screen disappears, not always Dashboard page is displayed. `mockLogin` expects a Dashboard page to be displayed and it waits for all widgets to be loaded. It can happen that Getting Started modal appears just after splash screen and there's no Dashboard (nor widgets) displayed.
So I decided to omit waiting for widgets to be loaded and wait only for splash screen to disappear.
N/A
1. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=2808)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/2808/) (only Getting Started spec) (27th May 2022)
2. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI- …

RD-5032 Improve robustness of Getting Started spec

---

app/components/layout/Grid.tsx
app/styles/style.scss
widgets/common/src/blueprintMarketplace/BlueprintMarketplaceModal.tsx
widgets/plugins/src/MarketplaceModal.tsx

According to recently settled requirement: "Minimal supported screen width: 1280px" and decision to use horizontal scrollbar for smaller screens, I have adjusted minimal width for `div.main` element.
In addition to the main change I did the following:
* Used `ReactGridLayout` component with fixed number of columns (no need to use responsive grid with minimal width set)
* Fixed content of blueprint and plugin marketplace modals to always use full width of the modal (using `maximized` does not work, RD-5023 should make it possible to use `maximized` in layout definition JSON)
https://user-images.githubusercontent.com/5202105/176841106-23ab05a9-b5cb-4ca9-a8e6-7bf1c0d2535d.mp4
1. I did many manual tests - didn't spot any issues
2. [![Build …

RD-4254 Set minimal width for the main layout

---

app/translations/en.json
widgets/userManagement/src/UsersTable.tsx

This PR is a follow-up for #2038 and it:
1. Fixes `user_management_spec.ts`
2. Improves "Getting started" column header styling in Users Management widget
"Getting started" column header is being adjusted automatically (single line when screen width is high, two lines when screen width is lower). Before it was always displayed in two lines.
https://user-images.githubusercontent.com/5202105/177487644-3a2288f9-ce57-49a0-b752-421a00fb5159.mp4
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3062)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3062/) - only `user_management_spec.ts` - in progress
N/A

RD-5153 Improve 'Getting started' column header styling in Users Management widget

---

widgets/common/src/inputs/fields/ValueListInputField.tsx
widgets/topology/src/Topology.tsx

As described in RD-5365 the topology view didn't load on second time open.
The reason for that problem was the fact that topology data was set (`topology.setTopology` calls in [widgets/topology/src/Topology.tsx](https://github.com/cloudify-cosmo/cloudify-stage/blob/master/widgets/topology/src/Topology.tsx)) only in case of blueprint data update. On `Topology` component mount the view was not initialized properly.
Small refactorings added: 
1. fixed `propTypes` definition
2. simplified nodes difference checking function
NOTE: This widget is hard to maintain (it's using non-React library for rendering the view) and the code is very messy. I considered TS migration, but I decided to drop it as a time-consuming and risky before the release. …

RD-5365 Fix Topology widget data loading

---

app/components/EditWidget.tsx
app/components/EditWidgetIcon.tsx
app/components/EditWidgetModal.tsx
app/components/shared/DynamicTable.tsx
app/utils/Toolbox.ts

Fixes RD-5371 by passing `placeHolder` configuration parameter to `GenericField` component (b62517b781ba9f6fbb312d7c1676ef8dde5fd927).
In addition migrated few components from `EditWidget*` family to TypeScript (f4e0ae30121a2c37745b6a227f4710fc1bcf070d).
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3149)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3149/) (15.07.2022) - all PASSED
N/A

RD-5371 Fix support for `placeHolder` widget configuration parameter

---

backend/routes/Terraform.ts

Issue was caused by not scanning `main.tf` file via processing mechanism for `.git` files
Solution for getting all the necessary file paths to scan has been unified across mechanisms responsible for processing `.git` and `.zip` files, to make it more robust and bulletproof 🎸 
https://user-images.githubusercontent.com/89005877/179215616-de009811-7f7e-44b3-adad-1afb56a467d8.mp4
https://user-images.githubusercontent.com/89005877/179215646-f254b665-773e-493e-9be0-3b913215b44a.mp4
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3158)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3158/)
2 case scenario had failed, but not due to the introduced modifications
From analyzing the video from …

RD-5301: Synchronized mechanism for scanning zip and git files

---

widgets/agents/src/widget.tsx

Invalid default value of `installMethods` configuration parameter resulted in having data `install_methods=null` in query string of Agents widget data URL, e.g.
```
http://127.0.0.1:4000/console/sp/agents?&_sort=id&_size=5&_offset=0&install_methods=null&state=started
```
and that caused empty agents list in the response and no agents displayed in the table.
This PR changes the default value to correspond with the type of the input field (`MULTI_SELECT_LIST_TYPE`) and sets it to empty array.
N/A
Did manual tests only.
N/A

RD-5393 Fix default value of `installMethods` configuration parameter in Agents widget

---

widgets/common/src/deploymentsView/detailsPane/header.tsx

Since implementation of #2023 the list of workflows may change after workflow execution. Deployment Action Buttons widget used inside Deployments View widget was not using data polling, so it couldn't get updated. This PR fixes this behavior by simply adding `pollingTime` parameter to Deployment Action Buttons widget defined inside Deployments View widget.   
https://user-images.githubusercontent.com/5202105/180049981-9d08394d-1972-4962-aa6e-9a3654e7f645.mp4
Don't see a need to run system tests for such a simple fix.
N/A

RD-5406 Fix refreshing deployment action buttons in Deployments View widget

---

test/cypress/integration/widgets/blueprints_spec.ts
test/cypress/integration/widgets/filter_spec.ts
widgets/blueprints/src/BlueprintsCatalog.tsx

The problem described in RD-5382 comes from the fact that blueprint ID was passed to `className` prop in one of the components in Blueprints widget. Depending on the blueprint ID it could change the styling of the catalog item 🙂 
1. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3192)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3192/) - `blueprints_spec` and `filter_spec` failed
2. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3196)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3196/) - only `blueprints_spec` and `filter_spec`:
a. `blueprints_spec` - failed due to known issue (RD-5020), so I'm considering it as PASSED
b. …

RD-5382 Remove setting blueprint ID in `className` prop

---

app/translations/en.json
test/cypress/integration/widgets/topology_spec.ts
widgets/events/src/widget.tsx
widgets/topology/src/Topology.tsx

[Issue](https://cloudifysource.atlassian.net/browse/RD-3910) is appearing due to unnecessary passing `nodeId` to deployment page.
It is read by `events` widget, making the event list to be incorrectly filtered.
That behavior seems to be related to the fact, that while clicking on the "Go to deployment page" button (inside `topology` widget) we are not only executing function attached to that button, but also the one responsible for handling selection of a specific node (to which the clicked button is attached 😅)
As handler for node selection is putting some extra data into the application `context`, we are getting into the situation when we are trying to navigate to the deployment page with a data that shouldn't be passed.
It looks like an issue related to the event bubbling - coming from …

RD-3910: Blocked passing unnecessary data upon navigating to deployment page

---

backend/package-lock.json
backend/package.json

Fixes security vulnerability described in RD-5440 .
After changes in `package*.json` files:
```
│ │ │ └── ansi-regex@5.0.1
│ │ │ │ ├── ansi-regex@5.0.1 deduped
```
N/A
Updated package is used only in migration code, so did only unit testing.
N/A

RD-5440 Bump `sharp` package to v0.30.7

---

backend/package-lock.json
backend/package.json

A proper fix for app-crashing issue (https://github.com/follow-redirects/follow-redirects/issues/211 and RD-5663) was implemented in `follow-redirects` package and new version was released. Bumped `axios` package to get the latest `follow-redirects`.
Noticed that axios v1 is coming, so created RD-5969.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3569)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3569/) - failed due to known issues (RD-5918, RD-5921, RD-5922), so I'm considering it as PASSED
N/A

RD-5965 Bump `axios` and `follow-redirects` packages in backend to make Stage DB migration more robust

---

test/cypress/integration/flows/user_spec.ts
test/cypress/integration/widgets/blueprints_terraform_spec.ts
test/cypress/integration/widgets/topology_spec.ts
test/cypress/support/executions.ts

The root cause for failing tests described within RD-5918, RD-6070 and RD-6071 is not in the UI source code.
Created RD-6082 and discussed it roughtly with @geokala .
For the time being let's skip failing tests.
In addition I have improved `waitForExecutionToEnd` Cypress custom command, so we will not only wait, but also verify execution status => that should make the actual errors provided by Cypress to be more accurate.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3657)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3657/)
N/A

RD-5918 RD-6070 RD-6071 Improve waiting for execution to be finished and skip failing tests

---

test/cypress/integration/widgets/blueprints_terraform_spec.ts

`blueprint_spec` was failing from time to time in "handle template URL 401" test case.
Added a check for Deploy blueprint modal existence after successful blueprint upload hoping that it'll reduce test flakiness.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3666)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3666/)
N/A

RD-5266 Add check for Deploy blueprint modal existence after successful blueprint upload in blueprint_terraform_spec

---

package-lock.json
package.json

Snyk reported [cloudify-stage - SNYK-JS-GLOBPARENT-1016905](https://app.snyk.io/org/cloudify-manager/project/42f77e91-9e07-43d5-8ef9-8367ae5f163c#issue-SNYK-JS-GLOBPARENT-1016905). This PR bumps `chokidar` package to fix it.
N/A
`chokidar` package is used only in [scripts/widgetBackendWatcher.js](https://github.com/cloudify-cosmo/cloudify-stage/blob/master/scripts/widgetBackendWatcher.js) - script used to trigger stage backend restart on `widget/**/backend.ts` files changes. I checked it manually - works without problems after upgrade.
N/A

RD-6090 Bump `chokidar` package to latest v3 to fix security issue

---

backend/package-lock.json
backend/package.json
backend/test/widgets/executions/references/root-level-task_elk-graph.json

Bumped `elkjs` package version to satisfy Snyk license audit (unfortunately it doesn't say what actually is the problem). 
One thing I spotted is that newer `elkjs` uses EPL-2.0 and not deprecated EPL-1.0.
I did quick investigation and I'm not sure it still is copyleft license and I'm not sure it solves copyleft-license-related concerns.
More: https://snyk.io/learn/open-source-licenses/
We use `elkjs` package only in Executions widget backend.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3668)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3668/) - only Executions widget test - PASSED
N/A

RD-6089 Bump `elkjs` package version

---

test/cypress/integration/flows/admin_spec.ts
test/cypress/integration/widgets/user_management_spec.ts
widgets/userManagement/src/authServiceActions.ts

As described in https://cloudifysource.atlassian.net/browse/RD-6205 the condition for checking if Auth Service is turned on was invalid. This PR fixes it.
This solution may even change in the future, once SaaS solution will become closer to production.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3762)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3762/) - only modified tests - PASSED
N/A

RD-6205 Fix Auth Service presence check in User Management widget

---

jenkins/Jenkinsfile
scripts/buildWidget.sh
webpack.config.js

After migration to Webpack 5 (RD-2853) `build:widget` NPM script in Stage stopped working.
This PR brings it back to live and adds CI check to avoid such issues in the future.
N/A
Manual tests + Jenkins CI pipeline.
Widget building already described in [widgets/README.md](https://github.com/cloudify-cosmo/cloudify-stage/blob/94665179a08b63f37df0836c9a0cbcb8ccc44836/widgets/README.md).

RD-6337 Fix `build:widget` NPM script

---

app/translations/en.json
test/cypress/integration/widgets/deployments_view_spec.ts
widgets/common/src/deployModal/DeployModalActions.tsx
widgets/common/src/deployModal/GenericDeployModal.tsx
widgets/common/src/deploymentsView/header/DeployOnModal.tsx

The reason for the problem described within RD-5423 was that there was no `deploySteps` defined for `GenericDeployModal` used in `DeployOnModal` component. That was fixed withing this PR as well as some other places were updated, so that user won't see Deploy option when deploy steps are not defined.
https://user-images.githubusercontent.com/5202105/202669852-44cfb9d5-77dd-4452-b942-db1927152f0f.mp4
Added Cypress test.
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3875)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3875/) - only `deployments_view_spec`
N/A

RD-5423 Fix support for Deploy action in Deploy On modal

---

test/cypress/support/executions.ts

Looks like `cy.killRunningExecutions` is not handled properly in non-SSL environment (introduced recently in AMI CentOS images - RD-6305). It creates the following URL:
```
http://46.137.48.103/console/sp//executions?status...
```
and that double slash seems to be interpreted incorrectly.
N/A
Testing only selected specs: 
* test/cypress/integration/flows/user_spec.ts
* test/cypress/integration/widgets/deployment_num_spec.ts
* test/cypress/integration/widgets/servers_num_spec.ts
* test/cypress/integration/widgets/snapshots_spec.ts
* test/cypress/integration/widgets/maintenance_mode_button_spec.ts
1. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3889)] (https://jenkins.cloudify.co/job/Stage-UI-System-Test/3889/) - InterruptedException (known …

RD-6430 Improve `killRunningExecutions` cypress custom command

---

test/cypress/integration/login_spec.ts
test/cypress/integration/user_configuration_spec.ts
test/cypress/support/commands.ts

Thanks to @Blewin I adjusted `interceptWithoutCaching` to be generic.
N/A
Not necessary to run system tests I guess. CI only.
N/A

RD-6431 Add generic parameter type to `interceptWithoutCaching` custom Cypress command

---

app/components/layout/GridItem.tsx
app/components/shared/Link.ts
app/components/shared/MaintenanceModeActivationButton.tsx
app/components/shared/PasswordModal.tsx
app/components/shared/graphs/Graph.tsx
app/components/shared/graphs/PieGraph.tsx
app/components/shared/widgets/WidgetsGrid.tsx
test/cypress/components/app/Graph_spec.tsx
widgets/executionsStatus/src/widget.tsx

First part of `shared` components migration to TypeScript.
In another PR(s) the following components are planned to be migrated:
* `app/components/shared/widgets/PageContent.tsx` (requires #2292 )
* `app/components/shared/widgets/Widget.tsx` (more complex change, need to fix widget definition types hierarchy)
* `app/components/shared/MaintenanceModeModal.tsx` (bigger change, I'm planning refactor in maintenance-related properties in Redux store first)
N/A
Added component test for `Graph` component.
N/A

RD-5756 Migrate `shared` components to TypeScript - part 1 

---

app/translations/en.json
test/cypress/integration/widgets/user_management_spec.ts
widgets/userManagement/src/InviteModal.tsx
widgets/userManagement/src/authServiceActions.ts

This PR aligns Invite modal in Users Management widget to API changes introduced in RD-6101 (details in: https://cloudifysource.atlassian.net/browse/RD-6099?focusedCommentId=78457).
Updated `user_management_spec`.
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=3982)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/3982/) - only `user_management_spec` - PASSED
Will be handled in RD-6115.

RD-6099 Add support for tenant and role selection in Invite modal

---

backend/config.ts
backend/server.ts
conf/README.md
conf/app.json
devServer.ts
package.json
tsconfig.json

This PR changes `SERVER_HOST` and `SERVER_PORT` constants into configurable parameters in `conf/app.json` file. This should allow others to use Stage package in docker container.
Direct trigger for introducing such change: RD-6342.
N/A
Local environment (`devServer`) works fine.
System tests:
1. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4025)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4025/) - failed on running backend (no configuration available as `app.json` is handled by Cloudify Manager, fix: https://github.com/cloudify-cosmo/cloudify-stage/pull/2305/commits/34212e552729b015f36df618908784d635cb4c93)
2. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4044)]( …

RD-6525 Move `SERVER_HOST` and `SERVER_PORT` constants to JSON configuration file

---

app/widgets/common/terraformModal/TerraformModal.tsx
backend/templates/terraform/inputs.ejs
backend/test/routes/fixtures/terraform/1_blueprint.yaml
backend/test/routes/fixtures/terraform/1_inputs.json

Removed empty input default from generated TF wrapper blueprint
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4143/
N/A

RD-6532 Remove empty input default

---

backend/package-lock.json
backend/package.json

NPM audit complained about using `flat@4.1.1` and dependabot created automatic PR bumping it's version to `flat@5.0.1` (https://github.com/cloudify-cosmo/cloudify-stage/pull/2356).
Snyk reports revealed issue in `flat@5.0.1`,and suggested to go to at least `flat@5.0.2`, and that change is provided in this PR 🙂 
N/A
Tested locally usage of `flat` package - used when fetching user configuration - no difference between `flat@4.1.1` and `flat@5.0.2`.
N/A

RD-6714 Bump `flat` package

---

test/cypress/integration/widgets/deployments_spec.ts

Improved setting blueprint ID value in one of the tests from Deployments widget test suite.
Before - blueprint ID was expected to be in the first 10 items visible when opening blueprint dropdown.
After - we filter by name first and then expect to see the item.
N/A
1. Local - `deployments_spec` passed.
2. Jenkins
1. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4264)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4264/) - only `deployments_spec` - I suspect that Cloudify Manager was not ready yet to use (failed on uploading blueprint 😨)
2. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4265)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/ …

RD-6660 Use `setSearchableDropdownValue` custom command for setting blueprint ID value

---

package-lock.json
package.json

Executed:
```
npm i --save-optional babel-jest@27
```
in order to solve security issue coming from `babel-jest` v26.
N/A
See CI results - frontend jest tests passed.
N/A

RD-6932 Bump babel-jest package version to fix security issue

---

app/translations/en.json
app/widgets/common/deploymentsView/types.ts
widgets/nodes/src/NodeInstanceModal.tsx
widgets/nodes/src/NodeInstancesTable.tsx
widgets/nodes/src/NodeType.tsx
widgets/nodes/src/NodesTable.tsx
widgets/nodes/src/TypeHierarchyTree.tsx
widgets/nodes/src/props/NodeInstancePropType.ts
widgets/nodes/src/types.ts
widgets/nodes/src/widget.tsx

Full migration of Nodes widget to TypeScript.
In the next PR (https://github.com/cloudify-cosmo/cloudify-stage/pull/2453) further refactoring in Nodes widget will be provided.
N/A
1. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4563)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4563/) - only Nodes widget test - failed due to external issues
2. Tested locally - PASSED.
N/A

RD-5776 Migrate Nodes widget to TypeScript

---

app/widgets/common/actions/SearchActions.ts
app/widgets/common/deployModal/EnvironmentDropdown/EnvironmentDropdown.types.ts
app/widgets/common/deployments/DeploymentActions.ts
app/widgets/common/deployments/DeploymentDetails.tsx
app/widgets/common/deployments/UpdateDeploymentModal.tsx
app/widgets/common/deploymentsView/types.ts
widgets/blueprintInfo/src/actions.ts
widgets/deploymentInfo/src/widget.tsx
widgets/deploymentInfo/src/widget.types.ts
widgets/deployments/src/DeploymentsSegment.tsx
widgets/deployments/src/types.ts
widgets/nodes/src/widget.tsx

1. Extracted `FullDeploymentData` type to `app/common/widgets/DeploymentActions.ts` file
2. Refactored uses of `DeploymentWithUpdate` type
N/A
No functional changes, so types check only.
N/A

RD-5078 Refactor use of `FullDeployment` type and reduce number of `Deployment*` types

---

app/utils/widgetDefinitionsLoader.ts

RD-7081 looks like a minor leftover from RD-6162 (in specific from #2321). 
I searched for `common.js` occurrences and adjusted code accordingly.
N/A
1. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4627)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4627/) (All tests) - FAILED (in addition to known issues failed on `license_spec`, `deployment_button_configuration_spec`, `pages_edit_spec`)
2. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4632)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4632/) (Only 3 specs failing in previous run) - PASSED (I suspect that previous failures were fixed in …

RD-7081 Remove `widgets/common/common.js` reference

---

backend/test/config.test.ts
conf/manager.json

Adjusted default value for Cloudify Manager REST API port.
Related backend change causing issues with our system tests: RD-7056.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4660)](https://jenkins.cloudify.co/job/Stage-UI-System-Test/4660/) - Stage package upload script is not overriding `manager.json` so it's not possible to test it this way :-/
N/A

RD-7092 Fix Cloudify Manager REST API port

---

test/cypress/integration/widgets/deployments_view_spec.ts
test/cypress/support/editMode.ts

The problem described in RD-7116 was not reproducible locally, but deduced from the video that the problem laid in faulty implementation of accessing dropdown component. I found out that we were not using already existing Cypress custom command (which are working flawlessly in other places) for setting dropdown fields in widget configuration. 
This PR changes it and simplifies/refactors section covering tests for configuration of Deployments View widget.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4798)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4798/) - only `deployments_view_spec.ts`
N/A

RD-7116 Refactor Deployments View widget spec to use Cypress custom commands for setting widget configuration fields

---

app/widgets/common/deployments/DeploymentActions.ts
app/widgets/common/deploymentsView/map/DeploymentsMap.tsx
test/cypress/integration/widgets/deployments_spec.ts
test/cypress/integration/widgets/deployments_view_spec.ts
test/cypress/integration/widgets/environment_button_spec.ts
test/cypress/support/editMode.ts
widgets/deployments/src/types.ts
widgets/deploymentsView/README.md

Cherry pick of:
1. https://github.com/cloudify-cosmo/cloudify-stage/pull/2500, 
2. https://github.com/cloudify-cosmo/cloudify-stage/pull/2501, 
3. https://github.com/cloudify-cosmo/cloudify-stage/pull/2503,
4. https://github.com/cloudify-cosmo/cloudify-stage/pull/2504
See PRs provided in Description section.
1. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4821)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4821/) - with Cloudify Manager v7.1-dev and Stage package taken from `7.0-bulk-cherry-pick` branch - all system tests passed.
2. Looks like RND-208 is solved, so triggered [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4826)](https://jenkins.cloudify.co/job/Stage- …

RD-6316 RD-7116 RD-7117 RND-220 Cherry pick from master branch [7.0]

---

widgets/blueprintActionButtons/README.md
widgets/blueprints/README.md

Sync PR after https://github.com/cloudify-cosmo/docs.getcloudify.org/pull/2537.
I think that the change itself is not the best. As a user I don't know what are "permissions" (Blueprint Action Buttons widget) or "correct permissions" (Blueprints widget), but... Don't have energy to fix it, just want to get Stage pipeline to be green again.
N/A
CI.
N/A

RND-278 Sync widget README.md files with user documentation

---

test/cypress/integration/templateManagement/pages_edit_spec.ts
test/cypress/integration/widgets/blueprint_num_spec.ts
test/cypress/integration/widgets/plugins_num_spec.ts
test/cypress/integration/widgets/sites_map_spec.ts
test/cypress/support/editMode.ts

(cherry picked from commit b062a3dbbff504be93a3a0426a74e765469d2b8a)
N/A
https://jenkins.cloudify.co/view/UI/job/Stage-UI-System-Test/4966/
N/A

RND-359 Extend fix for widgets adding (#2538)

---

app/translations/en.json
app/utils/GenericConfig.ts
test/cypress/integration/widgets/execution_logs_spec.ts
test/cypress/support/commands.ts
widgets/executionLogs/src/LogMessage.tsx
widgets/executionLogs/src/LogsTable.tsx
widgets/executionLogs/src/consts.ts
widgets/executionLogs/src/widget.tsx

This PR extends #2533 with "Show more logs" button and basic tests for new widget.
https://user-images.githubusercontent.com/5202105/232470804-aa4b0021-ffac-4b41-8de6-5013ab931605.mp4
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=4979)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/4979/) - full run - 3 tests failed (RD-4589, RD-6838 and something new from `snapshots_spec`), none of them seems related
Will be added as part of [RND-115](https://cloudifysource.atlassian.net/browse/RND-115).
[RND-115]: https://cloudifysource.atlassian.net/browse/RND-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RND-107 Create Execution Logs widget - part 2

---

test/cypress/integration/widgets/execution_logs_spec.ts
test/cypress/support/commands.ts

This PR fixes issue introduced by https://github.com/cloudify-cosmo/cloudify-stage/pull/2541 and described in RD-7152.
The fix adds support for Resource Filter widget configuration (which is used in all tests using `usePageMock`) and reverts default configuration to the one used prior merging https://github.com/cloudify-cosmo/cloudify-stage/pull/2541.
N/A
1. Manual Cypress test execution on Resource Filter widget and Execution Logs widget specs - PASSED
2. Full system tests run - [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=5029)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/5029/) - failed on known issues only (RND-527, RND-533, RD-7153), so I'm considering it as PASSED
N/A

RD-7152 Add support for Resource Filter widget configuration in Cypress tests

---

test/cypress/integration/user_configuration_spec.ts
test/cypress/integration/widgets/deployments_view_spec.ts

As RD-6631 has been bothering us for a long time, I turned on test retries mechanism in `user_configuration_spec`.
In order to do that I had move problematic part out of `before` hook as according to [Test Retries - How it works](https://docs.cypress.io/guides/guides/test-retries#How-It-Works):
> failures in before and after hooks will not trigger a retry.
N/A
Only `user_configuration_spec`:
1. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=5086)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/5086/) - hit, retry helped 
2. [![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=5087)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/5087/)
3. …

RD-6631 Add retries in run mode for `user_configuration_spec`

---

app/widgets/common/inputs/fields/DeploymentIdInputField.tsx
test/cypress/integration/widgets/deployment_button_deployment_inputs_spec.ts

Fixed URL in `DeploymentIdInputField` component (it was by mistake changed long time ago within #2324 ).
The bug was not detected by our test (`deployment_button_deployment_inputs_spec.ts`), because the method used in that test to verify input field options was buggy. Test fix is part of this PR.
Once merged, this PR will be cherry-picked on `7.0.1-build` branch.
N/A
[![Build Status](https://jenkins.cloudify.co/buildStatus/icon?job=Stage-UI-System-Test&build=5179)](https://jenkins.cloudify.co/view/UI%20Health%20View/job/Stage-UI-System-Test/5179/) - failed on `environment_button_spec`, seems like due to test flakiness, retested locally and it passes => I consider tests as PASSED
N/A

CYBL-2046 Fix data source in Deployment ID input field

---

backend/package-lock.json
backend/package.json

This PR updates cloudify-ui-common-backend to version 1.3.4, This should fix issue with audit, where we used vulnerable version of axios inside the package.

NE-31906 Update cloudify-ui-common-backend to 1.3.4

---

backend/handler/templates/PageGroupsHandler.ts
backend/package-lock.json
backend/package.json

This PR updates to the latest version `sanitize-filename` and fixes vulnerability present in `getUserPageGroupPath` in `PageGroupsHandler.ts`
This fixes reported vulnerabilities: [NE-32814](https://jira.cec.lab.emc.com/browse/NE-32814) [NE-32815](https://jira.cec.lab.emc.com/browse/NE-32815) [NE-32816](https://jira.cec.lab.emc.com/browse/NE-32816) [NE-32818](https://jira.cec.lab.emc.com/browse/NE-32818)
From [NE-32196](https://jira.cec.lab.emc.com/browse/NE-32196): Absolute Path Traversal 10, 11, 12, 13

NE-32814 Fix Absolute Path Traversal Vulnerability

---

backend/package-lock.json

```
braces  <3.0.3
Severity: high
Uncontrolled resource consumption in braces - https://github.com/advisories/GHSA-grv7-fg5c-xmjg fix available via `npm audit fix`
node_modules/braces
```
Applied fix with `npm audit fix`

audit: update braces package to 3.0.3

---

jenkins/Jenkinsfile

Fix RPM Build step in the pipeline, by replacing no longer available mirror repo for yum with vault.
N/A
N/A
N/A

Fix RPM Build issue with mirror not longer available

---

package-lock.json
package.json

Updated express version in webpack-dev-server, to 4.19.2 from 4.18.2. Version 4.19.0 fixes open redirect vulnerability. See here for information about vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2024-29041.
In previous PR updating express I missed express usage in frontend, because it's just dev usage, but since there are no breaking changes here, we can update it safely. I tested locally `devServer` command and seems to work without issues.
N/A
N/A
N/A

NE-31913 Override express version in webpack-dev-server to not vulnerable one

---

backend/config.ts
backend/routes/Config.types.ts
backend/server.ts
conf/app.json

From [node documentation](https://nodejs.org/docs/latest-v18.x/api/net.html#serverlistenport-host-backlog-callback):
> If host is omitted, the server will accept connections on the [unspecified IPv6 address](https://en.wikipedia.org/wiki/IPv6_address#Unspecified_address) (::) when IPv6 is available, or the [unspecified IPv4 address](https://en.wikipedia.org/wiki/0.0.0.0) (0.0.0.0) otherwise.
>
> In most operating systems, listening to the [unspecified IPv6 address](https://en.wikipedia.org/wiki/IPv6_address#Unspecified_address) (::) may cause the net.Server to also listen on the [unspecified IPv4 address](https://en.wikipedia.org/wiki/0.0.0.0) (0.0.0.0).
We were setting `localhost` by default in the configuration, which on some systems where ipv6 was available, it would listen only on …

Remove default host from server.listen to allow by default to listen on ipv6 and ipv4

---

devServer.ts
jenkins/build-pod.yaml

After latest change from #2647 `npm run devStart` stopped resolving correctly backend address due to it not longer defaulting to `localhost`. In the context of resolving backend address, we can safely fallback on `localhost`, hence this change.
N/A
N/A
N/A

Correct local backend address when starting frontend dev server
